kbase/narrative

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeControlPanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

This mainly addresses Issue #102 
* Remove code and text cell buttons
Not addressed yet, until #90 gets fixed
* Search button in style (should be title?) bar
Done
* Clicking search button should toggle search text box
Done
* Search text box should be fixed position
Done
* Design iteration on ‘more’ button (turn +/- to …)
Done
* click anywhere except for icon/title to pulldown
Done
* Add filter based on data input/output type (e.g. “type:KBaseGenomes.Genome”)
Done. Entering "type:XXX" searches among all parameters for each method and app for "XXX" in their allowed types. If present, that method/app passes, if not, then it gets filtered out. It actually searches for "XXX" somewhere within the type string itself. So, if the type is "KBaseBiochem.Media", then "media" matches, "biochem" …

Method panel styling - issue #102

---

src/config.json
src/notebook/ipython_profiles/profile_narrative/kbase_templates/page.html
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeCellMenu.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

This adds a couple of things, related to issue #116.
The first is a 'mode' configuration in config.json (currently set to debug).
The second is an additional cell menu option that appears in debug mode - at the top of the menu is a 'View Job Submission' option. Now, when an app job is run in debug mode, all of the results of that initial set up (all communication from the kernel) is stored in that app cell's metadata. Clicking that new menu item will do two things:
1. This will dump the contents of that info into the Javascript console (including a few message strings)
2. Create and run a code cell that contains the job info that gets returned on a successful job submission. Having this cell auto run registers that object as a variable, and prints it out in a nice way (it's a substantial …

Add debug mode for app jobs

---

src/biokbase/narrative/kbasewsmanager.py
src/biokbase/narrative/tests/test_kbasewsmanager.py
src/biokbase/narrative/ws_util.py
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js

This adds a count of each cell type to the Narrative object's metadata. For app and method cells, it keeps a count of which app and method was used. This all gets shuffled together as a dictionary like this (as an example):
<pre><code>{
'method': {
'my_method_id': 2,
'my_other_method': 3,
},
'app': {
'an_app_id' : 1,
'another_app_id' : 2,
},
'output' : 0,
'ipython' : {
'code' : 6,
'markdown' : 3
}
}</code></pre>
The numbers are just the counts of those cell types.
This also contains a small bugfix for an error that happens if a job tries to update a cell that's been deleted.

Narrative metadata update

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseNarrative.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

This should fix that issue. It's a little bit of a hack in places, since we don't want those to appear over KBase cells (app/method/output/error). However, the best way to tell when a new cell is created is to catch the create.Cell IPython event.
Now, when a KBase-ish cell is created, that menubar is explicitly hidden, but shown when any other cell is made.

Issue #91: Show cell menubar when new code/markdown cells are created

---

src/biokbase/narrative/common/kbjob_manager.py
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseNarrative.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

This has a number of changes to how App and Method cells behave. Now:
- Running Apps and Methods have a "Cancel" button associated with them. Clicking that will restore the cell to its input state, and cancel (and delete) the running job
- Deleting App/Method cells now prompts to delete, warning the user that it'll kill any running job (if they've been run before)
- Deleting jobs now triggers the call to the right back end services to delete the running job itself.
- Deleting a job from a running cell now unlocks that cell so its inputs can be used again.
- Added new error checking for different states
- A dangling job with no associated cell should properly error.
- A dangling job on the front end that's been deleted on the back should properly error.
- A job in an error state (not the …

Better job management/canceling support, Fixes to App and Method cells to deal with cancellations

---

src/biokbase/narrative/services/generic_service_calls.py
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseNarrativeError.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeOutputCell.js

Addresses the following issues:
- KBASE-1199 "time stamp issues - annotation"
Newly registered jobs weren't having their timestamps rendered right, though this gets fixed after a refresh. It should work now.
- KBASE-1210
Debug info for methods wasn't being properly sent to the console. Now it should be. **This doesn't actually fix the issue, but it helps diagnose what's happening**
- NAR-400 "Jobs not loading in jobs panel"
- KBASE-1202 "Running jobs list doesn't update correctly"
- KBASE-1192 "jobs view not updating"
- KBASE-1191 "assemble and annotate"
The root cause for these - especially with the jobs panel locking up - was that a completed job was trying to render an output widget that didn't exist. This caused a small chain of uncaught exceptions that resulted in the jobs panel …

Fix jobs panel

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/css/kbaseNarrative.css
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterTextareaInput.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js

Fixes NAR-441
When narratives are deleted outside of the narrative interface, without deleting the containing workspace, that workspace is corrupted, throwing an error and causing other narratives not to render.
This fix detects this case in the narrative manage panel, shows existing and corrupt narratives, and provides an option to delete the corrupt narrative.

Improved handling of corrupt narratives

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/page.html
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseNarrative.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_input/create_metagenome_set.js

This puts the current workspace id in the global namespace as soon as the page starts. Should avoid any issues with widgets trying to instantiate that variable on page load.

NAR-465 fix

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/css/kbaseNarrative.css

This PR should fix that. Just tweaks the z-index of a couple of panels.
The share panel falls behind the overlay now, but that's expected.

Overlay overlapping 'about' dialog

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/notebook/js/notificationarea.js

The IPython websocket error doesn't have the same meaning in the KBase Narrative, and needed to be updated. This PR does so, and removes the 'OK' button (since that doesn't really have meaning either - it's not like the user can just reboot their instance and reconnect to it).

Websocket text change

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/css/kbaseNarrative.css
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js

Added a little more sanity to the job error panel. Now, instead of blowing off the screen with multiple error traces, it should be a little more compact.
This is also making room for additional, non-blocking, error states. E.g. network connection errors while looking up jobs.

Job panel fixes

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/page.html
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/css/kbaseNarrative.css
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/css/kbaseStylesheet.css
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseNarrative.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/notebook/css/override.css

This adjusts a number of style rules to meet issue #161. This also relates to the following tickets:
- https://atlassian.kbase.us/browse/KBASE-1304 - this was a race condition where job lookup attempts happen before a cell's parameters are loaded. When this happens, the job lookup can't map between what are supposed to be user-provided output parameters and what's supposed to be autogenerated by the job result.
- https://atlassian.kbase.us/browse/KBASE-1196 - using red for a running state makes it look like an error. This was changed to blue
- https://atlassian.kbase.us/browse/NAR-421 - removed the styling from code and markdown cell toolbars.
Finally, it removes rounded borders from a few elements that shouldn't have them, so we can keep a little more consistent.

Styling changes and a bugfix

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

Apparently dropdowns in firefox pick the first option that has a non-empty value as the default, while in chrome/safari the first option is always selected.  Thus in firefox a type filter was always set at first, but the data isn't filtered as such until another filter event is triggered.  So on search, this causes strange behavior because it looks like everything is there, but then when a search starts the type filter is immediately checked and applied making it seem like some data disappeared when really a hidden filter was on!
Arg!!!!

Fix for bug in firefox search in data list

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

When refreshing narrative data in the background, if the WS cannot be connected, an error doesn't hide the existing view of data.
addresses: https://atlassian.kbase.us/browse/KBASE-1477

Data panel no longer hides data on network interrupt

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js

Fixes two things.
1. If the user has no valid narrative objects to look up, it just doesn't render anything.
2. Fixed an issue where the narratives panel was loading twice on page load.

Nar 651 fix

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js

related to changes from https://github.com/kbase/narrative/pull/261
Due to the other change from 261, when the height of the window is small, an extra scrollbar appears causing the mouseover of data to shift the text in an annoying way.  This is fixed.

Minor data/method list UI tweak

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/page.html
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js

Two semi-crucial things here:
1. Hide all non-specified 'viewer' widgets That functionality is duplicated by clicking the data object or doing a drag-and-drop with it.
2. Set the page title from a slightly incorrect User Testing Narrative to KBase Narrative in preparation for production.

Removed 'viewers' widgets from view, changed default page title

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js

A minor feature that's been requested several times now.  See: https://atlassian.kbase.us/browse/KBASE-1607
Note that longer term the plan is to organize these types into groups to make it easier to find types when you don't know the name of a type beforehand.

Dropdown to filter by data type is now sorted

---

RELEASE_NOTES.md
src/biokbase/narrative/__init__.py
src/config.json

Preliminary 1.0.3 release notes that capture a few minor changes and bugfixes. There will probably be more before the production 1.0.3 deployment, but doing this now to ease the process of testing on narrative-dev.

Updated release notes, version 1.0.3

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/page.html
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseNarrative.js

This changes the update button text to read "Get new version!" which is more actionable, and clearly prompts the user to click there, as opposed to the more passive "New Version Available!" text.

NAR-783 Change update button text

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseNarrative.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/notebook/js/savewidget.js

This change does two things.
1. It pulls out some hacky things that were injected into the IPython notebooks savewidget.js, and puts them where they belong.
2. It addresses a special error condition we've come across (https://atlassian.kbase.us/browse/KBASE-1843) where a Narrative object that is too large gets rejected by Nginx with a 413 error (Request entity too large). Currently, the maximum Narrative object size is set to 4 MB, which is pretty substantial, but we should have a discussion to decide what's actually reasonable. The Workspace can handle objects of nearly any size - several megabytes is no big deal - but this does create a performance cost on the front end.
Partly, I'm of the "caveat emptor" mindset that we should let the user do what they like and absorb the consequences, …

Modify save error messaging.

---

buildNarrativeContainer.sh
docker/Dockerfile.base
docker/Dockerfile.update

This addresses https://atlassian.kbase.us/browse/NAR-391 where the base Docker image was failing to build. There were a couple of main errors going on here:
1. The R repository used was set to .org instead of .edu, so it was defaulting to Ubuntu, meaning that most packages were out of date.
2. The automatic pip installation through apt (apt-get install python-pip) results in an unusable pip. Updating it with easy_install fixes it for now, will revert once the official Ubuntu fix is made.
3. An earlier bug (that was actually fixed! but masked by the above two) was fixed. The public ANL Ubuntu mirror was taken down - this was replaced by the PNL mirror.

Base image fix

---

.travis.yml
Makefile
narrative_backend_tests.sh
src/notebook/ipython_profiles/profile_narrative/kbase_templates/Gruntfile.js

This includes a .travis.yml file, and modifications to the Makefile and Gruntfile to handle testing. Since tests all run against PRs, and it's easy enough to update a PR before it's accepted/closed, this will be ongoing for a little while.
This one will be a little tricky because it contains multiple languages to test. This sets the base .travis.yml file to use NodeJS for testing, and will (eventually) install the Python dependencies in the script.

First pass at getting Travis-CI set up for the narrative.

---

README.md

Minor fix. Now that Travis and Coveralls are set up to deal with the Narrative, this adds a status badge for each of the branches of note - develop, staging, and master.

Added Travis-CI and Coveralls badges to the readme.

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/notfound.html

See https://atlassian.kbase.us/browse/KBASE-2042
When a Narrative is unavailable - whether it doesn't exist, or a user doesn't have permission to see it - this template is displayed. This fixes a typo and a couple out of date links on that page.

Fix error text when a narrative is unavailable

---

docker/Dockerfile.base

One of the R packages requires OpenGL headers, which are in the mesa-common-dev package.  Added the package.  I also moved the R build to be last; the hope is failures in previous steps abort before doing the R step, which takes an insanely long time.

add mesa-common-dev to package list

---

docker/docker.lua

There may have been a change in how the VolumesFrom config option is interpreted by the lua code.  It used to be that an empty string would work, but the variable is supposed to be an array, and the empty string is now an error.  json.util.null populates VolumesFrom with an empty array.

Config change in docker.lua

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/custom/custom.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseNarrative.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/narrativeLogin.js

This addresses NAR-804 - a race condition failure that sometimes happens on Narrative startup.
The issue is that the KBase code is loaded asynchronously, but still requires that IPython code is present, and certain events are fired at the right time. Specifically, it was set that the Narrative code waited for the first status_idle.Kernel event to be kicked off before starting up. This ensured that everything was in place before starting, including auth info and workspace info.
This PR fixes the problem by doing two things.
1. Load the KBase startup code in custom.js before running the IPython main function. This registers the needed event listeners at the right time.
2. Use the notebook_loaded.Notebook event, which is fired once when the notebook is successfully loaded.
This will all be …

Nar 804 race condition

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/page.html
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseNarrative.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/narrativeConfig.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/narrativeMain.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/narrative_paths.js

This adjusts the configuration management to load it all asynchronously, and it more tightly controls the load order of JS modules for the Narrative.
The goal here is to combat a race condition that popped up in the last PR (which was only discoverable once deployed on narrative-ci) where Narrative files were populated in the interface before required Javascript was loaded. This meant that strange behavior was seen, including broken app and method cells since their interface code wasn't loaded.
I worked through this problem while starting to upgrade to IPython 3 (upcoming WIP PR today), and applied the same solutions here.
At the same time, this makes a discrete configuration loading module that loads the config and icons files asynchronously in a separate script, not in the main page.

Adjust load order and configuration loading.

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/Gruntfile.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/page.html
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/custom/custom.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseNarrative.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/narrativeConfig.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/narrativeMain.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/narrative_paths.js

This fixes an issue where a file (IPython's notebook/js/main.js) that should not be compiled during the JS minification process was getting added. Because it is not an AMD itself, that means that as soon as the minified file was loaded, that script was run, which was done very much out of order.
This PR removes that file from the build step, so it is only properly downloaded and executed at the right time.

Adjustment to load order, fix compilation step

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js

This small change adds a runMethod function to kbaseNarrativeMethodCell so that we can run a method cell without user interaction.  This is a step towards being able to automatically create a method, set parameters, and run the method, which will be useful for some of the feature-value user stories.

API function for running a method cell

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeCellMenu.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js

I've been working out how to automatically create a method with parameter values set in the Narrative via the JS api, and have a potentially useful feature here to copy a narrative method including parameter values.
This could be useful because we can copy narrative methods even after they've been run.  So it allows a user to essentially rerun something without reentering all the parameters.
This could probably be done for apps too, but is slightly trickier because we need to find a way to ensure the the app input widgets are all fully loaded before we update state.
Thoughts on this feature?

Duplicate a narrative method with parameter values

---

src/biokbase/narrative/common/kbjob_manager.py

Occasionally, on CI, a UJS job lookup will fail because something spazzes out with the UJS/proxy client, and returns a (transient) URLError. This patch does two things.
1. Treats that error as a 'network_error', which is non-fatal, so it'll lookup the job info again on the next cycle.
2. Properly escapes any <> characters that the exception's message string contains so they can get rendered right. Silly HTML thinking angle brackets are always tags!

Updated kbjob_manager to treat urllib2.URLErrors as network errors.

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/css/kbaseNarrative.css
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

This update consists of:
1) When a method is run, it is automatically collapsed, and 'replacement' text is shown that allows us to briefly summarized the step the user performed.  The replacement text is pulled from the replacement text field in the narrative method specification (for example, here: https://github.com/kbase/narrative_method_specs_ci/blob/master/methods/reannotate_microbial_genome/display.yaml#L14).  This was already a feature in the narrative method store, so it will just work if you update the specs.  The cool thing is that the replacement text uses http://handlebarsjs.com so you can include parameter values in the replacement text (and do things like have conditional expressions, show the length of an array input, etc)
2) When an app cell runs, the method input fields …

Minimize methods on run and add summary text

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_input/kbaseNarrativeMethodInput.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterTextSubdataInput.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/narrative_paths.js

This introduces a new type of parameter that allows autocomplete of fields based on subdata selection of a workspace data object.  This is useful, for instance, for selecting features from a genome or elements of a model.  It is generalized (built on the workspace generalized subdata query), so you should be able to select anything in a list/map in a WS data object, and use those values to populate the dropdown.  The WS data object can either be one selected in another parameter, or a fixed object(s) (by WS reference id) which I think will be useful for instance if we want to force selections from a controlled vocabulary.
The Narrative Method Store was updated to support the new parameter, and I setup an example method specification in CI here.  You can see in the spec how the subdata …

New subdata autocomplete method parameter type

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseNarrative.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

This change allows us to add a method, populate parameters, and run it through an API call.  This is useful for widgets that need to trigger some additional narrative action, like computing some statistics on data selected in a widget using an existing narrative method, or calling a method to create say a FeatureSet based on features selected in a widget.
This is an important because it means we still get nice usability without having to create heavyweight widgets that do analysis internally, making it easier for people to see what is happening in a narrative.
You can test it out directly from the JS console like so:
```
var method_id = 'example_subdata';
var parameters = {
'input_model':'model',
'input_rxns':['rxn1','rxn2'],
'input_cmpds' : 'cmpds1,cmpds2',
'input_template' : …
```

Added Narrative API call to create and autorun a method

---

src/config.json

Should be looking for widgets on narrative-ci, not narrative-dev... Oops.

Wrong path for the CI ui-common-root

---

RELEASE_NOTES.md
src/biokbase/narrative/__init__.py
src/biokbase/narrative/kbasewsmanager.py
src/biokbase/narrative/magics.py
src/biokbase/narrative/monkeypatch.py
src/biokbase/narrative/ws_util.py
src/config.json

See JIRA ticket: https://atlassian.kbase.us/browse/KBASE-2626
When the Workspace service is unavailable (due to misconfiguration, downtime, cosmic rays, etc.), a newly started Narrative will just bail out, and shut its IPython process right back down. A little annoying, maybe, but not really a problem unless you're running this as a process in a Docker container. Then it takes the container down with it, since the process finishes. Even worse, if you're provisioning a bunch of containers at once, and trying to maintain a queue of loaded containers, that'll cause some serious churn as they start up and shut down repeatedly.
This PR fixes that but inserting an error into the log, but it keeps IPython alive. Trying to fetch any narratives will likely result in a 404 (a restriction due to a …

No longer auto-quit when the Workspace service is unavailable

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionConditionsetBaseWidget.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionFeatureTableHeatmap.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionGenesetBaseWidget.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionMatrix.js

In some cases if a particular expression data statistic is undefined (as opposed to null), the entire table will not render.  This PR fixes this bug.

Small bug fix in Expression widgets

---

RELEASE_NOTES.md
src/biokbase/narrative/kbasewsmanager.py

This fixes a bug where shared narratives weren't always saving properly. If Alice makes a narrative and shares with Bob with edit (not share) rights, Bob wouldn't be able the narrative.
This just fixes that error so saving can occur.
However, due to how Narrative names get presented, altered names won't always appear right. The Narrative object in the NI might get a different name than what's shown on the Dashboard. This is more of a minor cosmetic bug, though, and will be put off until after the RSV.

Fix shared saving

---

src/biokbase/narrative/common/generic_service_calls.py
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseFeatureSet.js

When features are not properly linked to a Genome, or cannot be found in a Genome, provide an error/warning per feature rather than an error that shows nothing.  This is useful for allowing the featureset object to still be inspected and for debugging.

Improved FeatureSet widget error handling

---

.gitignore
bower.json
kbase-extension/kbase_templates/notebook.html
kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/kbaseNarrativePrestart.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/narrative_paths.js

The main problem was that the jquery-ui tooltip plugin was being loaded after the bootstrap one, so tooltips, at least on the data list panel (I didn't check elsewhere), were rendered in the jquery-ui style, which was in the incorrect format and also did not place tooltip content as html, so character entities were displayed as plain text. 
The fix for this was to set jquery-ui as a dependency of bootstrap, and to load bootstrap in the main loading script rather than jquery-ui.
Secondarily, there were minor display problems with the data list tooltip. On the first item of the list, the tooltip would display above the item, and was mostly hidden inside containing element. The solution was to set the tooltip to try to display above the item, but if that would cause the tooltip to bump into …

Set of changes to fix malformatted tooltips on the data list panel

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

This PR fixes JIRA issue KBASE-1360.
The re-run button had wandered off with recent changes. This replaces it with a few other state changes.
1. When a method/app cell finishes running, the Cancel button is replaced by a 'Edit and Re-Run' button. Clicking this unlocks the input fields and re-enables running the cell.
2. Fixes other state management problems - lingering run icons and lingering error state borders.
3. In a method cell, the generated output is placed in a new cell. But in an app cell, the generated outputs are placed directly below each method. When re-running an app cell, the previously generated output viewers are removed. The data objects stay behind, however, and can be viewed by clicking on their names or dragging and dropping.
4. After running, if next steps are …

Put in 're-run cell' button

---

RELEASE_NOTES.md
src/biokbase/narrative/__init__.py
src/config.json

The new feature here is preliminary SDK support.
With any luck, this'll be the last release before upgrading the backend to Jupyter 4.0.6.

Bumped version to 1.1.0

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/api/Catalog.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/api/NarrativeJobServiceWrapper.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseRegisterRepoState.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseReportView.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseViewLiveRunLog.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/narrative_paths.js

This PR improves the register SDK module widget, updates the JS catalog and NJS wrapper clients, adds a method to show the live logs of running (or recently completed) SDK module jobs, and adds a simple widget for the new Report data type.

Changes/additions to support the SDK

---

kbase-extension/static/custom/custom.js

double click expands closed cells - before it was putting the cell into edit mode without actually toggling the visibility, which was weird. this is accomplished in the double click event on the cell bind_events.
toggling no longer interferes with edit / render state - on the other hand toggling put the edit/render cell areas into unexpected states. this fixes that by avoiding jQuery hide/show, instead adding display="none" to hide, and simply removing it (and thus returning to unmodified state) to show. 
Will be nice to get this working consistently across cell types, but this was targeted to have double click work more or less for markdown cells, in which it already does something. I'm not sure double click does anything interesting elsewhere.

improve markdown cell behavior

---

kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

The trick here was to hinge the "selected.cell" jQuery event upon the extension of cell.select. Previously it was emitted from the "select.Cell" jupyter event. However, there are cases in which the cell.select is called directly, and no select.Cell event is emitted. This change covers all cases of cell selection.

fix non-activation of cell toolbar buttons when cell selected due to cell deletion

---

kbase-extension/static/kbase/css/landing-pages.css
kbase-extension/static/kbase/js/narrativeLogin.js
kbase-extension/static/kbase/js/widgets/kbaseLoginFuncSite.js

This was because it was implemented with some bootstrap styles, but not completely (in other words, broken as far as bootstrap goes), with manual event handling on the dropdown button to handle closing the dropdown. It required some style changes, and at the same time styles embedded in the login widgets was moved into css. Also added code to set up the login initially upon widget initialization (hide or show the appropriate primary button.)

Fix login dropdown requiring click on button to close - click anywhere should close

---

kbase-extension/kbase_templates/notebook.html
kbase-extension/kbase_templates/page.html
kbase-extension/static/ext_components/jquery-extensions/js/jquery.svg.js
kbase-extension/static/kbase/config.json
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/kbaseNarrativePrestart.js
kbase-extension/static/kbase/js/widgets/function_input/devDataViz.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeExampleDataTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSharePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSideImportTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePublicTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
src/config.json

Some cleanup to the kbaseNarrative module:
* the save_failed callback that was set up in init() now gets its own function
* all Jupyter event handlers how set up in the right spot (registerEvents)
* removed dependency on genome_comparison for finding full user names (remember that?)
Created a Util/Display module for some display utilities
* added displayRealName to that module - give it a username and a jquery node target, and it'll format that as "Full Name (username)" where username is a link to the profile
* added a getUserProfile function. This is a shorthand to the UserProfile client call of the same name (get_user_profile). Just like that call, it returns a promise for the result, but it also caches that promise. Useful for doing displayRealName lots of times, so it doesn't spam the …

Cleanup and startup modification

---

KNOWN_ISSUES.md
kbase-extension/static/custom/custom.css
kbase-extension/static/kbase/css/kbaseNarrative.css

Fixes the problem where there was an overlapping invisible div just below the header bar, above the side panel headers (so it's hard to toggle between 'Analyze', 'Narratives', and 'Jobs').
Also added a KNOWN_ISSUES.md file with ongoing work on the visual junk in the upgrade. Made this a file instead of an JIRA ticket list for easier reading and rapid updating.

Fix invisible overlapping div, added 'known issues'

---

KNOWN_ISSUES.md
kbase-extension/static/custom/custom.css
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseTree.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeCellMenu.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

Clicking buttons on unselected cells (specifically the run buttons or the delete button) would often cause behavior to be based on the other selected cell. For example, a different cell would get deleted, or output cells would appear in the wrong place.
This fixes that by properly binding each KBase widget to the right cell. Instead of just assuming it's selected and calling `Jupyter.notebook.get_selected_cell()`, call  
`Jupyter.narrative.getCellByKbaseId(id)` or  
`Jupyter.narrative.getCellIndexByKbaseId(id)`.
The ids are in the $elem bound to the KBase widget.

Fix cell selection issues

---

src/biokbase/narrative/narrativeio.py

The exact version check was put in as a semi-hack some time ago to ensure things work on CI. Now it's clear that loading up any narrative will reconcile the right version, so it'll always be saved as the right version.

Removed typed object version requirement from save routine.

---

KNOWN_ISSUES.md
kbase-extension/kbase_templates/page.html
kbase-extension/static/custom/custom.css
kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
kbase-extension/static/narrativeMain.js

The read only mode toggle button works again. it still remains in view only mode until page reload, even if share settings change while viewing the page.
Additionally, you can now slide the left control panel out and back. It might be worth decoupling that from read only mode and still allowing usage. Honestly nothing much would change there, except for allowing existing run buttons to be pressed, and keeping the "View-only mode" message from showing. The only work to be done there would be where and how to define the toggle button.

Fix read only mode

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseFbaModelComparisonNew.js

It now uses the narrativeConfig module to fetch url configs, Bluebird for Promises, and the util/string module for uuid generation.
Some docs on those here: https://github.com/kbase/narrative/blob/develop/docs/developer/widget_helper_modules.md
And Bluebird is used throughout kbase-ui - this is just an early attempt to keep caught up.
Also, it looks like a lot of changes below, but most of it is my editor rearranging whitespace a bit.

Update new fba model comparison widget

---

kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/api/Catalog.js
kbase-extension/static/kbase/js/util/display.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
test/unit/spec/Util/DisplaySpec.js

This updates the methods panel to add several new features and provide a minor performance improvement:
1) instead of pulling complete specs of methods to filter by type, uses the new NMS brief info object.  So much less data has to be pulled and filtering by type is faster.  Specs are pulled when a method is added or a spec is requested.
2) Custom method icons are now displayed if they are registered with the SDK method or the NMS (also pulled out that code into a util function, with a few new tests, so this isn't copied in multiple places)
3) Links in the method panel and method/app cells are updated to point to the new App Catalog
4) Support for favorites is now in the methods panel.  Your favorites will be sorted to the top of the list, ordered by the date that you added a method to …

Methods Panel Update

---

kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeControlPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePanel.js

We should have just done this a while ago!  This turned out to be relatively simple fix.  Added a callback option to the side control panels widget that is triggered when a panel is minimized/maximized.  This is now wired to setting the height of the data and method list, so these lists now dynamically resize to fill up the free space in the side panel.
This isn't the more complicated 'responsive' fix to adjust things everytime the browser resizes or on different screen resolutions, but it's much better than what we have now.
This also tweaks a style so we never get multiple scrollbars appearing in the side panel.

Data and Methods side panels now dynamically resize

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeControlPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePanel.js

The changes from my PR last night had a side effect of removing scroll bars in the narrative and jobs panel.  I realized that the cleanest way to fix this is to just finally make the heights responsive to the window height, which turned out to be fairly straightforward given the new methods for setting the height of the control panel widgets.  So that finally works now!
I also made a separate minor styling change by removing the titles to the 'Narrative' and 'Jobs' panel.  I think it looks better, but could still use some styling tweaks (for instance, the jobs list seems compressed slightly more now).  We can always revert that or work on styling when we find time later.

More side panel improvements

---

kbase-extension/kbase_templates/page.html
kbase-extension/static/custom/custom.css
kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/function_input/kbaseNarrativeMethodInput.js
kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterCheckboxInput.js
kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterDropdownInput.js
kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterFileInput.js
kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterTextInput.js
kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterTextSubdataInput.js
kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterTextareaInput.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeControlPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

Made a number of style changes today, and hopefully closed a couple tickets.
* Toggle button now behaves as expected in read only mode (it was still showing jobs before)
* Slightly off-kilter Narratives and Jobs panel (as mentioned in #507 ) should be more on-kilter now
* removed extraneous padding at top of Narratives panel
* Jobs should stretch all the way across the panel again
* https://atlassian.kbase.us/browse/KBASE-2034 - the cancel copying narrative button should work again (also adjusted styles on those buttons)
* Fixed cell minimizing/maximizing that caused the title and icons to wobble.
* Parameter tooltips should float in the 'body' element now, so you can see them.
* https://atlassian.kbase.us/browse/NAR-565 (among others, I'm sure, I just can't find them) - overlapping text …

A bunch of style changes

---

kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

See issue: https://atlassian.kbase.us/browse/KBASE-3578
The problem was that when loading states, the process looks for what it expects are a unique id selector of `div[id^=kb-cell-X-UUID]` but that was showing up multiple times, at least once in the subtitle that had its structure shuffled around recently. This patch removes the duplicate.

Fix problem with method cell states not getting reloaded.

---

kbase-extension/static/custom/custom.css

Bootstrap tabs (that we use all over the place) are rendered as fancy things on top of an html list. This fixes some margin issues with that.

Fix problem with output cell tabs having a gigantic margin.

---

kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeCellMenu.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeOutputCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

Fixes a few things that were brought up:
1. the cell title for markdown cells shouldn't be present while maximized
2. double-clicking the min/max button (and anywhere in the toolbar, really) could unexpectedly put that into edit mode.
These changes block double-clicking on the toolbar from affecting the cell state, and hide the title on markdown cells only while in an expanded state.

Markdown cell behavior

---

kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js

See https://atlassian.kbase.us/browse/KBASE-3623
Loading an old version narrative (like what's all in production), then saving it, could revert the narrative name to 'Untitled'. This explicitly puts the name where it's supposed to be when loaded, so saving doesn't change anything.
This also fixes a problem when making a copy of a shared narrative from the narrative manager panel.

Fix narrative name change from old version

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js

This addresses https://atlassian.kbase.us/browse/KBASE-3624
- just a silly typo in the setup for that link.

Typo in link html caused linkouts to the method man pages to fail.

---

RELEASE_NOTES.md
src/biokbase/narrative/__init__.py
src/config.json

Includes a few tickets addressed, today's PRs that were accepted.
As a note - I think it was useful this time last year to bump the Narrative's semantic version much more frequently (e.g. before deploying to test servers). We were struggling along up to now to get to the 2.0.0 release targets on Next, but now that it's there, I think it'll help tell the difference between changes to bump the version before each ongoing release.

Bumped version to 2.0.1, added release notes.

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotation.js
src/biokbase/narrative/__init__.py
src/config.json

See https://atlassian.kbase.us/browse/KBASE-3556 - complaint was that data on opened gene tabs was redundant with what's in the gene list. Those links will now open the landing page. This also includes a change to make the contig ids in the gene list clickable.

Address issues in genome widget

---

KNOWN_ISSUES.md
RELEASE_NOTES.md
kbase-extension/static/kbase/js/util/bootstrapDialog.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSharePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

See: https://atlassian.kbase.us/browse/NAR-838 and https://atlassian.kbase.us/browse/NAR-839
Fixes problems with the delete cell modal (appears when deleting a cell linked to an existing job).
1. Now uses the BootstrapDialog module (less jquery solution, more pure bootstrap, which lets their code solve problems).
2. Pressing 'enter' to trigger the delete should delete that cell and close the dialog as usual.
3. No longer creates a new dialog for each cell - just a single dialog that sits in the DOM and gets rebound as needed, and shown/hidden as managed by Bootstrap JS code.

Fix delete cell modal problems

---

kbase-extension/static/kbase/css/kbaseNarrative.css

Somehow all borders were removed from .btn , and it was depending on subclasses (btn-danger, btn-primary, etc) to define borders.
I made the KBase core styling more specific for what buttons shouldn't have borders.

Altered styling to bring the btn-default border back.

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

Adds a simple check to not show an output widget if the output widget specified is: 'no-display'.
Tested this locally with Megahit, and seems to all work as expected without side effects.

Allow methods to specify no output widget

---

kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/config.json

It's expected that renaming a narrative should save the state of it as well. This is especially clear when a user creates a new narrative, edits a cell, hits the save button, and renames it (before, it wasn't saving, so those changes were lost). This fixes that.

renaming a narrative now triggers a save

---

bower.json
kbase-extension/kbase_templates/page.html
kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/kbaseNarrativePrestart.js
kbase-extension/static/kbase/js/narrativeLogin.js
kbase-extension/static/kbase/js/util/bootstrapDialog.js
kbase-extension/static/kbase/templates/update_dialog_body.html
kbase-extension/static/narrative_paths.js
scripts/start_docker_narrative.tmpl
src/biokbase/narrative/authhandlers.py
src/requirements.txt

There are a few environment variables that are expected to be present in each kernel process. 2 cases can cause those to get jumbled.
1. Manual restarting when multiple kernels are running can inherit variables from another running kernel.
2. Restarting the kernel when connecting to a new Docker container (without doing a page refresh) will start with a fresh session.
Since those values are known by the browser, but not by the kernel or (probably) by the Jupyter client, the main fix here is to set those needed variables every time the kernel gets restarted (triggers the 'kernel_ready.Kernel'). This just executes a tiny command to set things up at the right time.

Fix environment vars on restart

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js
kbase-extension/static/kbase/templates/beta_warning_body.html

Currently, when not in dev mode (e.g. on production servers), there's no toggle for the versions of SDK modules. This adds a toggle between release and beta. The concept is that SDK methods that are in development (the 'D' state in appdev, and CI) are intended to only be used by the developer. Beta methods are meant to be tested by colleagues and the community, then released ones should be seen by everyone.
This adds the SDK method toggle back to production servers, but only toggles between released and beta modules. It also has a modal warning when entering beta (though that can be suppressed for the session).

Change method panel to use beta and release mode in non-dev-mode.

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js

Was using the wrong time format api call to make the time string.
Also always adds the started time (for now). In some cases, the time it was finished doesn't get added to the status.
It should also show the actual time, not just the relative time, as a tooltip on mouseover. Working on that.

Fix job runtime being displayed improperly.

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotation.js

Nothing major - there's a data tables warning that'll pop up if it tries to populate a genome w/o gene or ids data. This won't add in the data if nothing exists.

fixed a datatables warning if no genes or cdses

---

docker/proxy_mgr.lua

The lua code was simply returning 401 for auth failure, although there had been code in the past to redirect to a "login page" to force the user to authenticate. The new code routes to the current kbase-ui login widget (#login) with the required routing parameter (nextrequest). In addition, the configurability of
the auth endpoint was removed -- simple string substitution is not really adequate for building the url. Well, it could be, but it is just a single case and one cannot really reconfigure the structure of the auth endpoint without knowing how and probably changing the function.
Also, fixed some bugs in the same function (use_proxy) which probably did not manifest themselves in a measurable way, because they were related to locks, which are released automatically after a period of …

provide redirect to auth page if there is an auth rejection in the lua startup code

---

kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterCheckboxInput.js
kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterInput.js

Hm. The last one was really just a partial fix - the real problem was any value that was 'falsy' wasn't necessarily being loaded into the parameter widget properly.
It should be up to each individual parameter input widget to properly deal with any value sent to it.

Actual solution to missing inputs problem on reload.

---

src/biokbase/narrative/tests/test_widgetmanager.py
src/biokbase/narrative/widgetmanager.py

* renamed `get_widget_inputs` -> `print_widget_inputs` because that's what it does.
* Made a few things private that won't likely need to be exposed easily
* Methods: `check_tag`, `load_all_widget_info`,
* Attributes: `version_tags`, `default_narrative_input_widget`, `default_narrative_output_widget`, `cell_id_prefix`
* Added docstrings to all methods so the Jupyter Pager will be useful (e.g. `biokbase.narrative.widgetmanager.WidgetManager?` does something helpful!)

Minor changes to widgetmanager API and tests.

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
kbase-extension/static/narrative_paths.js
nbextensions/methodCell/main.js
scripts/install_narrative.sh
src/biokbase/narrative/jobs/methodmanager.py

The `name` field in the metadata needs to be just the method name, not the id (which is module_name/method_name).
Also tweaked the install script to put the final output after installing the extension.
I also installed and updated the CDN on narrative-dev and pointed the narrative_paths.js file there for now.

Fixed bug in method code cell setup.

---

kbase-extension/static/kbase/js/widgets/narrative_core/ipythonCellMenu.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
nbextensions/methodCell/main.js
nbextensions/methodCell/runtime.js
nbextensions/methodCell/widgets/codeCellInputWidget.js
nbextensions/methodCell/widgets/fieldWidget.js
nbextensions/methodCell/widgets/input/singleCheckbox.js
src/biokbase/narrative/jobs/methodmanager.py

- added window-global level message bus to the runtime module 
- event to emit log status updates and listener in the method cell controller
- message status shown in toolbar and also not shown but state changes recorded in metadata
- use permanent cell id (cell.metadata.kbase.attributes.id) rather than jupyter cell_id 
- map untyped parameter with select attributes to the select control
- the input widget does not currently do enough useful with job state. E.g. when a job is running the cancel action should be available, when errors access to error message, when completed the cell should be locked but unlock able.
Couple of notes -
- the usage of module state is worrisome, both in our code and in jupyter. although it commonly holds, there is no guarantee that a module instance will be …

Route job status updates to method cells, various improvements

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
kbase-extension/static/kbase/templates/job_status_table.html
kbase-extension/static/kbase/templates/simple_bootstrap_button.html
nbextensions/methodCell/pythonInterop.js
src/biokbase/narrative/jobs/job.py

Got the Job _repr_javascript_ method working. Now, starting a new job should (properly) create and return a Job object. Viewing that Job object (e.g. just doing something like: 
```
my_job = apps.run_app('blahblah', foo='bar')
my_job
```
in a code cell) should put the job status widget in place, as it defaults to _repr_javascript_
`str(my_job)` works, too, and just coughs up the job id. For more, theres `job.info()` for a text view of the job with its inputs or `job.state()` for a more programmatic view of the state, or `job.parameters()` for the set of params used to start the job in the first place.
This hooks a listener onto the bus that now broadcasts from the Jobs Panel. Should behave a little better and just receive updates whenever the Jobs panel does.
Next up, make it behave as …

[WIP] Job _repr_ working

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/kbaseLoginFuncSite.js
kbase-extension/static/kbase/js/widgets/kbaseSessionSync.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
src/biokbase/narrative/__init__.py
src/biokbase/narrative/authhandlers.py
src/biokbase/narrative/narrativehandler.py
src/config.json

See tickets: 
* https://atlassian.kbase.us/browse/KBASE-4159
* https://atlassian.kbase.us/browse/KBASE-4154
* https://atlassian.kbase.us/browse/KBASE-2034
* https://atlassian.kbase.us/browse/NAR-849
* https://atlassian.kbase.us/browse/KBASE-4140
* https://atlassian.kbase.us/browse/NAR-850
These are all related to the same two issues:
1. The Narrative copy process is internally kinda complicated and kinda fragile. If anything breaks, you could wind up with a broken copy.
2. Copying a Narrative shouldn't also copy jobs.
Tasks to deal with them:

Addressing Narrative Copy problems

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

Duplicate custom name behavior for Genome using workspace metadata to include GenomeAnnotation.

GenomeAnnotation name display in data panel

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeOutputCell.js
nbextensions/methodCell/main.js
nbextensions/methodCell/widgets/jobLogViewer.js
nbextensions/methodCell/widgets/methodCellWidget.js
nbextensions/methodCell/widgets/methodExecWidget.js
nbextensions/methodCell/widgets/methodOutputWidget.js
nbextensions/methodCell/widgets/methodParamsWidget.js
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobmanager.py

The primary change is to insert the output cell after successful app execution. This is handled by the app cell widget (currently named methodCellWidget) upon the first time it is notified that the job has reached a completed state. This may be while after it has started running and has received the job state message, or after it has re-loaded and receives the job state message.
Another more radical change is to keep references to outputs within the app cell. This is exposed in a new output widget within the app cell. 
So the app cell can show a "history" of executions. There is provided for proof of concept -- so it is not fully formed. It is already useful, though, because it allows handling outputs (deleting) directly from the app cell rather than hunting them down in the narrative. 
I …

app cell inserts output cell and other changes

---

src/biokbase/narrative/jobs/app_util.py
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/tests/test_appmanager.py
src/biokbase/narrative/jobs/viewer_job.py

This introduces a few things.  
* `AppManager.run_local_app` - this is for running synchronous, fast-running apps. It'll still register a log call for the app run, but it'll return the Widget with the result immediately. It's mainly meant for viewers, but can be adapted for other locally running code eventually.
* Fixed issues with positional parameters from method specs.
* Fixed issue with mapping fetched parameters that are stored in job info, back onto the output widgets.
* Fixed issues with parameter mapping and transforming (making explicit ws refs from input names, etc)
* Fixed issues with error handling on run_app - shouldn't throw a stacktrace, just print an error message.
* Removed the ViewerJob idiom and branching... because that was silly. The viewerjob file will get removed …

Better app startup handling

---

kbase-extension/static/kbase/js/util/bootstrapDialog.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
kbase-extension/static/kbase/templates/job_panel/job_error.html
kbase-extension/static/kbase/templates/job_panel/job_info.html
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobmanager.py

* Only one function now - delete_job (removed 'remove_job'). (the request-job-removal Bus message still works)
* If a job can't be deleted (currently, we can't cancel running jobs), it produces a popup.
* More complete error handling for canceling jobs.

Update job deletion management

---

Dockerfile
RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCellToolbarMenu.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeOutputCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
src/biokbase/narrative/contents/updater.py
src/config.json

* The Narrative updater properly turns old Markdown'd viewer cells into code cells that have been pre-executed
* Added some installation lines to the Dockerfile to update requests-security (get rid of SSL errors showing up all over the place - thanks @MrCreosote !)

Viewer cell and updater fixes

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSideImportTab.js
src/config.json

Importer should show SDK import methods again.
Git decided to overwrite that with an old version in a merge that happened yesterday. This reverts the reversion.

Fixed strange reversion in the importer panel.

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterTextInput.js
nbextensions/outputCell/main.js
src/biokbase/narrative/app_util.py
src/config.json

Co-opting this for fixing Job running things that @MrCreosote exposed

Fixed typo in outputCell extension

---

RELEASE_NOTES.md
nbextensions/appCell/widgets/appCellWidget.js
src/biokbase/narrative/jobs/appmanager.py
src/config.json

The App param validation is maybe a little too strict in how it adheres to the app specs. This has some updates to loosen things up a bit.

kernel-side app validation

---

RELEASE_NOTES.md
kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/js/common/pythonInterop.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeOutputCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
nbextensions/appCell/widgets/appOutputWidget.js
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/tests/test_appmanager.py
src/biokbase/narrative/tests/test_widgetmanager.py
src/biokbase/narrative/widgetmanager.py
src/config.json

Using keyword args for run_app (and others) doesn't work. Parameter names are defined by method spec, and can (and should!) be arbitrary strings. The problem here, is that there are other keyword args in those methods that should be retained, since it's useful to provide defaults values, or just make them optional without requiring a user to put in "None".
The solution is to change that list of keyword args for param ids into a single, positional dictionary. So we turn an app call like this:
```Python
AppManager().run_app(
"MyModule/my_app",
tag="dev",
version="xyz",
cell_id="foo",
param1="a",
param2="b",
param3="c"
)
```
into this:
```Python
AppManager().run_app(
"MyModule/my_app",
{
"param1": "a",
"param2": "b",
"param3": "c"
},
tag="dev",
version="xyz",
cell_id="foo",
)
```
or, more …

Update run_app and show_output_widget signatures

---

kbase-extension/static/custom/custom.css
kbase-extension/static/kbase/css/appCell.css
kbase-extension/static/kbase/js/common/events.js
kbase-extension/static/kbase/js/common/monoBus.js
kbase-extension/static/kbase/js/common/props.js
kbase-extension/static/kbase/js/common/ui.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/singleSubdata.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
nbextensions/appCell/widgets/appCellWidget.js
nbextensions/appCell/widgets/appExecWidget.js
nbextensions/appCell/widgets/appOutputWidget.js
nbextensions/appCell/widgets/appParamsViewWidget.js
nbextensions/appCell/widgets/jobLogViewer.js
src/biokbase/narrative/jobs/jobmanager.py
test2/specs/active/props-Spec.js
test2/test-main.js

- job cancellation invokes request-job-cancellation (which does nothing yet)
- back end job status events split into job_status and job_status_all
- this allows the "detection of deleted job" in the job panel to work since the logic requires that all known jobs be included in the message (which is what job_status_all is for)
- this is a [wip] but fixes a problem with new jobs issuing a job-deleted message
- fixes to properly remove event handlers

Job related changes and other fixes

---

Makefile
package.json
test/unit/karma.conf.js
test/unit/run_tests.py
test/unit/test-main.js
test2/test-main.js
test2/travis.conf.js

- adds cdn modules into test
- works against ci CDN - this should be done better, by installing a local CDN and firing it it up during testing
- adds new tests (under tests2) for some modules used by the app cell and friends
- updates makefile so tests should run on travis

Fixes some front end unit test quirks

---

kbase-extension/static/kbase/js/common/pythonInterop.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeOutputCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
nbextensions/appCell/widgets/appCellWidget.js
nbextensions/dataCell/main.js
nbextensions/install.sh
nbextensions/outputCell/main.js
nbextensions/viewCell/main.js
src/biokbase/narrative/app_util.py
src/biokbase/narrative/widgetmanager.py
test2/specs/active/pythonInterop-Spec.js

the method of inserting python code for data objects conflicted with app
cell outputs. The code was unified, and data object display moved into
it's own cell extension (nbextensions/dataCell). This simplifies the
implementation of data cells, while still retaining the common object
vis widget invoker.
Along the way some python intro improvements.
This seems to have been a regression in a recent commit.

fix data object display in narrative

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/common/parameterSpec.js
kbase-extension/static/kbase/js/common/ui.js
kbase-extension/static/kbase/js/widgets/appWidgets/fieldWidget.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/singleCheckbox.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/singleObjectInput.js
nbextensions/appCell/widgets/appParamsWidget.js
src/config.json

- blocker was an alert and refusal to insert app cell when a parameter which is specified to contain an output object name is also specified as "parameter" type. It should be "output". This is an app spec error, but we are working around this by allowing  the output object name setting to override the parameter "ui_class" (input, output, parameter).
- improve error message when a checkbox is specified without providing the values associated with checked or unchecked state.

Fixes to problems exposed by testing 

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeOutputCell.js

Lazy-rendering of output cells, i.e. do not really render until they scroll into view.
Tasks:

Lazy rendering

---

kbase-extension/static/kbase/css/bootstrapHelper.css
kbase-extension/static/kbase/js/common/error.js
kbase-extension/static/kbase/js/common/fsm.js
kbase-extension/static/kbase/js/common/ui.js
nbextensions/appCell/main.js
nbextensions/appCell/widgets/appCellWidget-fsm.js
nbextensions/appCell/widgets/appCellWidget.js

In https://atlassian.kbase.us/browse/NAR-864, two different conditions were reported to cause an error popup upon loading a narrative.
These were due to, 
- in one case an incorrectly specified app cell. This was due to an app cell inserted some time during development of the app cell. The specific cause was a null tag.
- in the second case an app cell containing a dev app which had been updated, and the parameters changed. This triggered an unexpected condition (a parameter lookup returned undefined).
- another case discovered during testing was an app cell from several weeks ago which had an incomplete app spec.
In all cases, the implementation of the fatal-error condition with detailed error messaging will be more helpful to a user who encounters this. In the case of the invalid …

Fixes NAR-864 - handle severe app errors or version mismatch

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionAnalysis.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePanel.js

We had a pretty detailed discussion about removing the Jobs Panel (@eapearson, @scanon , @psdehal ) for a few reasons.
1. That information is easily available in each App Cell.
2. As that panel grows, and gets clogged with completed jobs, it's very difficult to navigate.
3. Even putting toggles to only show Jobs in a particular running state wouldn't solve most UX problems.
4. We'll be migrating all of that Job viewer functionality outside of the Narrative eventually.
5. There's no real way to actually manage running jobs yet, or any system for dealing with Job management (other than starting and canceling).
6. We want to remove the ability for a user to delete the Job record. There's enough rich information there that's useful for other things that probably shouldn't be deleted.
7. It …

Hide the Jobs Panel

---

docker/docker.lua
docker/notelauncher.lua

Fixes to support newer versions of the Docker API which deprecates some options for start_container
This seems to do the right thing, but would probably benefit from some more review.  Tested with Docker 1.12 on next.

Docker API Fixes

---

kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/js/common/jupyter.js
kbase-extension/static/kbase/js/common/pythonInterop.js
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/appWidgets/customWidgetWrapper.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/customSubdata.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/singleBooleanInput.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/singleCheckbox.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/singleFileInput.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/singleFloatInput.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/singleIntInput.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/singleNewObjectInput.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/singleTextInput.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/singleTextareaInput.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/singleToggleButton.js
kbase-extension/static/kbase/js/widgets/function_input/kbaseEditMedia.js
kbase-extension/static/kbase/js/widgets/function_input/kbaseEditModel.js
kbase-extension/static/kbase/js/widgets/function_input/kbaseNarrativeMethodInput.js
kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterTextInput.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
nbextensions/appCell/widgets/appCellWidget.js
nbextensions/dataCell/widgets/dataCell.js
nbextensions/viewCell/widgets/viewCellWidget.js
nbextensions/widgetCell/main.js
nbextensions/widgetCell/widgets/widgetCellWidget.js
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/widgetmanager.py
test2/specs/active/props-Spec.js

The custom input widget is now mostly functional. The remaining item is to synchronize the cell parameters with the media editor (mostly relevant at cell startup time.) 
However, we may not support the custom input widget going forward, so this may not see the light of day. There are two instances of custom widget, the media editor and fba model editor, and they are in the process of being updated to use server side apps for the object updating. This change would allow the editor widget to function as a parameter widget rather than an entire input area widget.
On a related note, custom subdata widgets had gone wonky with an ill-advised attempt at a 
reset method, and this is fixed in this PR. 
Curing custom widget work, the keyboard manager was causing problems. Efforts to disable the …

improvements to custom widget and custom subdata widgets.

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
kbase-extension/static/kbase/templates/job_panel/job_init_error.html
src/biokbase/narrative/app_util.py
src/biokbase/narrative/exception_util.py
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/jobmanager.py
src/config.json

One of the big issues from last week was that when backend services (UJS/NJS/etc.) go down, it has unpredictable results in the Narrative. This goes some way to trying to fix that.
When the Kernel looks up Job info, and an Exception is thrown, that can be one of two types - either a ServerError (thrown by the Service itself with faulty data or permissions) or a form of network error (represented as requests.exceptions.HTTPError). The change here consolidates those into one exception and returns the error code, message, source of the error where available (either network, UJS, NJS, or somewhere in the kernel), and communicates those to the front end. Effectively, it adds two new fields to the error message comms:
`code` - a numerical code, either a 3-digit HTTP code, a 5-digit negative …

Adds some more detailed error trapping when backend services are unreachable

---

nbextensions/dataCell/widgets/dataCell.js

An instance of case error in module names being ok on Mac with case
insensitive filesystem, but not deployed on Linux without.

Fix case error in module name

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
kbase-extension/static/kbase/templates/job_panel/job_init_error.html
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobmanager.py

[WIP] Job cancellation and status updates

---

RELEASE_NOTES.md
kbase-extension/static/kbase/css/appCell.css
kbase-extension/static/kbase/js/common/error.js
nbextensions/appCell/widgets/appCellWidget.js
src/config.json

Whenever an app gets updated on dev/beta, it gets a new git commit hash - that's a tag for the 'version'. The App cell tests for a new version every time it gets the page refreshed.
The old one will still run - it keeps the version information. But the App Cell is tied to whatever version it was when it was inserted into the page. The best thing to do is create a new one if you want to run the updated version.
(you can also manually delete the version parameter from the generated code, if you're feeling brave).

Added warning for out of date Apps

---

RELEASE_NOTES.md
kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/js/kbaseNarrative.js
src/config.json

Now all commands are stripped by the narrative module at startup. Supposedly. Unless the keyboard manager wants to resurrect itself, but I haven't found a case where it does that yet.

Another try at removing command-mode single-key commands

---

nbextensions/appCell/widgets/appCellWidget.js

The narrative currently saves whenever the app cell initializes. This is real bad when you have, say 10 or more apps, and you just refresh the page.

Prevent the narrative from saving every time the page loads.

---

kbase-extension/kbase_templates/page.html
kbase-extension/static/kbase/css/appCell.css
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
nbextensions/appCell/widgets/appCellResults.js
nbextensions/appCell/widgets/appCellWidget.js

Inching toward representing the mockups better...
* Hid the "Output" windowblind area.
* Popped the Results tab out into a separate widget - appCellResults in the nbextension area.
* When results happen, if the key "report_name" is present in them, then that's a report. This then adds the report widget.
* Adds a little string of which results are being viewed.
* Fixed @scanon 's issue of cells that can't be deleted.
* Made a few CSS adjustments - the padding on the widget view areas is gone when collapsed, added a light gray background.

Adjustments to App Cell UI

---

kbase-extension/static/custom/custom.css
kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/common/appUtils.js
kbase-extension/static/kbase/js/common/ui.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCellToolbarMenu.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
nbextensions/appCell/main.js
nbextensions/appCell/widgets/appCellWidget-fsm.js
nbextensions/appCell/widgets/appCellWidget.js
nbextensions/dataCell/main.js
nbextensions/outputCell/main.js
nbextensions/viewCell/main.js
src/biokbase/narrative/exception_util.py
src/biokbase/narrative/jobs/jobmanager.py

The prompt area is hidden with a single simple css directive.
This required moving the icon into the toolbar. This was not too strenuous, requiring an additional area in the toolbar on the left. Since the toolbar is rendered to the beat of Jupyter, it requires a different method of rendering the icon. Specifically, it must request it from the host cell via our cell extension method "getIcon". This replaces "renderIcon" which was called at cell creation time, not toolbar rendering time. It is possible that there will be flickering at times, since the cell toolbar may be rendered at arbitrary times. E.g. it renders before the cell is even ready, so there is an initial state of no icon, it renders after the cell extensions are loaded, and it can also render when the cell metadata is updated …

Hide prompt area, move icon to toolbar

---

kbase-extension/static/custom/custom.css
kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/js/common/utils.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCellToolbarMenu.js
nbextensions/appCell/main.js
nbextensions/dataCell/main.js
nbextensions/outputCell/main.js

To simplify the cell toolbar, buttons which may be less-used are moved from the toolbar into a dropdown menu on the toolbar. Buttons moved are the delete, collapse (min/max), and code view. The settings button is not in the new design and was removed.
Minor changes from the mockup -- the icon is an ellipsis, not gear, since gear is more commonly used for options and ellipsis for additional items.
Also help not included on menu, since we don't have a help system. 
A note here that the Jupyter toolbar is prone to rendering interruptions. The core code re-renders the toolbar when the cell.metadata property is set (not just updated, it has to be set through direct assignment.) The renderer removes all toolbar nodes, and then calls all toolbar extensions to render themselves. Using a dynamic, …

Cell toolbar - merge individual buttons into dropdown

---

kbase-extension/static/kbase/js/widgets/narrative_core/narrativeViewers.js

@briehl @eapearson - What do you think about this?
Right now, we capture all the object info and pass it along the long chain to actually render a widget, then we throw it away and only keep parameters from the method spec at the very last step.  So in most cases, we lose version information, and the viewers only show the latest version.  So why don't we just always pass this full object info to all of our viewer widgets (in addition to the other parameters of course, so nothing breaks)?
This would let me make sure the Genome and Assembly viewers respect versions.  And actually, In most cases, this object info is all the viewers need, so we wouldn't even need some complicated parameter mapping for most viewers.
A possible downside is that if these widgets are created in other widgets, or …

Provide full object info as input for viewer widgets

---

kbase-extension/static/kbase/js/tour.js
nbextensions/appCell/widgets/tabs/resultsTab.js

Still no list of created data objects, but the list of suggested next steps is back.
Unfortunately, there are no apps that use that feature to point to SDK methods - they're all still using the older method and app ids.

Tour cleanup, tweaked results to get closer to mockup, add suggestions

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseReadsViewer.js

only doing fields users can specify per Paramvir's instructions.
Now works for both single and paired end reads.

Read viewers pass number 2.

---

src/biokbase/narrative/contents/updater.py

Some wording changes as per https://atlassian.kbase.us/browse/KBASE-4399 
I wanted to leave out the internal names from the list of replacement apps (see suggestion #5 in JIRA ticket), but I don't know Python so I wasn't sure what to change or how to test my change. The relevant code is:
format_sug = "The following replacement apps might help and are available in the Apps menu:<br><ol>"
for idx, s_list in enumerate(suggestions):
format_sug += '<li>{}<ul>'.format(s_list['orig_step'])
format_sug += ''.join(['<li>{}</li>'.format(s) for s in s_list['sug']]) + '</ul></li>'
format_sug += '</ol>'

Changes to wording of "Obsolete App" message

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js

I still don't have pre-auth shock links working properly (they'll work once, but fail to re-generate a new link on every click). So until that's operational, here's a version using the import/export service to construct the URLs.
The token isn't visible in the html page, but will briefly be available in the location bar.
But other than the minor security concern, this should be fully functional.

updated download links in report

---

nbextensions/editorCell/widgets/editObjectSelector.js
nbextensions/editorCell/widgets/editorCellWidget.js

This was a remnant to work around the empty-set bug (add one item when creating a new set.) Not necessary now.

don't add fake reads object when creating new

---

kbase-extension/static/kbase/js/kbaseNarrative.js
src/config.json

To patch the busted appdev uploaders.
@rsutormin @scanon 
The `narrative_method_store_types` config piece can be added to any environment block to point just the types to a different service. If it's not present, it'll use the `narrative_method_store` variable instead (see previous PR #807 ).

Added appdev config for narrative_method_store_types

---

nbextensions/editorCell/main.js
nbextensions/editorCell/widgets/editObjectSelector.js
nbextensions/editorCell/widgets/editorCellWidget.js

added "Currently Editing" section to show object info, collapsible
pass around object info rather than reference to avoid extra info queries
The object selection and current set info are both collapsible. They can be tinkered with now to see how it would work if they were automatically controlled. E.g. if an editor cell is loaded with a prior selection, the only open panel should be the Editor, after selecting a reads set to edit, the selection could collapse. Of course, collapse could also be "hide" with buttons to control hide/show.

persist the reads set selection, restore upon reload

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
src/config.json

Just a first pass demonstration. Should be cleaned up otherwise.
Data palette stuff has (from palette) labeled by it, with a briefcase icon (couldn't find a palette in our fonts... maybe add one?).

Added view directives for things from data palettes

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseReadsSetView.js

Switched the reads browser to data tables and turned off any calls to the WS, instead relying on metadata for each item returned from the SetAPI.  Also generally improved formatting to align with the assembly and genome viewers.

Updates to reads set viewer

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/util/display.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeExampleDataTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePublicTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
src/config.json

Work in progress for rewiring Workspace calls from the data list to go to the NarrativeService
(see https://atlassian.kbase.us/browse/TASK-76)
Main Data Panel
My Data / Shared With Me (same widget)
Public Panel
Example Panel

Rewire data slideout

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

This'll cause the data panel to fail to render data objects.

Fix error when metadata is none

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSideImportTab.js
kbase-extension/static/kbase/templates/job_status/new_objects.html
src/biokbase/narrative/jobs/job.py

- Hides the code area on first appearance.
- Hides the "Report" and "New Objects" tabs until there's something to put there.
- Report only shows up if it can guess that there's a report object (looks for 'report_ref' in the results)
- "New Objects" will show up if there's a report (since that info is in there).
- "New Objects" also shows up if it looks like there's a workspace reference in the results. Scans through that object looking for any string that matches "XXX/YYY/ZZZ" where those can be anything (and the last part is optional). That might still be a bit brittle, since it just auto searches the workspace for that info.

Fixes to widget that shows up with importer jobs

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
src/biokbase/narrative/jobs/appmanager.py

The viewer cell broke after the introduction of the app_type feature to the app spec. The feature was introduced to the narrative and nms before all modules were updated with the app_type. Since the app_type defaults to 'app', most viewers were broken. This will not be resolved until all modules are updated and re-registered, so we have to handle the app type without complete dependency upon the app_type.
The fix is to revert to inspecting the app spec to determine the type of app it describes. If the behavior includes app routing information, it is either an app or an editor, in which case the app_type of 'editor' signifies it is an editor, otherwise 'app'. With no app routing, it must be a 'view' (app_type 'viewer') cell.

Fix viewer cell regression

---

kbase-extension/static/kbase/js/api/kbase-client-api.js
kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterFileInput.js

usage of lastModifiedDate was incompatible with Safari and non-standard.
tested on Mac Safari, FF, Chrome
could use additional testing on Windows
tested with a reads (single) file
1. from a narrative with a reads object
2. download FASTQ
3. attempt to import the fastq file
4. import it
5. repeat 3-4 for: same file, same file copied to another name, same file touched to give different timestamp, invalid fastq file (e.g. create a simple text file.)

Staging "hotfix" to fix data panel / import tab, file upload breaking on Safari

---

kbase-extension/static/kbase/js/util/timeFormat.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/singleObjectInput.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js

Now, when clicking the 'New Narrative' button in the Narratives panel, it does this flow:
1. Disable the button.
2. Call the NarrativeService create narrative function.
3. Build a link to the new narrative and put it in place under the button. This is the biggest shift - just popping open a window via JavaScript will get stopped by most browsers' pop-up blockers. And I think we still want it to come up in a new tab/window. So that's the feel for now.
4. Re-enable the New Narrative button when the link is clicked, and dismiss the link, while we're at it.
5. On error - show the error in a slide down alert (in the same spot) and continue to disable the create button while the error is being shown.
This also does a little bit of cleanup.

Rerouted New Narrative button, changed UX for it.

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/singleObjectRefInput.js
nbextensions/editorCell/widgets/editorCellWidget.js

- switch from workspace query to data panel for the object selector input widget
- this allows the editor to show reads objects from the data palette.
- disable object selector reset when object disappears from narrative workspace. an unresolved race condition exists between the control and the data panel ... the control may be rendered before the data panel is populated, and the data panel query returns no available objects. The logic of the control was that if it points to an object which does not exist, it will reset itself. This has been disabled. The effect for the user is that the control is first empty for a moment, and then the value appears. This is because there are no items for the dropdown initially.
This will become moot when this control is updated to support richer vis and …

Reads set editor datapanel

---

kbase-extension/static/kbase/js/common/monoBus.js
kbase-extension/static/kbase/js/common/sdk.js
kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidgetCompact.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/multiStructInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/singleIntInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/structInput.js
nbextensions/appCell2/appCell.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/appParamsWidget.js

Supports optional grouped parameters which by default are disabled with a null value and may be enabled, in which case  they are populated with default values.
Still working on improving lists of grouped parameters.
Note that the enable/disable control is still the checkbox, and that when disabled the grouped params are not displayed -- they don't exist. This is consistent at least with the mechanism and model that what you see is what is in the data model holding the params.
The value of a disabled optional grouped parameter (mouthful!) is null (None in the generated code) rather than being missing as we discussed. This is really just easier now given the way the parameters work in the app cell. I think we should treat missing parameter and null value as the same.
This required changes …

Optional grouped params pass 1

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js

This rewires kbaseReportView to use a hidden iframe to download files (same as the download panel) instead of setting window.location.href. Should resolve the warnings about navigating away from the page, and seems happy across Safari, Chrome, Firefox.

used hidden iframe for download

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeOutputCell.js

Legacy versions of output widgets aren't working in production right now. This should fix that and properly add the titles back.

Hotfix output cell

---

src/biokbase/narrative/contents/updater.py

The updater script was doing a couple things wrong - one major, one minor.
The minor error is what I suspect most folks were seeing - existing SDK apps weren't properly being updated with their method spec. Quickie one-line-change. (line 209) 😄 
The major error might not get seen very often - it happened when trying to update an old Narrative, from pre-Jupyter 4-ish (so, nbformat v3). These would be Narratives that had last been saved prior to the previous update last February, so really old. Anyway, these would break when getting updated due to some key changes.
The "right" way to do this going forward would be to first run the Narrative typed object through nbformat (to convert to the newest version) before updating any Narrative contents. Currently, the Jupyter code and KBase code are …

Hotfix legacy apps

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/uploadTour.js
src/biokbase/narrative/widgetmanager.py

When instantiating a widget, by default, the widgetmanager will check to see if that widget is referenced in any of the method specs. This is done to guess that it exists and is spelled correctly, etc. It's a little hand-wavey, and put there in lieu of having an actual widget registry solution.
But it's causing problems. This PR changes the default behavior to NOT check for widget existence, and just let the output cell catch the failure and display an error instead of the code cell stacktrace.
Also has a few little additions to the tour for the staging area (still incomplete... but that panel's hidden anyway).

Relaxed failures on widgetmanager, added to staging tour

---

bower.json
kbase-extension/static/kbase/js/widgets/appWidgets2/input/autocompleteInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/taxonomyRefInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/taxonomyRefWithParentInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/paramResolver.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/taxonomyRefView.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
kbase-extension/static/narrative_paths.js

Changes to autocomplete input to make it work
But then abandoned that in order to use select2, since that is the current use case
That control is taxonomyRefInput
There still is a use-case for autocomplete for scientific name, so it is still in the code-base, but there isn't anything to use it now
More work is needed in the taxonomy_service module, e.g. the field_type should not be autocomplete, but taxonomyRef (at least that is my suggestion).
This should be considered unstable, experimental work, in that it currently works with the state of the taxonomy_service, which defines the only apps using it, but both taxonomy_service and the control implementation will need to change.

Taxonomy ref control

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/checkboxInput.js

The stop method was not returning a promise, so it broke when removing a checkbox control from a sequence.

Fix checkboxes in sequence not deleting

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

App specs should now have a field called "info.app_type", as maintained in the NMS. Those that don't should try to infer what the app type is based on the presence of a few keys.
**Long version** = there are 3 possible app types - editor, viewer, and app. "Viewers" don't have their execution behavior defined in the spec (that's all managed by their widget) and are easy to infer. "Editors" are expected to be explicitly called out by the app_type field, since the cell change is mainly one of usability and how the code is executed. "Apps" are, well, all the rest of the apps.
Currently, in production, there are no Editors (e.g. the Reads Set Editor in CI), so defaulting to App won't break anything. This just means that before registering Editor apps in prod/appdev, we need to update NMS and …

Return a default type of "app" for missing app_type fields.

---

RELEASE_NOTES.md
kbase-extension/static/kbase/config/feature-config.json
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeOutputCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSideImportTab.js
src/biokbase/narrative/__init__.py
src/biokbase/narrative/widgetmanager.py
src/config.json

**DO NOT MERGE!**
Some tweaks, mainly to support demos for the Contractor's meeting. In no particular order.

[WIP] Some UI fixes and tweaks

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionMatrix.js

Fixed misspelling

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/editorCell/widgets/editors/readsSet/editor.js
nbextensions/viewCell/widgets/viewCellWidget.js
src/biokbase/narrative/__init__.py
src/config.json

This fixes a couple problems I found.
1. Using the copy button in read only narratives (e.g. public ones) worked, but created a bad URL in it's "Open the new narrative" button.
2. Disabled the execution controls for apps, editors, and view cells. Clicking on a data object should still create a (temporary) viewer, but a user can no longer run or modify any cell using the main action button.
@eapearson - I just added 'display:none' to the main cell areas when they get created. There's still plenty of internal logic that expects those buttons to be there for binding things, but just hiding their containers from the user seems to be sufficient.
see also https://kbase-jira.atlassian.net/browse/TASK-312

View-only fixes

---

kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseCummerbundPlot.js

If the cummerbund service isn't working properly, it can generate an invalid object which contains an empty cummerbundplotSet array key.
This modification will report that error which should never occur.

reports impossible error

---

src/biokbase/narrative/contents/narrativeio.py

These cell types were not being added to the notebook metadata stats upon narrative save, this fix simply replicates the code to do this using the same "method." property prefix. This treats all app cell types as the same, which reflects the way they are treated in the narrative

Add metadata support for editor and view cells

---

kbase-extension/static/kbase/config/data_source_config.json
scripts/install_narrative.sh
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test.cfg
src/biokbase/narrative/tests/test_appmanager.py
src/biokbase/narrative/tests/test_jobmanager.py
src/biokbase/narrative/tests/test_logging.py

The Public and Example tabs weren't working.
I'm not exactly sure what's supposed to be there, so I just copied the sources from prod. This changes lets Public Phytozome Genomes and Media work (the rest don't work for some reason... not sure how they're supposed to be configured, or if there's a missing Search service in appdev). Also, in the Example workspace (KBaseExampleData), there's only a few data sets.
So that should probably be either reconfigured to point to valid workspaces, or have those workspaces filled up with appropriate testing data.
Either way, this is better than an error message.

Added an appdev stanza to data_source_config

---

kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseFigureObjectHeatmap.js
kbase-extension/static/kbase/js/widgets/kbaseVisWidget.js

The figure object heat map could collapse down to nonexistent, since no minimum height was specified.
Now specifies an arbitrary minimum height. All better now.
Also cleaned up some old debugging crap that I'd kept neglecting to.

Figure object heatmap fix

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js

This is the placeholder text that appears in the app name text search box before you enter anything.
I hope this is the right place and right branch to change this.

"Search methods" -> "Search apps"

---

kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseRNASeqAnalysisNew.js

Should work, but I couldn't test due to workspace permission issues.
Just looks at a sample id to see if it has a / in it. If so, now assumes it's a ref. If not, assumes it was a name, as before.

sample_ids can now be names or refs

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

"Copy a narrative" -> "Copy this Narrative"

Improved wording of copy message

---

kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseRNASeqAnalysisNew.js
kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseRNASeqPieNew.js

more fiddling around with widgets to deal with the swap from name -> id.
kbaseRNASeqPieNew (which still doesn't have a pie chart) now assumes that the list of ids to select is actual a list of ids (instead of names, as previously).
kbaseRNASeqAnalysisNew now allows the sample_ids to contain IDs or names, and tries to guess.

Rna seq sampleset patch

---

kbase-extension/static/kbase/js/common/sdk.js

Don't propagate advanced flag to subcontrols because doing so makes then un-renderable, or rather, the class added to advanced subcontrols won't be removed.
Fixes https://kbase-jira.atlassian.net/browse/TASK-439

Fix advanced sub controls rendering as blank spaces

---

kbase-extension/static/kbase/js/common/sdk.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/select2ObjectInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/select2ObjectView.js
nbextensions/appCell2/widgets/appParamsViewWidget.js
nbextensions/appCell2/widgets/appParamsWidget.js
nbextensions/viewCell/widgets/appParamsViewWidget.js
nbextensions/viewCell/widgets/appParamsWidget.js

The root of the problem is that it calculates the wrong dimensions when hidden. Solution is to emit a jQuery event when advanced params are shown, and have the select2 listen for it and resize itself.
Fixes https://kbase-jira.atlassian.net/browse/TASK-440

Fix select2 control now rendering correctly as advanced parameter when un-hidden

---

nbextensions/appCell2/widgets/appCellWidget.js

When the narrative window is made narrow, the toolbar area's "tab buttons" would break. This essentially right aligns the layout container and makes the button bar inline-block, thus acting as an unbreakable unit.

Prevent app cell toolbar button area breaking

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterDropdownInput.js
kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterFileInput.js
kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterTextInput.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSideImportTab.js
src/biokbase/narrative/__init__.py
src/config.json

The parameter fields for the import tab were being set up in an unsupported way, and the minifier really exposed that.
There were other problems exposed by digging into this - a dropdown parameter was always treated as valid, even if it wasn't (e.g. the technology type dropdown for reads was allowed to be empty, even though it was marked required, which would cause the import to fail.)
There's still some interesting UX stuff going on if a text field is optional (it can be pre-filled, and still have a check mark when emptied), but those might be fixable with an improved docstring.

Fixed broken minified import tab. Some related fixes, too.

---

kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseRNASeqPieNew.js

The HISAT selector output *was* fixed, and even was fixed in production.
The problem was that it was looking at a table of mapping information provided by the given object, which contained a map from ID -> name. However, Shinjae informed me this morning that that mapping information is unreliable and should not be used.
So the rna_seq_alignments_mapping object which helpfully contained alignment ID -> alignment object mappings was instead sometimes populated with sample name -> alignment object mappings. And even those are not valid and not to be trusted.
Instead of using the provided mapping information, which is incorrect and should not be used. The widget should now map from sample -> alignment, get_object_info on all alignment objects, pull out the names of those objects, and use that …

Hisat widget mod

---

kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseRNASeqAnalysisNew.js

because the decorators around the datatables table to do searching and pagination weren't included. But now they are.

not all sample ids were displaying

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseTaxonomyBrowser.js

The service is updated to vend out data to populate the overview table, so now the widget actually uses it to populate said table.

populates the overview table

---

narrbase-image/Dockerfile

Installing IPywidgets brings in the latest setuptools (or some recent version) which is incompatible with other things, and effectively breaks our Python install.
This sticks to the last good version of setuptools (33.1.1) and should build.
See also this issue:
pypa/setuptools#942

Fix narrbase image build

---

kbase-extension/static/kbase/js/common/monoBus.js
kbase-extension/static/kbase/js/common/ui.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/customInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/customInputs/PetInput.js
kbase-extension/static/kbase/js/widgets/custom/advancedViewerOutputWrapper.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
nbextensions/advancedViewCell/main.js
nbextensions/advancedViewCell/widgets/advancedViewCellWidget.js

fix was that a shared comm bus was duplicating data within multiple advanced view cells in same narrative
update is to change the input area label to Configure (align with app cell) and to have the collapse/expand state stored in cell metadata and restored upon narrative reload. Esp. supports the "Viewed" state for a view cell -- when the view has been generated and the input/configure has been auto-collapsed.

Fix and update for advanced view cell

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePublicTab.js

Leaving the "." character in search was returning some unexpected results. E.g. searching for "e. coli" would return nothing, but "e coli" would. This just removes periods before sending the search string to the service
Tagging @qzzhang who requested the change.

strip "." out of search query strings in public data search

---

docker/proxy_mgr.lua

Now it goes to load-narrative.html
Also, make sure that when there's an UNAUTHORIZED error, we return it as such and don't try to let users through anonymously.

Update proxy_mgr for new interstitial loading page.

---

kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseRNASeqAnalysisNew.js
kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseRNASeqPieNew.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js

I don't think a ticket was created for this, or if it was I couldn't find it.
Updated the rna-seq widgets on http://localhost:8888/narrative/ws.19113.obj.1 to use get_objects2 and get_object_info3 to load their data, and deal with /'s in the object refs. Also cleaned up some commented cruft in them.
PLEASE NOTE - *only* kbaseRNASeqPieNew.js and kbaseRNASeqAnalysisNew.js have been updated to use the new workspace methods, and I'm sure other rna-seq widget should be updated to use the newer methods, but without a narrative using those widgets to test against, I don't want to make the change since it's not quite a drop in replacement. It's almost a drop in, but I still want to actually look at something and test it before deploy.

Updates widget ws loading

---

bower.json
kbase-extension/static/kbase/js/widgets/dynamicTable.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseBinnedContigs.js
kbase-extension/static/narrative_paths.js

This is pretty heavy on the alpha-side of things, but this adds download support from the newer table widget that @msneddon and I put together. It's demonstrated with the binned contigs viewer. The buttons (pending redesign...) in the lower right of the table will download either the current data view (left button) or all of the data in that table (right button).
A problem is that it requires holding all data on the browser right now before funneling it to the file system. Doing it this way supports up to hundreds of MB of data (several GB for Chrome), so it *should* be fine, but could also be a problem for certain files. But this is an alpha. We can do things to alleviate problems, like just preventing download of all data for sets of certain sizes.

Add download support to dynamic table

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotationAssembly.js

Minor fix that didn't get pushed in the last PR. Oops!
@msneddon - this means that the AssemblyAPI needs to be promoted to release in each environment so the `search_contigs` function is available.

Removed dependency on 'dev' version of AssemblyAPI for assembly viewer

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionFeatureClusters.js

This alters the 3 View methods in the "Explore Cluster" drop down to pop up in tabs.
"Build Feature Set" is a different type of method that needs to be run and produce output, so it's just hidden for now until there's a good method to invoke it.

clusters in tabs, not bounching through methods [TASK-430]

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSideImportTab.js

This patch is a hack that wallpapers over an actual issue, so it's submitted for informational purposes. It can be integrated, but it's may just be hiding another problem. Bill and Erik need to look into this more thoroughly, since it's getting into the guts which I am less familiar with.
There's a lot going on here, so please bear with me.
Right now, in CI, if you were to upload a gen bank file, the cell will add into the narrative and then immediately expand the cell while the job is still in the queue. If this happens, it'll fall into this issue where it claims that the job is still queued and not update the logs.
Conversely, in my local narrative, it will only show the title of the cell while it's in the queue. So the cell will be added to the narrative and only the title will be …

bails out if no w [TASK-588]

---

Gruntfile.js
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/util/bootstrapDialog.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSharePanel.js
test/functional/spec/smoketest/loadLoginPageSpec.js
test/unit/spec/narrative_core/kbaseNarrativeSharePanel-spec.js

There's a number of usability issues with the narrative sharing interface. This'll deal with a few of them.

TASK-834 Make the sharing UI more usable

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/util/timeFormat.js
test/unit/spec/Util/TimeFormatSpec.js

There was no mapping for May, oddly.

KBASE-5243 - Fix mapping from numerical month -> abbreviation

---

Dockerfile
RELEASE_NOTES.md
bower.json
narrbase-image/Dockerfile
narrprereq-image/python-pip-list-narrative
package.json
scripts/build_narrative_container.sh
src/biokbase/narrative/__init__.py
src/config.json

* bump narrprereq image to 1.2 (add distribution update, add ETE3 in environment)
* bump narrbase image to 4.7
* bump narrative to 3.4.2

Bump version of base images and narrative

---

kbase-extension/static/kbase/config/data_source_config.json

Removed the pubSEED_genomes section from all 4 environments and replaced the legacy_genomes in appdev environment with reference_genomes as in prod.

Removed the pubSEED_genomes section 

---

kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseExpressionSampleTableNew.js

I don't have an associated TASK ID - these were per request of Arfath who encountered a few bugs while using the ExpressionSampleTableNew widget.
* Now reports an error message if loading the sub-objects also fails
* Only presents a single TPM tab, not constantly adding them

bug fixes to kbaseExpressionSampleTableNew.js

---

RELEASE_NOTES.md
bower.json
nbextensions/appCell2/widgets/appCellWidget.js
package.json
src/biokbase/narrative/__init__.py
src/config.json

This case should just make a "version out of date" warning, but prompt with the newer name for the new app to click to update, instead of causing the app cell to crash all together.

TASK-877 new versions of apps with a new name caused errors

---

kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseExpressionSampleTableNew.js

Speaking poorly to our QA work, mostly mine, Arfath discovered yet another bug.
Choosing different expression levels would merely append more rows to the overview table, not redraw it.
Fixed. Also updated to the current data tables api in the process.

another bug fix to ExpressionSampleTableNew

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionVolcanoPlot.js

Lots of refactoring work on the volcano widget, inevitably with more to come. But you gotta draw a line somewhere.
The final result is that it's a drop in replacement and it should work pretty much identically to the old one. The only appearance change is (temporarily?) disabling the popups on the genes, since they don't currently work. That needs more investigation.
There may be minor appearance tweaks.
Other things -
* Should be ready (or at least readier) to be updated to use the dynamic service, once it exists.
* Got rid of global dom uniquely generated DOM ids in favor of locally stored refs.
* Re-shuffled around some methods for legibility.
* got rid of embedded html in favor of jquery selectors. Longing to port everything into React and redux.
* The SVG code should still be …

new volcano plot; same as the old volcano plot

---

kbase-extension/static/kbase/css/appCell.css

This resolves TASK-922, aka TASK-448 regarding the red error bar in firefox.
The basic issue appears to be that Firefox won't render an empty element with a variable size height.
As is always the case with stupid cross-browser CSS issues, the fix is stupid - it just explicitly wires the height to 28px, which is the height of the line. I'm unhappy about having the magic number in there.
Alternatively, fieldWidgetCompact.js is the widget which is used to render it. Firefox doesn't want to render an empty element with a percentage height, so we could alter the indicator element to append a &nbsp; (or a clear gif? I suppose?) into that field. Doing that will also make firefox happily render it w/o issue.
Using the 28px magic number in the style sheet seemed like the lesser of the evils, but …

Stupid red bar fix [TASK-922]

---

kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSharePanel.js

Whenever the sharing modal opens, it should show the current state of sharing; it shouldn't cache things from the previous time.

TASK-959 Make the Narrative sharing panel refresh

---

RELEASE_NOTES.md
bower.json
kbase-extension/static/kbase/js/api/auth.js
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/kbaseNarrativePrestart.js
kbase-extension/static/kbase/js/narrativeConfig.js
kbase-extension/static/kbase/js/narrativeLogin.js
package.json
src/biokbase/auth.py
src/biokbase/narrative/__init__.py
src/biokbase/narrative/app_util.py
src/biokbase/narrative/exception_util.py
src/biokbase/narrative/handlers/authhandlers.py
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/specmanager.py
src/biokbase/narrative/widgetmanager.py
src/config.json

There's a number of reasonably small changes in this PR: here's a summary.
1. If the browser stops checking whether it has an auth token for ~1 minute (mainly only happens if the computer goes to sleep), it will test if the token is still valid, regardless of the amount of time remaining in its lifespan.
2. Backend service clients are now always generated as needed. Previously, it was cached for essentially the lifetime of the server.
3. A teeny bit of code cleanup.
I have a nagging suspicion that this won't solve all the problems we've seen, but hopefully it will help.

TASK-932 address token failure problems

---

kbase-extension/static/kbase/js/common/sdk.js
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/subdataInput.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

The subdata control was, in some cases, interpreting an empty default value (a spec with a default value of [""]), as a default value, and populating the initial parameter object thus.
In addition there was other weird behavior with the subdata control with regard to preserving, or not, the default value when the dependent parameter (the one supplying the subdata values to select from) was changed. The fix will preserve any previously selected values which occur in the new subdata.
One minor fix to resolve a race between the kbaseNarrativeWorkspace object and the sidePanel.

Fix subdata control [TASK-1035, PTV-295]

---

kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseReadsSetView.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js
kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseRNASeqAnalysisNew.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
nbextensions/dataCell/main.js

Adds the command `Jupyter.narrative.addViewerCell(obj)` to the Narrative object.
`obj` can be one of three things.
1. a string, as an object reference.
2. an array, the typical object info returned from Workspace.get_object_info*
3. an object, with key-value-pairs defined by kb_service/utils/getDataObjectByRef (keys = id, name, version, etc. These all match up the array returned by Workspace.get_object_info*).
This inserts a Viewer cell below the currently selected cell.

Add method for programmatically inserting a viewer

---

scripts/narrative_backend_tests.sh
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/narrative_mock/mockcomm.py
src/biokbase/narrative/tests/test_app_util.py
src/biokbase/narrative/tests/test_appmanager.py
src/biokbase/narrative/tests/test_jobmanager.py
src/biokbase/narrative/tests/test_narrativeio.py
src/biokbase/narrative/tests/test_specmanager.py
src/biokbase/narrative/tests/test_updater.py
test/unit/initTestEnvironment.js

Updates and fixes backend tests in the following ways:
1. Support for auth2 (finally...). Requires manually adding a token to a couple of files as defined in `src/biokbase/narrative/tests/test.cfg`
2. More widespread support for service client mocking.
3. Test recent changes made to better support token timeouts.

Test refactor

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppPanel.js

Even if you use 'dev' it would default to 'release'. Actually, it was defaulting to whatever was set in the App Panel, which is typically release.

Fix problem with app insertion API not respecting app tag

---

nbextensions/appCell2/widgets/tabs/resultsTab.js

Some time ago, the Suggested Next Steps stopped showing up (https://kbase-jira.atlassian.net/browse/KBASE-3778). While awaiting a fix for that, I suggested in https://kbase-jira.atlassian.net/browse/TASK-1017 that we should just not show that Suggested Next Steps panel if there aren't any (otherwise it looks like all the apps are dead ends, which they're not).
I am suggesting this fix (which simply moves the ui.setContent('next-steps') call into the if (apps.length > 0) block) but I am not set up to test it. Hopefully @thomasoniii  can test my fix and see if it works. If it does, it would be great to get this deployed to prod ASAP! @RoyKBase @sychan

Don't show Suggested Next Steps if there aren't any

---

kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseRNASeqAnalysisNew.js

The inputs to the widget changed at some point.
It has always been wired up to display the name if it was available, and to fall back on the ref if it wasn't. It looks like it was previously assuming it would receive one list of infos items from get_object_info3, but now it's receiving multiple lists, each with multiple infos. Or maybe different data inputs would sometimes produce multiple lists and it was never tested with those combos in the past? Dunno.
Regardless, it's updated to allow for lists of multiple objects, each with their own infos, which resolves the issue. Again, if no name is available, it'll fall back on displaying the ref.

updated to assume lots of extra_args with infos [PTV-535]

---

RELEASE_NOTES.md
kbase-extension/static/kbase/templates/document_version_change.html

Fixes a problem with the popup template where it said "you might consider getting in contact with (some version number)" instead of a real user name.

TASK-1041 - fix problem where version shows up where username should

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/tour.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
test/unit/spec/narrative_core/kbaseNarrativeAppPanel-spec.js
test/unit/spec/tourSpec.js

Changes some behavior along with the fix.
* fixed the output filter button from the data panel
* now accepts "input:" and "output:" along with "in_type:" and "out_type:" (I figured it looks a little cleaner and more obvious)
* the input and output setting are more stringent - it will only accept the complete token. E.g. input:Genome will no longer match GenomeSet or PanGenome.
* adding the complete type name (prefixed with Module name) is similar in its strictness - KBaseGenomes.Genome will not match KBaseGenomes.GenomeSet.
* pretty much anything goes with the non-typed search. Searching for anything (not prefixed with "input:" or "output:") will do a simple string search in the name, input types, and output types.

TASK-1069 Fix problem with app panel filtering.

---

kbase-extension/static/kbase/js/widgets/function_output/modeling/kbasePathways.js

The number of reactions and compounds associated with pathways was maxing out at 95 because the number was calculated incorrectly.

Fixes PUBLIC-123: Bad reaction counts

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js

This fixes Ticket KBASE-4756.
The filter list on the data panel only presented the type name to the user, but there are types which exist in multiple modules. As a result, filtering didn't work. If a user had a "KBaseAlpha.Foo" object, but the widget was filtering on "KBaseBeta.Foo", nothing would show up.
This change does a couple of things:
* It removes the hardwired list of types from the widget. It was incomplete and out of date.
* It dynamically builds a new list of types to present to the user, based upon the results of getAndRenderData. That way, the user will only see the option to filter to types that they have, instead of the massive list of all possible types.
* The filter list includes all modules in its filtering. So it'll show "Foo" in the dropdown, but actually filter on …

Fixes filtering [KBASE-4756]

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

This fixes sorting by type, with a caveat -
The type will sort by the fully qualified name, which may be a little confusing to the user. e.g., in the collapsed view of the data, the user may see "GenomeAnnotation" and "Media" and expect "GenomeAnnotation" to be first in the sorted list. It won't be. 
That's because the actual types are "KBaseGenomeAnnotations.GenomeAnnotation" and "KBaseBioChem.Media", and will in turn sort KBaseBioChem.Media first.
I left the behavior as is, since the user could expand the data item and see the full name, but we may want to change this.

Fixes PTV-225

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseBinnedContigs.js

(because it's listed as a fraction, not a %)
As requested by @paramvir in https://kbase-jira.atlassian.net/browse/PTV-758

Change "GC Content %" column header to "GC Content"

---

kbase-extension/static/kbase/js/api/fileStaging.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeStagingDataTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/fileUploadWidget.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/uploadTour.js
src/config.json

* Cleaned up some things that made my linter angry - mainly whitespace and quotes.
* Changed staging area viewer to use newer API calls for handling things (fetching files, inserting app cells).
* Tweaked the file staging client to be a little more flexible with its list function.

Small refactor to import panel

---

test/unit/karma.conf.js
test/unit/run_tests.py

Apparently Travis-CI no longer likes the Jupyter notebook being started up on `localhost`, but it will handle `127.0.0.1`.
As of, like, Tuesday.
Hopefully this fixes it for the foreseeable future.

Fix Travis-CI testing

---

kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/api/StagingServiceClient.js
kbase-extension/static/kbase/js/util/timeFormat.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
kbase-extension/static/kbase/templates/data_staging/ftp_file_table.html
test/unit/spec/Util/TimeFormatSpec.js

This integrates changes from the feedback doc here:
https://docs.google.com/document/d/1LLhFVipqMRkZ16IGFwwbKeX5-VDecMkombH1hk-6_2g/edit#
* Age is now rendered with "short" names, i.e. "88 secs" instead of "88 seconds ago"
* The remove button is moved to the right, and framed in a button. Still inside the expanded area, though.
* Changed formatting of Info field - bolded text, changed size, removed colons, added commas to line count.
* first 10 / last 10 are in a slightly different gray and monospace font
* fixed the bug that could cause metadata to not appear if sorted
* added the decompression button, which only shows up for files assumed to be compressed.
* Added "All files will be deleted after 90 days" footer.
errata -
* I also added a change to swap the directional arrow on the data …

Staging panel updates

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

Might need another pass at this, but this changes the twin arrows button (in the list sort of the left-side data panel) to a hierarchy sorting button. This one - http://fontawesome.io/icon/sort-amount-asc/
It will then flip the icon and flip the sort order.
I'm not sure what's a better way to show this. This icon goes from "small" -> "large" (or the reverse), which I'm implying to be A -> Z for name / type sorting, or newest -> oldest for date sorting.

PTV-225 Clarify sorting control

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
kbase-extension/static/kbase/templates/data_staging/ftp_file_header.html

This tacks on the KBase username to the globus link.
It also hides the globus link entirely if the user doesn't have globus as a provider. We may want to re-visit this to instead display a "signup for globus link" instead.
Also brings along two minor tweaks to the metadata - there's apparently a bug in the service wherein it may not hand back a line count or md5, this just adds some extra prettiness to the user to change the blank or NaN into "Not provided".

resolves [KBASE-5410]

---

kbase-extension/static/kbase/js/util/icon.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseDataCard.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

A recent update replaced the genome icons in the data panel with the default icon (document). This brings them back.
The problem was with how the object type was getting interpreted by the new KBaseDataCard abstraction. I added a new "viewType" parameter to that (so the "type" string could continue to have things like the scientific name), and shuffled around how the actual data type gets read.
Also did a little bit of general cleanup on a few things.

PTV-833 Fix genome icons in data panel

---

kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/function_output/kbasePanGenome.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

Peripherally related to other copy/sharing problems, I'd say this is more a problem of policy. Basically, in an original narrative, the object name and current workspace name are passed to the pangenome viewer, so it looks up the object by the "ws_name_a/obj_name_a" formulation.
In a copied narrative, due to some deep flaws in the architecture (being addressed here: #1214 ), it gets passed the current workspace name still, but now the UPA of the object from the original workspace, so it tries to build a reference as "ws_name_b/ws_id_a/obj_id_a/obj_ver_a" which is wrong.
This PR fixes a few minor issues in other modules, then "fixes" the problem in the pangenome viewer by having it interpret the object identifier passed to it. If it looks like an UPA (has a '/' character), it gets treated …

PTV-682 - temp fix to Pangenome viewer

---

kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js

This will add an additional tab to populate file metadata, if it exists.
Notes:
* It manually finds the metadata file by looking at the first part of the filename before the first period, and then appends ".metadata" to the end. So that if your file is "foo.bar.baz.fasta.gz", it'll look for a metadata file called "foo.metadata". This is reasonably brittle, in that if the naming convention changes it won't find metadata. Arguably, this should be wrapped up into the staging service client, but as of yet this is the only way to get at it.
* It was mentioned on the call yesterday that metadata files will no longer be visible to the user - we need to make sure that this method still works even if the metadata files cannot be seen. If not, then we're back to what was said above about adding it …

adds contents of metadata file to metadata tab [STC-284]

---

kbase-extension/static/kbase/js/api/StagingServiceClient.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js

We now have a jgi-metadata endpoint to vend back jgi-metadata files.
So the logic is the same as before - when the expanded view on a file is opened, it attempts to load jgi metadata. If any is found, it is tossed into a new tab, now named "JGI Metadata" instead of just "Metadata".
While I was at it, I slowed down the load by a fraction of a second but got rid of the "JGI Metadata" tab blinking into view after the other tabs. I felt this was the lesser of the evils.
IMPORTANT NOTE - this is explicitly *not* backwards compatible with older styles of storing jgi metadata. Previously, the importer would create a second file with a .metadata extension (foo.jgi.fasta and foo.jgi.metadata), and the frontend would look for that file. It doesn't do that any more. So any older imports would not …

Update to use jgi-metadata method [SCT-284]

---

kbase-extension/static/kbase/css/kbaseJobLog.css
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
nbextensions/appCell2/widgets/tabs/jobLogViewer.js

-no longer crashes when two lines are the same
-scrolls up and down during app run pause
-line numbers are unselectable when copying
-x axis scroll removed (border that looks like scroll left in)

[KBASE-5405] bug fixes

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js

The decompress button is now on the left of the file name, so it's always visible.
Probably needs more work, but it's a start.

just moves the decompress button to the left side

---

kbase-extension/static/kbase/js/widgets/function_output/modeling/KBaseFBA.FBAModel.js

Some minor tweaks to the modeling viewers:
1. If there is no enzyme data for a reaction, the entire viewer won't crash
2. Compound names in reactions will link to their respective compound pages

Struct to image

---

kbase-extension/static/kbase/js/tour.js

removed redundant sentence, added link to data upload/download guide (minus the "http", following the example of other hrefs in this code).

improved wording of import tab tour text

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeStagingDataTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js

This pull does a couple of things -
* kbaseNarrativeDataPanel and kbaseNarrativeStagingTab are updated to allow a widget on the panel to have an activate() / deactivate() method to be called when the panel they are on respectively comes into view / leaves view. These methods are not required to be defined. But they're generic in nature, so that if we want a tab to do extra processing when it comes to the foreground, it can.
There is a gotcha in that an active widget will not be told to deactivate() if the panel is closed by any means other than hitting the toggle button. This should be re-visited.
* stagingAreaViewer now auto-refreshes its view every 30 seconds. The timer will start when the widget has been sent an activate() and stopped when the user sends it a deactivate(). Per the …

added auto-refreshing of staging panel [SCT-516]

---

RELEASE_NOTES.md
bower.json
kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/js/common/runtime.js
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/narrativeLogin.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
package.json
src/biokbase/narrative/__init__.py
src/config.json
test/unit/spec/narrative_core/kbaseNarrativeStagingDataTab-spec.js

It was using a somewhat hidden, cached copy instead of straight from the browser cookie. Now, when the kernel restarts, it should do so with the browser's cookie, which should be up to date.

SCT-401 Inject the correct auth token on kernel restart

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js

I have no idea why this is necessary.
The pre-autorefresh version of kbaseNarrativeDataPanel.js had a list (this.renderFn) that mapped tab -> render function. The last item was an empty function, which you can see here: https://goo.gl/wvPvxd
When I modified it to allow tab activate/deactivate (to turn on and off the auto-refresh timer on the import panel), I retooled that to have a tabMapping object instead which just contained the render() function and a reference to the widget involved. While doing that, I found that my mods didn't work in my local environment if I kept that empty render function there. So, foolishly assuming it be an artifact, I removed it. My code them worked locally.
Apparently after pull and merge, the panel started failing when you closed it on the Import tab. …

restored required empty function which does nothing

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppPanel.js

maranas tools had a typo in it - one of its methods was categorized as "metabolic_modeling", and the other was categorized as "metabolic modeling". Both of those categories would display as "Metabolic Modeling", yielding a duplicate category in the UI.
This change re-wires how the unique list of categories is built - instead of keying off of the string used in the spec file, it keys off of the name that will eventually be displayed to the user. Note that this also uses categories.yml file for keying purposes.
The result is that previously, you could have multiple spec files with categories such as "assembly", "genome_assembly", "genome assembly", and "Genome Assembly" and you'd end up with 4 different categories in the app panel, all named "Genome Assembly".
Now, all of those categories …

keys by category display title

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js

I spotted on the demo on Friday that there was a bug - if you opened the metadata view, closed it, and re-opened it, then you would no longer be able to switch tabs (info/first 10/last 10). This was because I was removing the node via the remove() method (which also clears all event handlers) instead of the detach() method (which works the same, except it won't clear out event handlers).
Updated to reflect that. Also added a class to the row so I could detach all nodes before it was emptied  in render() as part of the periodic refresh (empty() will also detach handlers).
Finally for some unrelated cleanup, moved the redundant code on the jgi_metadata call into an always() block. Duh.

fixed close/open bug [SCT-581]

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeStagingDataTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/fileUploadWidget.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
kbase-extension/static/kbase/templates/data_staging/dropzone_area.html
kbase-extension/static/kbase/templates/data_staging/ftp_file_table.html

The main purpose of this pull is to add drag 'n drop support of folders.
NOTE - DnD of folders does _not_ work in Safari. Chrome and Firefox work properly. This is a browser limitation and not something we can get around atm (AFAIK). Once Safari is updated to support the mods to the FormData object, it should automatically start working.
To that end, several things were changed on the staging panel:
* Clicking on the decompress button will now pop up a spinner as it decompresses.
* The delete button was moved to the row that the file is in (from within the detailed view) and will also now allow the user to delete directories.
* Several bugs were fixed regarding handling of subdirectories - including viewing and deleting files within them.
* The list endpoint on staging_service was …

Staging panel [SCT-585]

---

kbase-extension/static/kbase/js/narrativeConfig.js

It doesn't happen often, but when the data source config (the config file for updating the sources for Public data in the data slideout) gets changed, the Narrative tends to not pick it up as it's cached in the browser.
This adds an explicit cache busting call, instead of just being lazy and using $.getJSON.
Also, this expects #1272 to be merged first.

SCT-590 cache busting for data_source_config.json

---

kbase-extension/static/kbase/js/util/bootstrapSearch.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
test/unit/spec/Util/BootstrapSearchSpec.js
test/unit/spec/narrative_core/kbaseNarrativeAppPanel-spec.js

The fix was reasonably simple, but playing around exposed that the search boxes in the app panel and data panel were different. They (more or less) should act the same, but looked slightly different. To avoid keeping duplicate code around, this factors that search box out into a generic, though specialized, widget. It might be a little much, but it keeps things consistent.
The widget - BootstrapSearch - makes a simple Bootstrap input form with an attached clear button. Options sent to it on initialization set its functionality, mainly what to do when a user types.
This also includes some whitespace and style cleanup to the App panel.

SCT-706 - fix app panel search not accepting spaces

---

bower.json

The problem was a unconstrained dependency on the "file-saver" library. The "^" operator causes the narrative build process to pick up the most recent version of the library; a change in 1.3.6 (current version is 1.3.8) broke the library by, um, omitting the javascript file which implements the library.

Fix broken pangenome viewer [SCT-793]

---

kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseFigureObjectHeatmap.js

Despite my generally sarcastic commentary, the original requests were fairly straightforward -
The object that goes into the multi-cluster heat map returns its clusters in some sort of arbitrary order, and the desire is to have them sorted. So this now sorts clusters into alphabetical order. Cluster, transcript label, and row data information are not tightly coupled, so there's a lot of hoop jumping to parse through the data to tease it apart and then sort and put it back together.
It also prunes out any rows which have all null values for their columns. Same hoop jumping ensues - a cluster only knows which rows are associated with it by a count of the number of rows in the cluster, which is based on an array describing cluster counts by index. So the order of that array needed to be …

deals with undesirable input data [SCT-875]

---

src/biokbase/narrative/app_util.py
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/tests/test.cfg
src/biokbase/narrative/tests/test_appmanager.py

This adds a `run_app_batch` function to the appmanager. Instead of taking a single dictionary of inputs, it takes a list of dictionaries. These get built out (based on the app their calling), then bundled together in a call to the kb_BatchApp.run_batch app.
This all might change eventually, but it's a place to start from.

SCT-962, SCT-975 batch backend

---

kbase-extension/static/kbase/js/util/timeFormat.js
src/biokbase/narrative/clients.py
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobmanager.py

There really isn't much to do for the batch jobmanager, as defined now. But this wires things together to use the mock job checking service. Also there's a couple minor fixes to some frontend things.
So it's temporary, but reasonably small. It does also depend on #1314 getting merged first, though.

SCT-976 batch jobmanager

---

src/biokbase/narrative/jobs/appmanager.py

The parameters being sent to the batch app weren't what was expected. Expected a string like "module.method" for app_id. Instead, app_id expected just the module name.
So this is the narrative side of two changes. The kb_BatchApp.run_batch now expects "module_name" and "method_name" to be separate, and this Narrative change updates to meet the right expectations.

fix problem when starting a batch app

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

Just a very minor change to have the icon for a non-functional disabled report viewer button be the same as the enabled button (the "file-text" font awesome font) but showing in a disabled state.
I was experimenting with icons for the states, and left the "ban" icon inadvertently.

disabled report viewer button is now disabled text file not ban [SCT-930]

---

kbase-extension/static/kbase/config/feature-config.json
kbase-extension/static/kbase/css/kbaseNarrative.css
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/appParamsWidget.js

Just tweaks a couple small things since the last update that cleaned up how fonts are made.
1. Changes the Narrative titles back to non-italicized.
2. Changes the font in the loading screen from just a plain serifed font (I think it was Times New Roman) back to Oxygen Bold.
Others could go here, too. I think a mix of the font sizes and bolding make them look squashed together in the data and app cards, as well as the headers to the data slideout, but those might take extra fiddling.

font styles

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCardLayout.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePublicTab.js

couple of regressions in the data copy feature for the public data tab:
- genome names with html-entities needed additional scrubbing when translating to object name
- the public data tab's copy of the data list widget's data was populated at widget creation time, which occurs (at least now, or sometimes) before the data is loaded, so it was behaving (initially) as if the there were no objects in the narrative, which conflicted with the workspace calls which revealed that there were! A race condition. Moved the data loading into the first render of the widget, rather than the init method (aka, constructor).

SCT 1082 - fix public data tab regressions

---

src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobmanager.py

- it looks like this was left in place from development
- job_service_mock causes job queries fail outside of CI

restore "job_service_mock" to "job_service"

---

Dockerfile
package.json
scripts/local-dev-run.sh

The bower version in the base image is 1.7.6; the current version is 1.8.4. 1.8.0, released in late 2016, deprecated the old package service hosted at heroku. The herokuapp service still works, sometimes, but is not reliable. This fix updates the narrative's locally installed bower, which was at 1.7.9, to 1.8.4, and the Dockerfile to use the locally installed bower.
A small fix to the local image run script removes the mapping of the ext_components directory, which breaks if ext_components is not installed locally, which for me is more often than not the case. It is also only rarely used for testing new dependency versions without needing to rebuild the image.

Fix bower version

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionVolcanoPlot.js

Ensures that the displayed columns are fixed to at most 2 decimal places.

log values to fixed 2 decimals [SCT-380]

---

docker/docker.lua
src/config.json.templ

These commits modify the Lua code to look for an environment variable called NARR_ENV_VARS which is then inserted into the default docker client config for environment variables passed to along at narrative container startup.
The value for NARR_ENV_VARS should an array of NAME=VALUE strings. For example, the following docker command will startup the nginx container and set the CONFIG_ENV variable to appdev for all narratives started by the Docker.lua module:
`docker run -it -v /var/run/docker.sock:/var/run/docker.sock -e 'NARR_ENV_VARS=["CONFIG_ENV=appdev"]' kbase/nginx:latest`
This commit also fixes the default docker configs for CMD and USER so that they don't clobber the settings built into the narrative image. The old defaults set CMD to /bin/bash, which stopped the narrative from …

Pass along Env Vars at Narrative startup, fix problematic defaults for docker config

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js

@scanon - This PR changes 'Select a format' to 'Select format' on the Import selection pane. The goal is to eliminate the ellipses that currently appear as "Select a for..." in PTV-1023.

Change import button to 'Select format' PTV-1023

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionVolcanoPlot.js

Apparently the log2fc_f value can sometimes be undefined/null. So just wraps it in a check to see if we can get a truthy value out of it, and if so make it toFixed(). 
Otherwise, just leave it as is, since I wasn't comfortable with making explicitly undefined values "0".

fixed undefined object bug [SCT-380]

---

kbase-extension/static/kbase/custom/custom.css

In Jupyter Notebook 5.6.0, there's a new run button that shows up on hover over any code cell. ( see this PR: https://github.com/jupyter/notebook/pull/3535/ Clicking it runs that cell. Pretty nifty, but it breaks a number of different design things we have, including how app cells are supposed to run.
This is the short term fix so we can use their security fixes - just hide the new thing.

SCT-1199 hide the new run button

---

kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseRNASeqPieNew.js

kbaseRNASeqPieNew was formatting numeric values as strings to be pretty printed (e.g., 1004.21342 would become 1,004.213), but this was causing concatenation issues because sometimes those formatted values were used in addition (e.g. "1" + "1" = "11" instead of "2").
This reformats the value_for_wedge() method so it just returns the raw numeric value and not the formatted string.
It also adds a new method formatted() which actually does the formatting. This way we can do math on the values as format them once we reach the point of display.
A final note - the value_for_wedge method is effectively vestigial at this point anyway. This widget was originally designed to display a pie chart with a donut chart surrounding it that would contain a breakdown of values. That is, a wedge on the pie …

fixed concatenation bug [SCT-1253]

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js

The issue was that `reportRowEvents` was only called on table load but not on pagination. This PR fixes that as well as updating the settings to be current with jquery-datatables and removing dead code.

SCT-1393: Fix "Objects Created" links

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseDataCard.js

Was not able to find a good way to write a unit test though as the attributes are not showing up in jasmine (but they do work in practice).

Fixes the tooltip popup for long object names

---

src/biokbase/narrative/clients.py
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py

Agent token info was passed to a started job, but apparently the token itself must be used to create the Job Service client that starts the job.
This fixes that.

Fix agent token

---

kbase-extension/static/kbase/js/common/jupyter.js
kbase-extension/static/kbase/js/common/runtime.js
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/kbaseNarrativePrestart.js
kbase-extension/static/kbase/js/narrativeConfig.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
kbase-extension/static/narrativeMain.js
src/biokbase/narrative/common/exceptions.py
src/biokbase/narrative/common/narrative_ref.py
src/biokbase/narrative/contents/kbasewsmanager.py
src/biokbase/narrative/contents/narrativeio.py
src/biokbase/narrative/handlers/narrativehandler.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_kbasewsmanager.py
src/biokbase/narrative/tests/test_narrative_ref.py
src/biokbase/narrative/tests/test_narrativeio.py
src/biokbase/narrative/tests/util.py
test/unit/spec/api/upaApiSpec.js
test/unit/spec/narrative_core/kbaseNarrativeOutputCell-spec.js

Currently Narrative URLs all look like this: https://narrative.kbase.us/narrative/ws.###.obj.###
This will adjust to allow urls like this: https://narrative.kbase.us/narrative/xyz where xyz = a numerical workspace id. The changes in this PR handle the following cases:
1. workspace has a single narrative, set in the workspace metadata.
2. workspace has a single narrative, but NOT set in the ws metadata.
3. If the workspace has either 0 or > 1 narrative (and the ws metadata is not set), it will throw a 404 error.
This wound up requiring a refactor of some deep chunks of the ContentsManager that's plugged in to Jupyter, so there's a bunch of changes and more tests are needed before merging (but I want them tested in Travis-CI as well).
Also, there's some front end adapter work that needs to …

SCT-1602 Allow workspace id for Narrative URLs

---

kbase-extension/kbase_templates/403.html
kbase-extension/kbase_templates/error.html
kbase-extension/kbase_templates/generic_error.html
kbase-extension/static/errorMain.js
kbase-extension/static/kbase/js/narrativeLogin.js
src/biokbase/narrative/common/exceptions.py
src/biokbase/narrative/common/narrative_ref.py
src/biokbase/narrative/contents/kbasewsmanager.py
src/biokbase/narrative/contents/narrativeio.py
src/biokbase/narrative/handlers/narrativehandler.py
src/biokbase/narrative/tests/test_narrative_ref.py
src/biokbase/narrative/tests/test_narrativeexporting.py
src/biokbase/narrative/tests/test_narrativeio.py
src/config.json.templ

All communication errors with workspace now raise a WorkspaceError (before was just either the standard ServerError, or a PermissionsError). WorkspaceErrors are aware of what http_code they should have, and parse the Workspace error message into something more fitting for the Narrative context.
These errors now show up a little more pretty on the front end, too, and include the same trimmed-down header as the permissions error.

Better generic error handling

---

docs/developer/local-docker.md
kbase-extension/kbase_templates/page.html
scripts/local-dev-run.sh
src/biokbase/narrative/handlers/narrativehandler.py
src/config.json.templ

- add per-deploy-env google analytics tracking id; previously was hardcoded to production
- update google analytics usage to use latest recommended google js lib
- improvements to local-dev-with-docker docs and script
This PR strives to improve google analytics usage, as part of the current effort to improve GA support at KBase. To wit:
1. Update the analytics library to the recommended google client. That is, since the Narrative already uses the GA client downloaded from google via the code snipped published by google, this replaces the current google client code snippet with the current release.  The previous client was "analytics.js", and the current one is "gtag/js". Usage is a bit different. This matches the new google analytics usage in the static app catalog.
2. Utilize unique a GA …

improved google analytics support

---

kbase-extension/static/kbase/js/util/display.js
nbextensions/appCell2/widgets/tabs/resultsViewer.js

Similar to the lazy loading of viewers, this goes through the following cycle:
On AppCell report panel load, check if the panel is in the viewport. If so, render the KBaseReportView widget and be done. If not, attach a scroll listener to the `#notebook-container` element. On each scroll event fire, check if it's in view again. When the panel goes in view, render the widget and remove the listener.
There's one little hack in there where if the bounding box being tested has no height and is at top 0, bottom 0, treat it as not in view. It's probably not actually being rendered on the page yet, so this is safe.

Add lazy loading to reports

---

RELEASE_NOTES.md
bower.json
kbase-extension/static/kbase/custom/custom.js
kbase-extension/static/kbase/js/kbaseNarrative.js
package.json
src/biokbase/narrative/__init__.py
src/biokbase/narrative/contents/narrativeio.py
src/biokbase/narrative/tests/test_narrativeio.py
src/config.json
src/config.json.templ

**MASTER VERSION** - a PR is also set for develop
This bug crept in before GSP.
A user with "write" access (i.e. "w" in workspace) is unable to save a Narrative right now, as it requires a little poke at the workspace metadata. Only workspace admins can change that. Previously, the error that was thrown was just silently ignored, now it's propagated forward.
The solution here is in two parts.
1. Check if the user can edit the ws metadata before saving. If not, (they don't have 'a' perms on that ws), then don't even try.
2. The main way that ws metadata gets modified is with the narrative name. So prevent anyone who isn't an admin from changing the Narrative name through the browser (this checks and shows a polite error message now).

Fix share saving

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeControlPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePanel.js

Took a little tweaking to a few places.
In the parent widget class for the Narrative Manager widget, I added an `activate()` method. This gets invoked whenever that tab gets clicked on by the user. It's a no-op in the parent widget, so each child widget can extend it. Only the Narrative manager widget uses it to do its first rendering, then it doesn't do so again.

Lazy-load the Narratives tab

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeComparisonViewer.js
kbase-extension/static/kbase/js/widgets/function_output/kbasePanGenome.js

Proposals 1 and 2 in
https://docs.google.com/document/d/1vktk2Wq6NrovJ9MOSRZm5HuNM54r0N7HP_96fKcVSZY/edit#
Rename the column headings to be consistent and move the Functions column to last. Of course this could blow up if the Functions code is creating something that the Families section needs but we will just have to see.

Update column headings and order on Pangenome output display

---

Dockerfile

fixes a problem where installing deps with conda wants to overwrite python2 with python3, which then breaks the whole build.

update dockerfile to install with pip instead of conda

---

src/biokbase/narrative/jobs/jobmanager.py

NJS 1 had an occasional (very rare these days) problem where it would throw an error on returning a job. These were captured during the `initialize_jobs` function and forwarded to the browser.
This is different from a job being in an error (or the new terminated) state. Those are still valid and shouldn't raise an overall exception.
I'm guessing things will be a little more stable, too, so this just eliminates that individual job lookup error, especially now that they're all looked up in a batch, so the lookup will all either work at once or fail all together.
This also fixes some issues with the `list_jobs` function.

JobManager error on startup

---

.gitignore
kbase-extension/static/kbase/js/widgets/appWidgets2/input/dynamicDropdownInput.js
package-lock.json

Fixed two bugs:
The dynamic dropdown was hardcoded to only handle the case where the selection
items were in the first position of the return array and were at the first level
of the object at that position.
Now the position of the object in the return array and the path into the object
to the selection items can be specified.
Some dynamic service functions don't like empty input, but the DD will always
query the server regardless of the input contents. This behavior can now
be configured.
These changes require https://github.com/kbase/narrative_method_store/pull/74
There are no meaningful tests for the DD, and developing  a test harness
for the DD is way out of scope, so the changes were tested manually.

Bugfix for dynamic dropdown result processing

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/dynamicDropdownInput.js

1. fetchData needs to always return a Promise (even on a no-op, empty array return)
2. Calling the select2 command again when showing a dynamic dropdown tagged as advanced would cause the dropdown to forget its ajax ability (should probably be double-checked in different browsers, but verified in Firefox and Chrome)

minor dynamic dropdown fixes

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseBinnedContigs.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeComparisonViewer.js
kbase-extension/static/kbase/js/widgets/function_output/kbasePanGenome.js

@briehl 
PTV-1214 - Binned contig viewer - Make column heading change
PTV-1341 - GenomeComparison Viewer had information that wasn't needed and was missing some very useful information. The details are in the ticket.
Previous update - In the genome comparison viewer, the column and row heading should have been G1, G2, G3... but they came out G01, G11, G21 because I was adding a 1 as a string instead of a number.
Previous update - Last time I moved a column in the 'Families' table and the wrong column was getting a hotlink, which went nowhere. I just had to move the link to the first column instead of the second.
Unlike last time, this one has been tested because I now have narrative working locally. :)

PTV-1214, PTV-1341, fix problems from previous update

---

src/biokbase/narrative/app_util.py
src/biokbase/narrative/tests/test_app_util.py

Found a pretty big security flaw. If anyone takes advantage of this, it'll put tokens in provenance. Oops.

remove token from sys var option

---

Dockerfile

They were forcing an upgrade to python 3.8 which was breaking all kinds of things. Narrative can run fine on Python 3.7.3

version-lock Dockerfile installs

---

kbase-extension/static/kbase/js/widgets/narrative_core/staticNarrativesManager.js
package-lock.json
test/unit/karma.conf.js
test/unit/spec/narrative_core/staticNarrativesManager-spec.js

Mostly under-the-hood changes.
1. Use new get_static_narrative_info command from dynamic service, instead of Workspace calls.
2. Some minor bugfixes around error handling.
3. Fully test it.

Update exporter panel

---

nbextensions/appCell2/widgets/tabs/errorTab.js

Make the "Details" section of the app widget's error output formatted with a `pre` tag so you can see the proper linebreaks and debug things more easily

Minor error formatting fix

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/dynamicDropdownInput.js

DO NOT MERGE
Also pending in this PR is some looser validation, so if it gets a number or a string, it just stays as a number or a string. The idea here is that whatever the service provides should be passed along to the app. As long as its an atomic type (a number or string). Maybe booleans can be investigated in the future if we need, but expanding this to arrays or structures would just be ripe for abuse.

make the default behavior to do empty input search in dyn dropdown

---

kbase-extension/static/kbase/js/widgets/appWidgets2/validators/float.js

`if (min && min > value)` was being ignored if `min` is 0. So that's treated as falsy.
And fun fact, `isNaN(null)` evaluates to `false`. So it'll catch `undefined` and strings and whatnot, but not null? I ❤️ Javascript.

PTV-966 fix float validator

---

src/biokbase/narrative/contents/narrativeio.py
src/biokbase/narrative/tests/test_narrativeio.py

Fails happen when a non-owner shared user saves.
This got fixed a while ago on this branch, but somehow regressed when extracting EE2 code.

fix issues with narrative saving

---

kbase-extension/static/kbase/js/widgets/narrative_core/publicDataSources/searchDataSource.js

The links in the public data sidebar weren't working. It looks like `object.workspaceReference` needs to have a `ref`property. This should also fix the "Add" button, but I had a hard time testing that

Small fix on the public data links for the sidebar

---

kbase-extension/static/kbase/js/widgets/narrative_core/catalog/app_card.js
kbase-extension/static/kbase/js/widgets/narrative_core/catalog/kbaseCatalogBrowser.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseAppCard.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppPanel.js

Before, the side panel app browser was generating links like `https://ci.kbase.us/#appcatalog/module//KBaseFeatureValues`
But they should be `https://ci.kbase.us/#catalog/modules/KBaseFeatureValues`

Fix some app catalog links

---

src/requirements.txt

version 2.10 (previous one) has a security flaw.

bump jinja2 to version 2.11.1

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js
src/requirements.txt

This was mainly affecting firefox. Some how Chrome and Safari managed to get through, somehow. But it was a real bug.
The issue was that the list of Narratives in the Narrative panel was out of order, caused by referencing some key that didn't exist. So it was effectively comparing a string against `undefined`, which is weird.

Fix narrative sort order

---

kbase-extension/static/kbase/js/widgets/narrative_core/jobCommChannel.js
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py

The JobManager initialize_jobs call was not passing errors back to the browser. Now the flow goes:
1. Browser inits JobComm() with a kernel call.
2. JobComm (by default) tries to init JobManager.initialize_jobs
3. If that fails, JobComm sends the old `job_init_err` message across the channel.
It's that step 3 that wasn't there, so instead of sending a message (the front end registers a channel, the kernel response really creates it), nothing was happening. The semaphore that the app cells wait on never clears, and app cells never become more than just an empty header.
This fixes that with the initialization error prompt.
You can test by spoofing a bad EE2 endpoint in the config.

Handle errors at job init better

---

kbase-extension/static/kbase/css/kbaseJobLog.css
kbase-extension/static/kbase/js/util/jobLogViewer.js
test/unit/spec/Util/jobLogViewerSpec.js

Addresses #1621 
* Make unique element id for viewer with `html.genId()` (see line 1042 - fetching the panel element)
* set id = the generated id
* Remove most/all references to jquery and jquery as a dependency
* There was just one remaining - an animate step. Swapped this out with a simple CSS transition.
* Rename warpperDiv -> wrapperDiv
* just a typo, fixed
* Redundant if statements around line 663.
* Also fixed.

remove jquery from job log viewer, other minor fixes

---

kbase-extension/static/kbase/js/util/jobLogViewer.js
test/unit/spec/Util/jobLogViewerSpec.js

It was using `scrollIntoView` instead of `parent.scrollTo`. 
Easy to let get through when you're only running a single app on a page. Also the `scrollTo(options)` form doesn't work on Safari.

fix autoscrolling the log viewer dragging the page around

---

kbase-extension/static/kbase/js/kbaseNarrative.js

Resolves #1630 
Instead of refreshing the page (and getting a plain 502 error from traefik), this now redirects to the load-narrative.html page which will then poke the loading container until 502 resolves into something useful.

redirect to load-narrative.html after deleting session

---

nbextensions/appCell2/widgets/appCellWidget-fsm.js
nbextensions/appCell2/widgets/appCellWidget.js

fixes #1617
Job status is unavailable before the job starts, so disable that tab until the job actually starts (not in the Sending or Launching stages).

remove toggle to job status before job launches

---

src/biokbase/narrative/tests/test_widgetmanager.py
src/biokbase/narrative/widgetmanager.py

The error was in mapping workspace and object names to UPAs. They tried to lookup `None` as a valid object name.
Also updated some `str.format()` into newer style f-strings.

PTV-1446 - fix bug preventing KBaseFeatureValues viewer apps from working

---

Makefile
kbase-extension/static/kbase/js/api/auth.js
scripts/local-dev-run.sh
test/unit/spec/api/authSpec.js

Here are the changes to improve the cookie support.
The primary functional change is to make the configuration of cookies in auth.js carry specific cookie config info, separated test specs for zapping the narrative_session cookie and the backup cookie. The backup cookie testing also needs a spec targeting prod behavior, but that would require more changes since the testing is against localhost and the backup cookie is set for kbase.us.
Some minor changes to the tools I use for local narrative development in a container.
Since I couldn't fully test this, I performed manual confirmation using local kbase-ui and narrative proxied to respective kbase environments. 
Special setup was required:
- for narrative_session confirmation, the cookie is generated in next and narrative-dev; I chose next …

Fix cookies

---

kbase-extension/static/kbase/js/util/jobLogViewer.js

We don't need to sanitize HTML as it's being rendered as text anyway. Sanitizing just introduces odd characters.

use createTextNode to print logs

---

.github/dependabot.yml

Daily updates are a bit excessive starting out.

Updating Dependabot config to only check weekly.

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCellToolbarMenu.js
test/unit/spec/narrative_core/kbaseCellToolbarMenu-spec.js

This pull request makes an app cell status visible when the app cell is collapsed.
The unit tests test whether the status messages display in the toolbar menu depending on if the app cell is collapsed.

Fix SCT-2664: Show status when cells are collapsed

---

test/unit/karma.conf.js
test/unit/spec/appWidgets/infoTabSpec.js

This pull request is to demonstrate tests running on code within the `nbextensions` directory without radically changing the current configuration within the repo. Most of the tests currently are configured to evaluate code under the `kbase-extension/static` directory. There is a sizable amount of code which lives under the `nbextensions` directory, but it does not seem to be configured to be tested at present. This comprises about 7% of the codebase by lines of code, so it might make sense to move all the code from here into the other folder. Before I would seriously suggest that, however, I would like a little more context on why there is a split in the first place and make sure that the move is possible and desirable.
The coverage report from karma also does not seem to properly count …

Adding basic unit tests for app cell info tab.

---

Makefile
docs/developer/local-docker.md
kbase-extension/static/kbase/js/widgets/function_output/kbasePanGenome.js
scripts/local-dev-run.sh

Actually sorting by these columns triggers an error in the backend api -- they are simply not sortable.
This resolves PTV-1527, which is linked to several public tickets.
Also included in this PR are some minor changes to the local docker developer support.
PTV-1527 #comment fixes table sorting, removes sorting from affected columns

Removes sorting from two columns in the pangenome viewer - PTV-1527 #resolve

---

.eslintrc.yml
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/tabs/infoTab.js
test/unit/spec/appWidgets/infoTabSpec.js

This commit adjusts the app cell info tab according to user feedback related to #1652. It fixes some unit tests to test for what their spec says they are testing for, and includes some new tests. It updates some linter settings. Note that this PR changes the order of the info tab among other app cell tabs. This is not immediately obvious as JS did not always guarantee key order in objects, but now it does. Finally, it removes some instances of Bluebird in favor of the global built in Promise object.

Incorporated feedback on app cell info tab.

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCellToolbarMenu.js
test/unit/spec/narrative_core/kbaseCellToolbarMenu-spec.js

This PR relates to #1758 and takes a "less is more" attitude to the app cell status when minimized. Instead of using the long, and possibly dynamic, status message, it restricts statuses to Canceled, Error, Queued, Running, Success. This simplified approach allows the status messages to be styled more uniformly, increasing readability.

Incorporated feedback on minimized cell status

---

src/biokbase/narrative/appeditor.py
src/biokbase/narrative/tests/data/simple_display.yaml
src/biokbase/narrative/tests/test_appeditor.py

A long-standing issue with the in-narrative app spec editor is how it handles quotes in parameter descriptions. Or, more accurately, how it doesn't.
This was causing problems with how the cells are being generated. In the standard Narrative workflow, the app spec is directly put into the cell metadata, so as long as it's valid JSON, there's no problem. In the `generate_app_cell` function, the spec is "printed" into the Javascript parser directly, which causes some string parsing to be done. The result of this is that potentially invalid JSON (with the standard `\"` escaping of quotes) can be emitted, which causes the Javascript interpreter to fail.
This patch explicitly converts any double-quote `"` to `&quot;` and any single-quote `'` to `&apos;`, in parameter fields which is more html …

better handling for quotes in spec editor

---

kbase-extension/static/kbase/css/appCell.css
kbase-extension/static/kbase/js/widgets/appWidgets2/common.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/select2ObjectInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/select2ObjectView.js
test/unit/spec/appWidgets/commonSpec.js

Certain values are not as easy to copy and paste from within KBase app cells, and this PR trials a clipboard button to sequence input and view elements.
For select2 object inputs and views, this PR adds a clipboard icon to enable copying and pasting the value selected within the select2 widget.

Added clipboard functionality to select2 inputs.

---

nbextensions/codeCell/main.js

Code cells currently forget whether the user has decided to hide the code or not, but this PR alters the behavior so that this choice will be remembered.

Remove explicit forgetfulness of code cell state

---

kbase-extension/static/kbase/js/api/auth.js

Auth tests (and local dev environment behavior) were failing due to auth tokens being unable to be set in the headless Chrome environment. Auth tokens are set as cookies in the browser, and there was a recent Chrome update that requires that `samesite=none` and `secure` are both set. This allows cross-origin cookies to work.
However, the only case where cookies need to be cross-origin is in a development environment that's configured to run on localhost (i.e. the narrative URL is something like http://localhost:8888). This is also running unsecure (not https), so a `secure` cookie cannot be set. So, when running a test that tries to make an auth token, that would always fail. But since we only need to have cookies like that on localhost, and they'll only communicate at the top level, we …

Adjust how authentication cookies are set

---

README.md
docs/adrs/0001-git-workflow.md
docs/git-workflow.md

This PR updates the narrative repo documentation to reflect the recent git workflow ADR. I also added a table of contents to the readme. This required editing some of the readme headers to work properly with markdown.
https://kbase-jira.atlassian.net/browse/DATAUP-63

Update gitworkflow doc DATAUP-63

---

.github/pull_request_template.md
.pre-commit-config.yaml
README.md
docs/git-workflow.md

In order to ease the burden on devs to run flake8 and black on each commit, we have instructions on how to automatically run these linters now added into the readme, as well as a dev checklist item
It's possible we might need to update travis file if black changes it standards, and then the builds mysteriously start failing because of a new rule
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-164
``` 
* Install git precommit as per the instructions
* Attempt to check a file in
```

DATAUP-164 DATAUP-165 Update pull_request_template to reflect lint/black/precommit and add git precommit config

---

.github/workflows/build_truss_pr.yaml
.github/workflows/scripts/build_truss_pr.sh
.github/workflows/scripts/tag_truss_latest.sh
.github/workflows/tag_truss_latest.yaml
docs/deploy_narrative.md

* Adds several new configs and shell scripts that run via github actions to support a new narrative-truss image that is build from a branch named "truss". This is intended for testing on narrative-refactor.kbase.us
* We want to keep a parallel test/integration environment for the Truss bulk import/analysis work, instead of having to deploy into CI for testing.
* We may need some help from Jason Fillman for setting permissions in case we missed something. These edits were tested in the narrative-traefiker repo and worked properly.

DATAUP-128: First pass at adding support for a Truss tagged image build, based on branch named "truss"

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
kbase-extension/static/kbase/templates/data_staging/ftp_file_header.html

* Fixing an issue with the [previous PR](https://github.com/kbase/narrative/pull/1855) where the script to add ACL 
on line 170 of stagingAreaViewer.js wasn't getting triggered due to a class/element name mismatch 
https://kbase-jira.atlassian.net/browse/DATAUP-187
* Details for how to test the PR: I was able to confirm that the call to the ACL service is triggered by logging and checking in the console. However can't quite test fully on CI as the endpoint is disabled for security reasons. 
- [n/a] I have added tests that prove my fix is effective or that my feature works

Dataup187 move globus bug fix

---

kbase-extension/static/kbase/css/appCell.css
kbase-extension/static/kbase/css/batchMode.css
kbase-extension/static/kbase/css/bootstrapHelper.css
kbase-extension/static/kbase/css/buttons.css
kbase-extension/static/kbase/css/contigBrowserStyles.css
kbase-extension/static/kbase/css/kbaseEditor.css
kbase-extension/static/kbase/css/kbaseIcons.css
kbase-extension/static/kbase/css/kbaseJobLog.css
kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/css/kbaseNotify.css
kbase-extension/static/kbase/css/kbaseStylesheet.css
kbase-extension/static/kbase/css/kbaseTour.css
kbase-extension/static/kbase/css/landing-pages.css
kbase-extension/static/kbase/css/methodCell.css
kbase-extension/static/kbase/css/narrative.css
kbase-extension/static/kbase/css/widgets.css
kbase-extension/static/kbase/custom/custom.css
nbextensions/advancedViewCell/styles/main.css
nbextensions/appCell2/styles/main.css
nbextensions/editorCell/styles/main.css
nbextensions/editorCell/styles/old.css
nbextensions/viewCell/styles/main.css

Ran the [stylelint css formatter/linter](https://stylelint.io) over the codebase to enforce whitespace and formatting; stylelint is one of the code quality checks run by Codacy.
In addition to formatting the css, stylelint also identified a number of empty stanzas, which I removed.
https://kbase-jira.atlassian.net/browse/DATAUP-246

DATAUP-246: whitespace changes and reformatting of css files

---

kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/widgets/narrative_core/upload/fileUploadWidget.js
kbase-extension/static/kbase/templates/data_staging/dropped_file.html
kbase-extension/static/kbase/templates/data_staging/dropzone_area.html
src/config.json
test/unit/spec/narrative_core/upload/fileUploadWidget-spec.js

This PR creates a `clear all` button when a file upload to the dropzone errors. The clear all button will remove all errored files from the dropzone when clicked. It will not remove files that are still uploading. 
I talked to Mallory about the button positioning and she is fine with it's location given the scrolling functionality when there is more than a single errored file in the dropzone.
https://kbase-jira.atlassian.net/browse/DATAUP-213
To execute the unit tests, navigate to the narrative repo and enter `make test-frontend-unit`
To view this change locally, complete the following steps:
* Pull this branch
* Execute `kbase-narrative'
* Create a new narrative
* Navigate to the data import panel
* Drag and drop a file that is greater than 20 GB into …

Dataup 213 clear errors from staging

---

kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/templates/data_staging/ftp_file_header.html
test/unit/spec/narrative_core/upload/stagingAreaViewer-spec.js

This PR is to address the comments from Mallory: 
_"Was making the globus button text blue and underline on hover intentional? Was this to combat the a11y issue? If it was not intentional, can we style it so it matches the other button?
Can we add an 8px margin to this row so it has just a little bit more breathing room?"_
To address accessibility, I wrapped the button with an anchor tag and made the button non-keyboard navigable. This provides the benefit of the globus button looking correct while also maintaining typical link functionality with keyboard navigation and screen readers.  
https://kbase-jira.atlassian.net/browse/DATAUP-187
* Execute `make test-frontend-unit`
* To view the changes locally, execute `kbase-narrative`, open a new narrative, and navigate to the import panel. The …

DATAUP-187 Review edits

---

kbase-extension/static/kbase/css/appCell.css
kbase-extension/static/kbase/css/bootstrapHelper.css
kbase-extension/static/kbase/css/buttons.css
kbase-extension/static/kbase/css/kbaseJobLog.css
kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/css/kbaseNotify.css
kbase-extension/static/kbase/css/kbaseStylesheet.css
kbase-extension/static/kbase/css/landing-pages.css
kbase-extension/static/kbase/css/narrative.css
kbase-extension/static/kbase/custom/custom.css

NOTE: this is built on top of the whitespace changes made in #1872. When #1872 is merged, I will rebase this PR.
The changes made in this PR include:
- removing commented-out styles
- removing invalid css tags and values
- removing duplicated stanzas
- combining declarations spread over several lines
https://kbase-jira.atlassian.net/browse/DATAUP-246

DATAUP-246: CSS cleanup, pt II

---

kbase-extension/kbase_templates/notebook.html
kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/custom/custom.css

Fixing the placement of the icons for the "Add new cell" buttons.
Beautiful buttons now:
Looking good, huh?
Also fixed a padding problem was accidentally unleashed due to selector precedence and the ****** styles in the underlying jupyter notebook. Doh!
Note: base branch is set to DATAUP-246_css_to_css-error_pages (#1887) as it assumes the presence of changes in that PR.
https://kbase-jira.atlassian.net/browse/DATAUP-269

DATAUP-269: fix add new cell buttons

---

kbase-extension/kbase_templates/403.html
kbase-extension/kbase_templates/error.html
kbase-extension/kbase_templates/generic_error.html
kbase-extension/kbase_templates/notebook.html
kbase-extension/static/errorMain.js
kbase-extension/static/kbase/css/advancedViewCell.css
kbase-extension/static/kbase/css/errorPage.css
kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/custom/custom.css

Cleaning up error template pages and moving the css to a separate file
https://kbase-jira.atlassian.net/browse/DATAUP-246
... plus any others that you can generate!

DATAUP-246: error pages

---

kbase-extension/static/kbase/js/kbaseNarrative.js
test/unit/karma.conf.js
test/unit/spec/kbaseNarrativeSpec.js

This PR addresses some of the events that occur during Narrative startup. The startup process consists of 5 primary steps that are checked off of a tracking div, ending with the disappearance of that div.
There are two of these that are closely dependent on the kernel and what it's doing - these are checkbox 4 and 5 on the list. In the first kernel step, we try to make sure the connection between the FE and the Jupyter notebook kernel exists and is stable and ready for input. This is currently done by waiting for the `kernel_ready.Kernel` event to get fired. This happens when the kernel is connected and idle. This can be a problem if the kernel already exists and is busy, which can happen on a page reload. It's therefore possible for the kernel_ready.Kernel event to not be fired in any …

DATAUP-176 slow startup

---

kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/widgets/narrative_core/upload/fileUploadWidget.js
kbase-extension/static/kbase/templates/data_staging/dropped_file.html
src/config.json
test/unit/spec/narrative_core/upload/fileUploadWidget-spec.js

This PR alters the file row UI in the dropzone area. On success and error, the file row has been updated to reflect this figma mock: https://www.figma.com/file/zBQcHiLV4FlIkD3Y1ogNcy/concept-sketches2?node-id=13%3A153
https://kbase-jira.atlassian.net/browse/DATAUP-209
To test this PR, run the narrative locally and navigate to the staging area. Drop a file that is larger than the max file size (20). This will cause the file to error and you will be able to see the changes.
To view the successful file upload, you should see it flash briefly upon success. If you would like to view it for a longer period, open devtools and put a break point on line `108` in file `fileUploadWidget.js`.
A question I am currently asking Mallory: If the successful files are …

Dataup 209 fix error msg cutoff

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js

Came across a bug while working on another ticket, but I noticed that the stagingAreaViewer updateView() method gets called twice on our first load of the narrative. 
This is because it's being called via setPath in the init function on line 75 (of stagingAreaViewer), and then again via the narrativeStagingDataTab module when it first gets rendered and calls updateView() on line 97. 
It occurred to me that this could impact load times negatively so I put in a simple fix. Open to feedback on approach, just wanted to get something in. 
https://kbase-jira.atlassian.net/browse/DATAUP-301
You can set breakpoints or console statements where stagingArea.updateView is being called.

DATAUP-301 simple fix for loading staging

---

kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js

Came across this bug when testing out DATUP-224, if a user selects a file type and then goes to delete or upload another file the previously selected type(s) disappear and the dropdown is reset to “Select a type”
I was able to refactor stagingAreaViewer so that we are now saving the type if selected between renders. One of the parts of the refactor also included saving file name and data so that when data tables is rendering each column in the row it doesn't have to look it up every time. 
I also tangentially fixed an issue with hover states on the delete file button. 
https://kbase-jira.atlassian.net/browse/DATAUP-294 
* Checkout this branch
* Go to the import data tab
* Add at least one file and select the type for it
* Upload or delete another file
* The selected type should remain …

Dataup 294 save selected type

---

kbase-extension/kbase_templates/page.html
kbase-extension/static/kbase/js/tour.js
kbase-extension/static/kbase/js/util/jobLogViewer.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/uploadTour.js
nbextensions/advancedViewCell/main.js
nbextensions/appCell2/main.js
nbextensions/appCell2/widgets/tabs/status/logTab.js
nbextensions/editorCell/main.js
nbextensions/viewCell/main.js

Use a single file for all kbase css.
Removes dynamically-loaded kbase css from various widgets, and serves the `all_concat.css` file by default.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-246

DATAUP-246: css to scss: single file, please

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/fileUploadWidget.js
test/unit/spec/narrative_core/upload/fileUploadWidget-spec.js

This PR includes the following changes:
* Adds an on `canceled` event handler to the upload widget. When an upload is canceled, the file is deleted from the server. Before this change, canceled files would appear partially upload in the staging area. 
* Added a test to verify the `canceled` event was being emitted when a user clicks on the cancel button for a file
https://kbase-jira.atlassian.net/browse/DATAUP-295
Execute `make test-frontend-unit`
Navigate to the import tab, drop a file in the dropzone, cancel the file upload. You will not see the file appear in the staging area below.

DATAUP-295 cancel upload bug

---

RELEASE_NOTES.md
bower.json
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

Just updates the release notes to encompass all of the user-facing changes, and a few of the more major non-user-facing ones.
There's no real new features here (unless I'm forgetting something?), so this seems like a patch version change to me.

bump version to 4.3.1, add release notes

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeStagingDataTab.js

This fixes the issue of deleted file showing up temporarily in the staging area after the upload has been cancelled. Dropzone.js emits the 'complete' event when an upload is completed or stopped. This triggered the staging area to be refreshed before the canceled file was deleted; therefore it could be temporarily seen (if you refreshed again, the deleted file would no longer be in the staging area.). 
Now, refresh is not called when a file is canceled because there is no file being added to the staging area. 
https://kbase-jira.atlassian.net/browse/DATAUP-215
To test, navigate to the import tab. Upload a file, and cancel the upload before it completes. You should not see a file in the staging area.

DATAUP-215 file temporarily shows in staging area

---

nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/bulkImportCell/cellControlPanel.js
nbextensions/bulkImportCell/cellTabs.js
nbextensions/bulkImportCell/main.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

Convert the base `bulkImportCell` module to use the factory pattern.
It really only needs to expose the `make` function, other items are added to the factory result for help with testing and cell deletion if needed later.
This is on the same branch as other changes to #1954 , so there's some overlap until that gets merged, but I wanted to get this out there.
Really there should be no change - fire up the narrative and try out a bulk import cell, and run tests. Tests should all have been updated accordingly.

DATAUP-288 left column prep - factory pattern

---

nbextensions/bulkImportCell/bulkImportCell.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

Adds in the maximise / minimise JS for showing and hiding the bulk import cell contents.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-322

DATAUP-322: Adding cell minimize / maximize controls

---

scripts/install_narrative_docker.sh

The dockerfile version of the narrative installer included a list of which nbextensions to activate, instead of using the included nbextension installer file. This means that it was missing the new bulk import cell.
Now it just uses the installer as it should.
Running a narrative from a container should allow you to make a bulk import cell. No other changes.
(mostly not applicable in this case)

Use script to install extensions in dockerfile

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
nbextensions/advancedViewCell/widgets/advancedViewCellWidget.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/codeCell/main.js
nbextensions/editorCell/widgets/editors/readsSet/editor.js
nbextensions/viewCell/widgets/viewCellWidget.js
package-lock.json
package.json

Standardise the way that kbase cells refer to `user-settings`; for some reason, the code cell uses `userSettings`, whereas everywhere else uses `user-settings`.
Removes the annoying `pre-commit` module, which was forcing tests to be run whenever you tried to commit.
Also fixed an issue where someone had used a comma instead of a semi-colon, which eslint highlighted; the lines were of the form
```
alert('internal error'),  // COMMA!!
console.error('INTERNAL ERROR', err);
```
(there's no such thing as too much warning)
https://kbase-jira.atlassian.net/browse/DATAUP-322

DATAUP-322, min max cell: fix user settings

---

.eslintignore
.eslintrc.yml
.gitattributes
.prettierignore
.prettierrc.yaml
package-lock.json
package.json

This PR puts in place machinery and configs for prettier and eslint. This includes:
- prettier config
- updating eslint config so it does not clash with prettier
- adding prettier to the dev dependencies and removing `pre-commit`, which had somehow found its way back in
- updating the package-lock.json with the new versions
- adding a `.gitattributes` file to ensure that line endings are always unix style.

DATAUP-322: ESLint / Prettier: npm machinery

---

nbextensions/codeCell/main.js
test/unit/karma.conf.js
test/unit/mocks.js
test/unit/spec/nbextensions/bulkImportCell/main-spec.js
test/unit/spec/nbextensions/codeCell/main-spec.js

A previous PR standardised the way that we refer to `user-settings` in cell metadata. This ensures that saved narratives will have their cell metadata correctly reconstituted.
Added some basic `codeCell` tests and specific tests for the `userSettings` key in the kbase metadata.
Doing this as a separate PR so it doesn't get lost in the cell min/max stuff.
https://kbase-jira.atlassian.net/browse/DATAUP-322

DATAUP-322: fix user settings

---

nbextensions/bulkImportCell/bulkImportCell.js

Ensure that the initial cell min/max state is set properly. At present, the bulk upload cells are always expanded when a narrative opens; this corrects the situation so that they are only expanded if they were saved in that state.
https://kbase-jira.atlassian.net/browse/DATAUP-322

DATAUP-322: Ensure initial cell min/max state is set

---

.github/codecov.yml

Codecov has recently started to be obnoxiously noisy about what's tested or not in PRs. I admit this can be helpful, but IMO seeing a code coverage difference is enough, and the annotations clutter the file view of the PR, and they can only be disabled per file.
It's really annoying.
This PR adds a `codecov.yml` file that still keeps all the defaults, but disables that annotation as described here:
https://docs.codecov.io/docs/github-checks-beta#yaml-configuration-for-github-checks-and-codecov
N/A - no ticket. 
N/A - no tests needed, just a config update
N/A - no new code, just a config

make codecov chill out with its annotations

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStateList.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStateListRow.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTab.js

Adding in a link to view the logs, and making the log viewer panel non-collapsible so it's always shown.
new table appearance:
https://kbase-jira.atlassian.net/browse/DATAUP-313

adding 'view log' link to status table

---

kbase-extension/static/kbase/js/common/cellComponents/fieldTableCellWidget.js
kbase-extension/static/kbase/js/common/cellComponents/filePathWidget.js
kbase-extension/static/kbase/js/common/cellComponents/paramsWidget.js
test/unit/spec/common/cellComponents/fieldTableCellWidget-Spec.js
test/unit/spec/common/cellComponents/filePathWidget-Spec.js

* This PR is to fix tests for the file input widget and field table cell widget which were failing previously after some updates. 
* In the process of fixing the tests themselves I found some issues with promise resolution so I cleaned that up a bit. 
* I am still seeing intermittent issues with some of the tests where we get warnings about not being able to set "innerHTML" or retrieve "getAuthToken" when trying to initialize the widgets. I am not clear on what's going on here, I've tried troubleshooting to no avail and it doesn't seem to have an impact on the tests actually succeeding so not sure if it's a karma synchronicity red herring or what. If anyone has input or advice I would love to pair on this. 
https://kbase-jira.atlassian.net/browse/DATAUP-365
* Details for how to test the …

Dataup 365 test fix

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/results/outputWidget.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/results/reportWidget.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/results/resultsTab.js
nbextensions/bulkImportCell/bulkImportCell.js
test/unit/spec/common/cellComponents/tabs/results-spec.js

* This is the initial implementation of the results tab, which includes the output objects and report widget. For now they have data sent to them but display nothing. I didn't dig deep enough into the code to ensure the right data was making it to each place, just wanted to get something in there to make sure all the plumbing was working as expected. 
I wrote some fast tests for the results tab, but nothing for reports or output yet as I wanted to keep the scope of this small. 
https://kbase-jira.atlassian.net/browse/DATAUP-369

Dataup 369 results container

---

kbase-extension/static/kbase/config/staging_upload.json

* This adds the correct UIs for the additional FASTQ/SRA apps, instead of all using one UI
* This hooks up the decompress app
* Spin up a local narrative and press the uploads in staging.. You might have to update narrative/kbase-extension/static/kbase/js/util/kbaseApiUtil.js to use dev instead of prod
* Test on CI (Once they are released in https://github.com/kbaseapps/kb_uploadmethods/pull/310)

DATAUP-331 DATAUP-265 Add additional apps to dropdown

---

.github/pull_request_template.md

* Updating the PR template to be in sync with the truss branch template, and to correct the URL for the reference website
- [-] I have added tests that prove my fix is effective or that my feature works

Updating PR template with trussresources site URL

---

kbase-extension/kbase_templates/403.html
kbase-extension/kbase_templates/error.html
kbase-extension/kbase_templates/generic_error.html

Remove mentions in the page templates to `errorPage.css` and put the css declarations in the files themselves (only one line, so no point in maintaining a file).
I thought I had already made this change in another PR, but perhaps it got accidentally undone? Anyway.

DATAUP-322: Remove errorPage.css

---

RELEASE_NOTES.md
kbase-extension/kbase_templates/narrative_header.html

A tiny PR to change the "dashboard" link to go to the new "narratives" path.
Just a little cleanup that needs to be done before staging the release.

change hamburger menu link to 'narratives'

---

RELEASE_NOTES.md
bower.json
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

Freeze a new version at 4.3.2.
This can probably wait until a few pending PRs get worked out, as those will have an impact on the released product, mainly #1959, #2076, and #2088.
- N/A Added the Jira Ticket to the title of the PR (e.g. `DATAUP-69 Adds a PR template`)
* Details for how to test the PR: N/A - just version change
no code changes

Version bump to 4.3.2

---

package.json
test/unit/run_tests.py
test/unit/test-main.js

This is the first of probably many PRs around fixing the frontend unit tests. See the ticket linked below for further details.
This simply ports the recent change to the truss branch that sidesteps using `grunt` and `grunt-karma` to start the test suite. The way grunt captures logs can lead to some false errors. See this PR for more info: https://github.com/kbase/narrative/pull/2110
Practically, this doesn't change the experience of running tests, just how they get started.
There's also a little modernization to the `test-main.js` startup script.
running `make test` or `make test-frontend-unit` will still work.
Alternately, start a local headless narrative on port 32323 with:
```
kbase-narrative …
```

DATAUP-330 port removal of grunt test from truss branch

---

kbase-extension/static/kbase/js/widgets/appInfoPanel.js
test/unit/spec/appWidgets/infoPanelSpec.js

Fixes the tests (and the module) for the app info panel popup. This is the popup that appears with app info when clicking the ellipsis menu in app cells (NOT the "info" tab, which has its own tests).
* The tests weren't mocked and made calls to NMS and Catalog that could fail and cause a false failure of the unit tests.
* The module was using Promises improperly (well, inefficiently) and needed a little modernization.
Viewing the popup should work just the same as before.

DATAUP-330 fix app info panel widget and tests

---

test/unit/spec/api/authSpec.js

This changes the auth api tests so that their calls to the auth service are mocked.
I understand there's issues with this pattern. If the auth service changes, then the tests are invalid. I argue that this is why we also have integration tests - the unit tests should test that the Javascript API code works as expected.
The main fixes here are as per other tests - fix how we handle Promises in Jasmine, and remove the necessity for making network calls.
Just run the tests! The auth api wasn't touched, so nothing should be different in the Narrative.

DATAUP-330 fix auth tests

---

kbase-extension/static/kbase/js/narrativeLogin.js
kbase-extension/static/kbase/js/userMenu.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppPanel.js
test/unit/karma.conf.js
test/unit/mocks.js
test/unit/spec/kbaseNarrativeSpec.js
test/unit/spec/narrativeLoginSpec.js
test/unit/spec/narrative_core/kbaseNarrativeAppPanel-spec.js
test/unit/spec/userMenuSpec.js
test/unit/test-main.js

This rewrites the tests for the narrativeLogin module to handle promises properly, and mock out calls to the auth service.
This also exposes the clearTokenCheckTimers function from that module. Without this, there's no way to clear the timers, and they seem to just go off anyway during the remainder of the test suite. This would cause, among other things, a redirect to the logout page if tests run for too long. 
That redirection is something that's definitely one of the causes of our test miseries, and having a tighter control on how that happens is necessary.
Yet again, there should be no visible narrative changes. The only actual code change is to expose that interval clearing function, and it's only …

DATAUP-330 fix narrativeLogin tests, add a cleanup function to narrativeLogin

---

.github/workflows/test.yml
Dockerfile
narrbase-image/Dockerfile
scripts/build_narrative_container.sh

Narrative builds were failing due to the version of node installed on the base image. This PR updates the `narrbase` image to use the current nodejs release. In addition, the docker file commands are concatenated to reduce the number of layers in the resulting docker images.
Note that the 'Build' workflow requires `kbase/narrbase:6.2` to be present on ghcr.io.
- [] I have added tests that prove my fix is effective or that my feature works

DATAUP-330: Update docker image nodejs

---

.github/workflows/scripts/build_prodrc_pr.sh
.github/workflows/scripts/build_test_pr.sh
.github/workflows/scripts/tag_prod_latest.sh
.github/workflows/scripts/tag_test_latest.sh

* The narrative_version container is not being built/pushed by the GHA, this is a fork with updates to test GHA builds for the additional image
No jira ticket on this one.

Changes to get the narrative_version container built/pushed

---

kbase-extension/static/kbase/js/common/errorDisplay.js
kbase-extension/static/kbase/js/common/jobs.js
package-lock.json
test/unit/spec/common/errorDisplay-Spec.js

Building on work previously done in this ticket, I've added code to transform for display another error type that I have seen regularly whilst working on the bulk import cell.
Also included a try/catch around code that converts old-style jobState objects into the newer format to avoid throwing errors if the jobState structure is not as expected.
Updating the `caniuse-lite` package in package-lock.json.

DATAUP-314: adding a new error type

---

kbase-extension/static/kbase/js/common/cellComponents/actionButtons.js
kbase-extension/static/kbase/js/common/cellComponents/fieldTableCellWidget.js
kbase-extension/static/kbase/js/common/cellComponents/filePathWidget.js
kbase-extension/static/kbase/js/common/cellComponents/paramsWidget.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/infoTab.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/results/outputWidget.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/results/reportWidget.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/results/resultsTab.js
test/unit/spec/common/cellComponents/fieldTableCellWidget-Spec.js
test/unit/spec/common/cellComponents/filePathWidget-Spec.js
test/unit/spec/common/cellComponents/paramsWidget-Spec.js
test/unit/spec/common/cellComponents/tabs/infoTab-Spec.js
test/unit/spec/common/cellComponents/tabs/results/outputWidget-spec.js
test/unit/spec/common/cellComponents/tabs/results/results-spec.js

Prior to looking at test failures in the `truss` branch, I have applied standardised formatting to component files and formatting and variable naming to the test files.
- Ran eslint and prettier on files in `/static/kbase/js/common/cellComponents/` and `test/unit/spec/common/cellComponents/`
- In test files, named the objects produced by each module `<module_name>Instance`

DATAUP-330: eslint, formatting, and variable name standardisation

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/common/html.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePanel.js
test/integration/specs/kbaseNarrativeDataPanel_test.js
test/integration/specs/kbaseNarrativeSidePanel_test.js
test/unit/spec/common/html-Spec.js
test/unit/spec/narrative_core/kbaseNarrativeAppPanel-spec.js

This set of changes relates to and is motivated by PTV-1635, which relates to the slideout refusing to close. The issue being fixed is that the button to open the app slideout did not change when the slideout opened, closing the slideout via clicking on the background did not either, and switching between the app and data slideout was visually rough and inconsistent.
The primary means to open the data and app slideout is via the small right-arrow buttons in the data and app side panels. These arrows should switch to a left-pointing arrow when the associated slideout is open. The data slideout button worked correctly, some of the time, and the app slideout button never changed direction. Sometimes the data slideout button would get reversed (due to closing actions which did not affect the …

PTV-1635: improve app and data slideout button and opening behavior

---

kbase-extension/static/kbase/js/widgets/narrative_core/jobCommChannel.js
test/unit/spec/narrative_core/jobCommChannel-spec.js

Fix timeout and async issues with the jobCommChannel tests. This essentially replaces any roundabout tests that make and use a Bus with a mock for the bus that tests that we send what we expect to send. 

DATAUP-330 fix jobCommChannel tests

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppPanel.js
test/unit/spec/narrative_core/kbaseNarrativeAppPanel-spec.js

A bug was introduced that prevented apps from being added to the main working area when clicking on an app name, this fixes that bug and adds a unit test around it.
I couldn't get integration tests to run with any local stability - my internet connection is kinda horrid, and juggling timeouts doesn't seem to help. I'd appreciate a little help with this, or we can put it aside for now.
- ~Added the Jira Ticket to the title of the PR (e.g. `DATAUP-69 Adds a PR template`)~
No ticket for this one, was a blocking bug that got introduced in CI.
Open a narrative, try to click on any app - if it loads the proper cell, it works!
Skipping release notes update - this bug is in CI, and won't be seen by users. …

Fix app panel

---

test/unit/karma.conf.js
test/unit/spec/dynamicTableSpec.js
test/unit/spec/loadingWidgetSpec.js

Adding expectations to tests which were not testing things adequately, and disabling some empty tests.

DATAUP-330: Fixing empty specs in the dynamicTable and loadingWidget tests

---

test/unit/spec/common/validate-Spec.js

port of the content of the validate-spec.js test from PR #2151 , since that branch has been used for other purposes

DATAUP-330: restore validate test from #2151

---

test/unit/spec/nbextensions/appCell2/widgets/appCellWidget-spec.js

Skipping three app cell widget tests that have no expectations. They can be filled in at some mythical later date.

DATAUP-330: skip tests with no expectations

---

Gruntfile.js

Not having cache-busting has bit us hard in the past. Even with modern browsers, this ensures the latest bundle is loaded.
- no ticket for this one
- run the build, `notebook.html` should load `kbase-narrative-min.js?cb=asdfasdf`
- loading the narrative at this point should work seamlessly

add cache busting to minified bundle load

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/checkboxInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/floatInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/intInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/select2ObjectInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/taxonomyRefInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/inputUtils.js
kbase-extension/static/kbase/js/widgets/appWidgets2/validators/float.js
kbase-extension/static/kbase/js/widgets/appWidgets2/validators/int.js
test/unit/spec/appWidgets/input/checkboxInputSpec.js
test/unit/spec/appWidgets/input/dynamicDropdownInputSpec.js
test/unit/spec/appWidgets/input/floatInputSpec.js
test/unit/spec/appWidgets/input/intInputSpec.js
test/unit/spec/appWidgets/input/newObjectInputSpec.js
test/unit/spec/appWidgets/input/select2ObjectinputSpec.js
test/unit/spec/appWidgets/input/selectInputSpec.js
test/unit/spec/appWidgets/input/subdataInputSpec.js
test/unit/spec/appWidgets/input/taxonomyRefInputSpec.js
test/unit/spec/appWidgets/input/textInputSpec.js
test/unit/spec/appWidgets/input/textareaInputSpec.js
test/unit/spec/appWidgets/input/toggleButtonInputSpec.js
test/unit/spec/appWidgets/input/undefinedInputSpec.js

Continuing the fun theme of test fixes, this is a set of fixes to tests in the following directories:
- `test/unit/spec/appWidgets/input/`
This fixes tests where there were no expectations and adds in more stringent tests where the existing test was a bit meh.
I have removed some files from the original PR so some of the comments are outdated. I've marked them as resolved.
See inline comments for the details.
This has the prettier branch as the base branch to avoid all the reformatting crud.

DATAUP-330: Edits to the appWidgets and unit tests

---

.github/dependabot.yml

Set as monthly checks instead of weekly checks, as the signal-noise ratio is getting to be excessive.
Based on request from @sychan & @briehl.

Set dependabot alerts to check monthly

---

test/integration/specs/kbaseNarrativeDataPanel_test.js

There was a faulty selector in an integration test, that's not valid on the truss branch.
N/A - just changed a selector.

DATAUP-330 fix integration test selector

---

test/unit/karma.conf.js
test/unit/test-main.js

I noticed a couple of minor things with the test runner.
1. There's a series of "no timestamp available for..." errors for data files under the `/test/` directory.
2. The `test-main.js` file was letting a number of non-test js files through the filter, namely `parameterSpec.js` and `spec.js` - these likely weren't doing any harm as they don't have any test specs, but they don't need to be loaded, either.
This fixes both of those.
Run the tests - shouldn't see "no timestamp" errors for the test data files.

Tweak test runner

---

.github/workflows/scripts/build_prodrc_pr.sh
.github/workflows/scripts/build_test_pr.sh
.github/workflows/scripts/tag_prod_latest.sh
.github/workflows/scripts/tag_test_latest.sh

The narrative_version image build is working for the develop branch, but the new build scripts were never merged all the way into master, so there isn't an up to date narrative_version image built. This bit us this morning when we restarted rancher and it ended up refreshing the narrative_version image with the old version number.
This PR recreates the edits in the narrative_version branch, so that we can get a proper narrative_version built without pulling in all of the rest of the commits in develop.

Independently merge narrative_version build into master

---

package-lock.json
package.json
test/unit/karma.conf.js
test/unit/spec/narrative_core/kbaseNarrativeStagingDataTab-spec.js
test/unit/spec/narrative_core/upload/fileUploadWidget-spec.js

Some quick patches to prevent tests from calling CI.

DATAUP-330: Prevent widgets from calling external resources during tests

---

kbase-extension/static/kbase/js/common/props.js
kbase-extension/static/kbase/js/common/runtime.js
test/unit/spec/common/runtime-spec.js

I wanted to pass params to `monoBus.js`, but there is no way to do so at present. Adding a `config` arg to `runtime.js` solved that little issue. Since there were no tests for the runtime, I added some in.

DATAUP-314: Adding tests for runtime.js

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStateListRow.js
kbase-extension/static/kbase/js/common/errorDisplay.js
kbase-extension/static/kbase/js/common/jobs.js
test/data/jobsData.js
test/unit/spec/common/errorDisplay-Spec.js
test/unit/spec/common/jobsSpec.js

Adding in the type of error to the status row, as in the diagram:

DATAUP-314: add error type to the job status row

---

kbase-extension/static/kbase/js/common/jobs.js
nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/bulkImportCell/jobsData.js
test/data/jobsData.js
test/unit/spec/common/cellTabs-spec.js
test/unit/spec/common/jobsSpec.js

This PR adds in the job status line for batch cells.

DATAUP-314: Batch job status line

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js
test/unit/spec/common/cellComponents/tabs/results/reportWidget-spec.js

This fixes a few tests so that workspace and service wizard calls are properly mocked. They don't actually need to be called (i.e., we don't need any real data), but they're getting invoked over the course of the tests, so that needs to be prevented to deal with timeout issues.
Done as part of the followup to DATAUP-360

DATAUP-360 reports table tests

---

kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/kbaseNarrativePrestart.js
kbase-extension/static/kbase/js/util/bootstrapDialog.js
test/unit/spec/common/monoBus-Spec.js
test/unit/spec/function_output/kbaseSampleSet-spec.js
test/unit/spec/kbaseNarrativeSpec.js
test/unit/spec/narrativeLoginSpec.js
test/unit/spec/userMenuSpec.js
test/unit/spec/util/BootstrapDialogSpec.js

Preventing tests from leaving modals cluttering up the DOM.
A few eslint fixes that I noticed whilst working on these test files.
Codacy has failed, but everything else has passed.

DATAUP-314: test modal elimination II

---

nbextensions/bulkImportCell/main.js
test/unit/spec/narrative_core/jobCommChannel-spec.js
test/unit/spec/nbextensions/bulkImportCell/main-spec.js

More modals eliminated!
Integration tests timed out, but unit tests have passed.

DATAUP-314: test modal elimination III

---

docs/testing/testing.md
package-lock.json
package.json
test/unit/spec/narrative_core/kbaseNarrativeWorkspace-spec.js

- update jasmine to v3.7.1
- fix occasional kbaseNarrativeWorkspace widget test failures due to DOM elements not appearing quickly enough.
Integration tests timed out in both runs; frontend tests are fine.

DATAUP-314: test timeout fix

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/infoTab.js
kbase-extension/static/kbase/js/common/spec.js
nbextensions/bulkImportCell/tabs/configure.js
test/unit/spec/common/cellComponents/tabs/infoTab-Spec.js

The infoTab wasn't removing itself from the DOM properly. This wasn't an issue in the single-app appCell, due to how it removes and replaces its widget container, but is in the bulk import cell. There's likely something that can be streamlined there, too, but we've mostly been rolling with the concept that widgets that have `stop()` called on them should remove themselves from the DOM where appropriate. So, now it does.
- not really a JIRA issue, just a thing I noticed.
* toggling back and forth from the info tab in the bulk import cell should completely detach it / rebuild it now.

fix issue with infotab not removing itself completely

---

.github/workflows/scripts/build_prodrc_pr.sh
Dockerfile2

The narrative_version that was built and pushed by GHA has an old version number 4.2.0 for some reason, might be an issue with when the feature branch was branched off and merged back in versus when the most recent merge of develop into master occurred. Debugging it with a print during the build.

Debug issue with narrative_version

---

src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_appmanager.py

This is PR 1 of ~3 for adding the `run_app_bulk` method to `biokbase.narrative.jobs.appmanager`.
There were some... issues with that old module. 
1. There's a fair amount of duplicated code. This takes the first step of taking the wrappers around each app running style and turning that into a decorator. Now, instead of `run_app` calling `_run_app_internal`, where `run_app` would just catch and reformat errors for Narrative consumption, this uses a single decorator that applies to each function. It still follows the idiom of sending errors as comm messages to the front end as well as printing a prettier form of error message (which would go under the cell). I applied this only to `run_app` and `run_app_batch` as there are no tests for `run_local_app` right now, and I don't want to make any …

DATAUP-312 update appmanager tests, first step toward deduplication

---

src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/tests/test.cfg
src/biokbase/narrative/tests/test_appmanager.py

This little gap was a bit unacceptable. Should cover the appropriate test and error cases.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-312

DATAUP-312 add run_local_app tests

---

docs/design/job_architecture.md
kbase-extension/static/kbase/js/common/jobManager.js
kbase-extension/static/kbase/js/util/jobLogViewer.js
kbase-extension/static/kbase/js/widgets/narrative_core/jobCommChannel.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/narrative_core/jobCommChannel-spec.js
test/unit/spec/util/jobLogViewerSpec.js

The first commit contains some sonarcloud issues from DATAUP-379 that I fixed and accidentally committed into the wrong branch.
The second commit alters the `jobCommChannel` module to accept an array of job IDs so that action can occur on multiple jobs without requiring so many messages to the server. The backend will need to be updated appropriately.
I also renamed one of the message types to make the naming more consistent.
Whilst exploring this ticket, I found there are a number of messages that get sent out by the jobCommChannel but get ignored as there are no listeners. At some point this sad state of affairs should be rectified.
Surprise, surprise, frontend integration tests are still failing.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-315

DATAUP-315: batch cancel call

---

package-lock.json
package.json

Integration tests are all failing hard due to an out of date chromedriver. And dependabot is only doing v 89, and those are failing, too.

Bump chromedriver to ^90.0.0

---

src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test_jobmanager.py

Make copies of looked-up job states in jm.list_jobs() so that when they are modified, they don't affect the next lookup. 
- [n/a] Tests pass locally and in GitHub Actions
- [?] My code follows the guidelines at https://sites.google.com/lbl.gov/trussresources/home?authuser=0
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [n/a] [Release …

DATAUP-428 allow jobs to be listed more than once

---

nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/bulkImportCell/bulkImportCellStates.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

This is one of the final tasks for getting the jobs to start - getting the cell to know that's there's new job ids.
There's two possible events to listen for from the kernel-side app startup.
* `launched_job_batch` will have the new parent and child job ids, which will get registered with the cell's JobManager.
* `error` which happens if the job batch fails to start. What to do with the errors will get fleshed out in another PR, just to keep this one tidy.
This also fixes an issue where, on startup, the cell would only go into `editingComplete` or `editingIncomplete` as those were responses to the state of the various input widgets. Now it politely ignores those state change requests if the cell's already running.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-312
* Details for how …

DATAUP-312 run-status event listener

---

src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/tests/test_jobcomm.py

The front end was modified to be able to send job comm requests to the kernel with a `job_id_list` field instead of `job_id`. This can be handled at `JobComm._handle_comm_message` by detecting whether there is a `job_id_list` field, and if so, split that request into multiple requests with a `job_id`. Similarly to before, these requests are then wrapped in a `JobRequest` class, and delegated to the appropriate method.
- [n/a] Tests pass locally and in GitHub Actions
- [n/a] I have made corresponding changes to the documentation
- [n/a] (JavaScript) I have run Prettier and ESLint on changed code manually or with a git …

DATAUP-315 batch cancel BE

---

kbase-extension/static/kbase/js/common/busEventManager.js
kbase-extension/static/kbase/js/common/jobManager.js
nbextensions/bulkImportCell/bulkImportCell.js
test/data/testAppObj.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

Makes the Cancel button actually work and do stuff. It will:
* cancel the launching job state (which, incidentally, orphans the jobs it would have otherwise started. Not sure how to fix that yet)
* cancel all running jobs that it knows about
* return the cell to the editing state.
https://kbase-jira.atlassian.net/browse/DATAUP-312
* start a bulk import job and hit the cancel button. It should work and return to the ready-to-run state.

DATAUP-312 connect cancel button

---

docs/design/job_architecture.md
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/tests/test_jobcomm.py

When the browser requests a `job_status` from the kernel, the kernel currently responds with `job_does_not_exist` when the `job_id` is not associated with the current narrative. This PR changes the kernel to also respond with a `job_status` with a `status` of `does_not_exist`, "also" because the front end has not been altered yet. This new response message is actually sent after the current `job_does_not_exist` response message, because the testing scheme only tests the last message sent over the job comm channel.
- [n/a] Tests pass locally and in GitHub Actions
- [n/a] Any dependent changes have been merged and …

DATAUP-438 kernel responds with job_status message type with does_not_exist status

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/dynamicDropdownInput.js

Dynamic dropdown inputs - even optional ones - were previously unclearable. If you set a value, you'd have to make a whole new app cell to get an empty one.
This activates the `allowClear` select2 option and wires various events up.
no ticket on this one, yet.

let dynamic dropdown inputs be clearable

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/results/resultsTab.js
test/data/jobsData.js

As part of the BE connection, fix the report tab - it was using some job status keys that were there in the early test data, but don't exist in live data. Namely, the job status `result` key is really under `job_output.result`.
https://kbase-jira.atlassian.net/browse/DATAUP-312
- [n/a] I have added tests that prove my fix is effective or that my feature works

DATAUP-312 Fix report tab

---

.gitignore
.prettierignore
RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/publicDataSources/search2DataSource.js
test/.eslintrc.yml
test/integration/specs/kbaseNarrativeSidePublicTab_test.js

Modifies the query backing the refseq public data panel so that searches are conducted against the scientific_name, genome_id, and source_id fields. The match is an ES version of "or", so that a match on any one of these fields will succeed.
Previously only scientific_name was considered.
genome_id,  shown. as "KBase ID", is the refseq assembly accession number, and source_id is the ncbi project accession number.
Integration tests added for searching a value in these new fields.
This request was originally from Shane, who adds:
FYI.  This search change is actually related to a message we want to send out to users that had corrupt Euk genomes.  With out this fix it is …

Implement SCT-3038 refseq public data also search by genome_id and source_id

---

kbase-extension/static/kbase/js/common/cellComponents/filePathWidget.js
kbase-extension/static/kbase/js/common/cellComponents/paramsWidget.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/dynamicDropdownView.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/newObjectView.js
nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/bulkImportCell/tabs/configure.js
test/unit/spec/common/cellComponents/filePathWidget-Spec.js
test/unit/spec/common/cellComponents/paramsWidget-Spec.js
test/unit/spec/nbextensions/bulkImportCell/tabs/configure-spec.js

Implements the "View Configure" tab that appears while jobs are running / completed.
Really, all that happens here is this creates a mode switch for the configure, file path, and params widgets. Default is "edit" mode, with "view" mode as an option when the flag is set. The only real difference is that "view" mode uses the `view` variant of the input widgets.
There's a couple of those widgets identified here that don't really play as expected. I suspect there are others, but these fixes fill the need at the moment. I'm sure there's be a bugfix jamboree at some point...
https://kbase-jira.atlassian.net/browse/DATAUP-449
* get a running bulk import cell, and click on "View Configure", this should show up with read only / disabled versions of all of the …

DATAUP-449 add view configure mode for bulk import cells

---

kbase-extension/static/kbase/js/common/cellComponents/filePathWidget.js
nbextensions/bulkImportCell/bulkImportCell.js

This fixes a new bug where the object name input wasn't showing up in the file path widget. It was missing an event that should've been moved, but was just deleted.
Also deletes the `DefaultWidget` from the `bulkImportCell`. No more defaults, now we have something to fit everywhere!
* For FASTQ uploader types, the output object name field should appear now.

replace missing code, remove old code

---

.github/workflows/integration_test.yml
.github/workflows/unit_test.yml

Separates the test actions into unit test and integration test runs, so they can be more easily checked to see what passes and what fails. It maybe makes things take a little longer as the app has to get built multiple times, but I think it'll be helpful for seeing at a glance what's failing.
This came up from seeing a new batch of `dependabot` PRs which all failed miserably. This is really due to `dependabot` using a separate fork for submitting PRs - so another option might be to have the integration tests skip / fail immediately if there's no token available. Right now, they continue and just time out all over the place as they're running tokenless. The unit tests should be fine without authentication, and in fact, that's preferred. …

split test functions in gha

---

.coveragerc
.github/workflows/unit_test.yml
.prettierignore
Makefile
RELEASE_NOTES.md
docs/testing/testing.md
narrbase-image/conda-requirements/base
scripts/narrative_backend_tests.sh
src/biokbase/narrative/common/kblogging.py
src/biokbase/narrative/common/log_proxy.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_app_util.py
src/biokbase/narrative/tests/test_appeditor.py
src/biokbase/narrative/tests/test_appmanager.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py
src/biokbase/narrative/tests/test_logging.py
src/biokbase/narrative/tests/test_narrativeio.py
src/biokbase/narrative/tests/test_updater.py
src/biokbase/narrative/tests/test_user_service.py
src/biokbase/narrative/tests/test_viewers.py
src/biokbase/narrative/tests/test_widgetmanager.py
src/biokbase/narrative/tests/util.py
src/requirements.txt

The original motivation for this PR was found in the previous PR #2321 - Python code unit test coverage wasn't properly being uploaded to codecov. After a little poking, it seems that it's not being generated properly. Should be easy enough. I was also inspired to look at moving from nose to pytest at the same time.
So this is the first step (of likely many, TBA) in updating the Python test stack to be a little more modern. Nose is an ancient way of running Python tests. It has served us well, but it is long past time to move on. https://nose.readthedocs.io/en/latest/
Pytest is a framework that's used more commonly in the Python world, and at KBase in other projects. It has good support for test fixtures and mocking, and is under active community support. Best of all, it's basically a …

Move from nosetest to pytest

---

src/config.json
src/config.json.templ

The EE2 endpoint in the narrative-refactor config is pointing at the wrong place! 😱 

fix ee2 endpoint

---

docs/design/job_architecture.md
src/biokbase/narrative/exception_util.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

Backend hookup for batch retry.
Only the EE2 `retry_jobs` endpoint is used now, and `retry_job` is not used anymore. So the communication is adapted to be done in the plural. This means that requests that come in with request type `retry_job` and data `job_id` are converted to use `job_id_list`. Also, this endpoint always sends the resulting `new_job` comm message with data `job_id_list`, and the resulting `jobs_retried` message with data being a list of objects containing `job_id` and `retry_id`. In addition,  message types `job_does_not_exist` and `job_comm_error` also can use `job_id_list` now. 
* Details for how to test the PR: Run `make test-backend`. Or, spin up local narrative, import some files with the bulk import cell, cancel …

DATAUP-328 Batch Retry BE Hookup

---

src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_appmanager.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py
src/biokbase/narrative/tests/test_narrativeio.py
src/biokbase/narrative/tests/util.py

Makes sure that the parent job ID gets saved as part of the job object by the narrative backend
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-462

DATAUP-462: get parent job

---

nbextensions/bulkImportCell/tabs/configure.js

When a bulk import cell is in a ready to run state, and a user makes a change to some parameter, it wasn't always updating the code. This forces the message to get passed from the configure tab to the main widget every time a parameter changes, not just when it changes state from ready <-> not ready. This will trigger the code generator as appropriate.
no ticket - this was a quick response to a finding on Slack.
* Make a new bulk import cell, open the show code area, get it in the editingComplete state (run button's active)
* This should now show the code that'll execute.
* Make a change, especially to a …

Update code promptly

---

src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_jobmanager.py

Adding `cancel_jobs` method to job manager and updating tests

DATAUP-463: Adding cancel jobs (plural) method to the job manager

---

src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

Added a new function to deduplication job IDs in a list, removing any None or '' values first.
Also made some generic fixes, like swapping out repeated strings for constants and updating method docs
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-463

DATAUP-463: job manager job ID deduplication

---

kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidget.js
kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidgetCompact.js
kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidgetMicro.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/selectInput.js
test/unit/spec/appWidgets/input/selectInputSpec.js
test/unit/spec/narrative_core/upload/stagingAreaViewer-spec.js

Change the select input dropdown to use select 2 for app cells and bulk import cells.
This is the first step to finishing DATAUP-452. Now all dropdowns should make use of the select2 widget styling and should look and behave consistently. This has a couple typo and missing style fixes as well.
https://kbase-jira.atlassian.net/browse/DATAUP-500
https://kbase-jira.atlassian.net/browse/DATAUP-452
Details for how to test the PR manually
1. Open a new bulk import cell with FASTQ reads (for example)
2. Scroll down to the Sequencing Technology parameter. It should use select2 styling instead of browser standards. It should also have a little x to delete on the right side.
3. Open a standard app with a dropdown input and do the same (like MEGAHIT)

DATAUP-500 (DATAUP-452 part 1) update selectInput to use select2

---

kbase-extension/static/kbase/js/common/cellComponents/fieldTableCellWidget.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/selectInput.js
test/unit/spec/appWidgets/input/selectInputSpec.js

This alters the selectInput widget in the following ways
1. Adds an optional `availableValues` config option, which, if present, overrides the values taken from the constant spec.
2. Adds an optional `disabledValues` config, which disables any of the set values on startup.
3. Adds the `disable-values` and `enable-values` messages, which each take an Array of value strings. If any are present in the dropdown they'll be disabled/enabled. If any of those are the currently selected value, it stays enabled until the user selects a separate option. It doesn't seem to make sense to disable the selected value.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-500
* Nothing really obviously user-facing yet - commands will be included in the next PR.

DATAUP-500 Add messages to enable/disable options in select input

---

docs/design/job_architecture.md
kbase-extension/static/kbase/js/util/jobLogViewer.js
kbase-extension/static/kbase/js/widgets/narrative_core/jobCommChannel.js
package-lock.json
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_jobcomm.py
test/unit/run_tests.py
test/unit/spec/narrative_core/jobCommChannel-spec.js
test/unit/spec/util/jobLogViewerSpec.js

Simplifies the frontend by removing the 'request-job-log-latest' message channel and use 'request-job-log' with an option instead.
The python parts were taken from a branch that @n1mus worked on.
Update docs and tests.
Narrative frontend unit tests are failing. 😢 
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-437
* view the log of a job that has been completed
* run a job and view the logs
* stop the logs and restart them

DATAUP-437: remove 'request-job-log-latest', use 'request-job-log' instead

---

kbase-extension/static/kbase/js/common/jobManager.js
kbase-extension/static/kbase/js/widgets/narrative_core/jobCommChannel.js
package-lock.json
src/biokbase/narrative/jobs/appmanager.py
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/narrative_core/jobCommChannel-spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

* Switch front and backend over to using "batch id" instead of "parent_job_id" to refer to the batch job parent
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-512

DATAUP-512: use batch_id instead of parent_job_id

---

src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_jobmanager.py

The `check_job_terminated` method makes a call to ee2 to check whether a job is finished or not; if it is not, `ee2.cancel_job` is then called. This first call can be avoided by calling `ee2.cancel_job` straight away, as `cancel_job` returns a 200 / success response if the job is finished, regardless of whether the job was already finished or whether executing `cancel_job` caused it to complete.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-511

DATAUP-511: Removing the unnecessary check_job_terminated method

---

.gitignore
RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
test/unit/spec/narrative_core/kbaseNarrativeDataList-spec.js

The data panel's search feature was non-functional. This was simply caused by incorrect usage of `entries()` which caused the data object list filtering attempt to fail.
This was reported in a public ticket (https://kbase-jira.atlassian.net/browse/PUBLIC-1687) with development linked to a tracking ticket (https://kbase-jira.atlassian.net/browse/SCT-3084).
This PR also includes a single test added to ensure basic filtering is operational. (More tests could be added to cover data panel filtering and sorting.)
The test for this fix is included in `test/unit/spec/narrative_core/kbaseNarrativeDataList-spec.js` located here https://github.com/kbase/narrative/pull/2371/files#diff-cb9d9f24ad0c6a467ed27c2706878f2be2642c542281180cd8cfb5886bf572b7R206. This will be run with the frontend unit tests, …

SCT-3084 fix broken search in data panel

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
test/unit/spec/narrative_core/upload/stagingAreaViewer-spec.js

As the title says, this automatically checks the selection box when a user selects a file type in the staging area.
Note this only happens when a USER selects the file type. If there's only one suggested type for the file from the system, which gets auto-selected, this doesn't also auto-check the import checkbox.
https://kbase-jira.atlassian.net/browse/DATAUP-457

DATAUP-457 automatically check the import box when user selects a file type

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js

This converts the staging area to use the Datatables API when finding the set of files selected for import. This gets all files from all currently loaded pages in the datatable.
This is the first step in this ticket - it doesn't solve the problem of subfolders, which will be some additional work. Those are separate tables that get loaded and built when the user clicks into them.
https://kbase-jira.atlassian.net/browse/DATAUP-487

DATAUP-487 get checked rows from other pages

---

src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/tests/test_appmanager.py

The `EE2.run_job_batch` function was updated to propagate the workspace id in the `batch_params` parameter to each child job that gets started. This means that the individual jobs submitted don't need to have the `wsid` parameter, and, in fact, this throws an error.
This updates the appmanager to remove that parameter from jobs submitted through the `run_app_batch` function.
https://kbase-jira.atlassian.net/browse/DATAUP-533
It's easiest to do a `dry_run` of the function and see that the `wsid` isn't present. Or just run a bulk import cell and see that it doesn't get booted out of EE2 immediately.

DATAUP-533 remove wsid from batch submission

---

src/biokbase/narrative/jobs/jobmanager.py

Backend code expected the response from ee2 to be an object, but in fact it was an evil list!
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-512

DATAUP-512: Fix ee2 call to ensure it never returns a list

---

src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/data/ee2_job_test_data.json
src/biokbase/narrative/tests/test_appmanager.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobmanager.py
src/biokbase/narrative/tests/util.py

Handling for `batch_id`, `batch_job`, `child_jobs`, `retry_count`, `retry_ids`, and `retry_parent`. With an increasing number of `Job` attributes that may or may not be changing, @ialarmedalien decided the right data storage way would be to store the [reconstructed] EE2 state and extract attributes from that using either `@property` or `__getattr__`.
Parent `Job` objects are made aware of child `Job` objects.
- [n/a] [Version …

[DATAUP-512] Job Attributes & Parent-Child Relationship

---

docs/design/job_architecture.md
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test_jobmanager.py

Simple search-n-replace to make things more logical for the frontend; replacing the keys `job_id` and `retry_id` with `job` and `retry` respectively, since they are returning job objects.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-512

DATAUP-512: In retry_results, change job_id to job and retry_id to retry

---

src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

Set newly retried jobs to automatically refresh their status.
The majority of the changes are from black; I've commented on the two code changes that I made for the PR.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-512

DATAUP-512: Setting retried jobs to automatically refresh their state

---

docs/design/job_architecture.md
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/data/ee2_job_test_data.json
src/biokbase/narrative/tests/test_appmanager.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

Use `jc._cancel_jobs` and `jm.cancel_jobs` as the cancel job(s) narrative BE endpoints. Take out `jc._cancel_job` and `jm.cancel_job`
So, narrative BE expects a `cancel_job` message with either a `job_id` or `job_id_list` data. BE will filter out falsey job IDs and partition off any job IDs not registered. BE sends to FE `job_statuses` with the job states.
Carefully eliminated tests for `jc._cancel_job` and `jm.cancel_job` and added new tests, but could always add more.
- [n/a] (JavaScript) I have run Prettier and ESLint on …

DATAUP-485 Cancel Jobs

---

src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test_jobcomm.py

A couple of minor tweaks to the narrative backend to include the batch ID with job data
- added batch ID to the data returned in the job info request
- added batch ID to the job logs request plus returned a dict instead of a tuple

DATAUP-532: backend tweaks

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeStagingDataTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
kbase-extension/static/kbase/templates/data_staging/ftp_file_table.html
test/unit/spec/narrative_core/upload/stagingAreaViewer-spec.js

This has a number of changes to the staging area viewer code to support some bug fixes. There's a few other changes that this included.
Sorry for the size, there was really no way to do this piecemeal, as it needed an overhaul of how the datatable gets created and maintained. I couldn't really see a way to do that in parts without introducing strange and unusual behavior.
Bugs addressed:
* Navigating back from a two-deep-nested directory used to go from, for example `user/dir1/dir2` to `user/user/dir1`. Now it goes to `user/dir1` as expected.
* Selected files from multiple pages now all get added to the import cell.
* Select all / select none button works again.
* Selected files from nested directories all get added to the import cell.
* For example, selecting a file from root, a file …

DATAUP-487 Staging Area Viewer reworking to allow uploading of all checked files

---

docs/design/job_architecture.md
src/biokbase/narrative/exception_util.py
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

BE support for incoming messages from FE for `job_status_batch` and `job_status_info`.
- [n/x] [Version has been bumped](https://semver.org/) for each release
- [n/x] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge of feature branches)

DATAUP-485 Batch Statuses/Infos

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobActionDropdown.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTab.js
kbase-extension/static/kbase/js/common/jobManager.js
kbase-extension/static/kbase/js/common/jobMessages.js
kbase-extension/static/kbase/js/common/jobs.js
nbextensions/bulkImportCell/bulkImportCell.js
test/data/jobsData.js
test/data/testAppObj.js
test/unit/spec/common/cellComponents/tabs/jobActionDropdown-Spec.js
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/common/jobs-Spec.js
test/unit/spec/util/jobLogViewerSpec.js

- added the batch parent to the set of jobs in `exec.jobs`
- implementing proper batch handling in the job cancel and retry functions
- added a batch job cancel function to be hooked up to the cell 'Cancel' button
- test updates
The bus creation tests seem to be broken... I will take a look at them and fix them either in this PR or the next one.

DATAUP-532: Updating job manager to correctly calculate the jobs to be retried

---

docs/design/job_architecture.md
kbase-extension/static/kbase/js/common/jobCommChannel.js
kbase-extension/static/kbase/js/common/jobManager.js
nbextensions/appCell2/widgets/appCellWidget.js
test/unit/spec/common/jobCommChannel-spec.js
test/unit/spec/common/jobManager-Spec.js

The backend will soon be able to accept info/status/start updates/stop updates requests for all jobs in a batch, so this PR puts the frontend machinery in the `jobCommChannel.js` module in place.
I also made the FE job request naming conventions more uniform.
- Adding new batch queries into the job comm channel
- Converting "request-job-cancellation" => "request-job-cancel" for a more uniform API experience
- Updating job management docs

DATAUP-532: enable batch queries in the frontend

---

src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test_jobmanager.py

Ensures that `_create_jobs` and `_construct_job_state_set` return early if there are no jobs to create or construct a job state set for.

Ensure that narrative deals with empty results

---

docs/design/job_architecture.md
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

Updating backend to send results of job info and job status queries as a dictionary keyed by job ID with status or info as the value.
Switch all messages to respond with either `job-info` or `job-status` for simplicity.
- [x ] I have performed a self-review of my own code

DATAUP-532: simplify BE messages to FE

---

docs/design/job_architecture.md
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test_jobcomm.py

If there is no input, use the `job_comm_error` message instead of `job_does_not_exist`

DATAUP-532: change backend response types

---

RELEASE_NOTES.md
bower.json
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

Version bump to 4.5.0, and updated webdriverio in `package.json` to 7.9.1 to be in line with its side-dependencies.
The rest of the usual checklist is kinda redundant so was removed.

version bump to 4.5.0, webdriverio -> 7.9.1

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
kbase-extension/static/kbase/js/common/jobManager.js
package-lock.json
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobManager-Spec.js

- Updating job status table to be capable of handling retries
- Adding some super cool tests and some less cool tests
- remove some redundant code for handling jobs as the JobManager's default handlers will do most of the job for us

DATAUP-532: Increasing the retry readiness of the frontend

---

src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_appmanager.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobmanager.py

Always instantiate a `Job` object with the ee2 state, i.e., no longer with partial state information. This cuts down on the uncertainty of the `Job` object particulars at any given moment in the narrative backend. Use `Job.from_job_id` or `Job.from_job_ids`.
Switching the tests over was a bit of a challenge because there was either a lot of testing of the instantiation with partial information (since it is a bit un-simple) or the attributes of the `Job` objects instantiated with partial information were heavily used to test the correctness of the rest of the method in question.
- [n/a] Any dependent changes have …

DATAUP-556 Instantiate Job with EE2 State

---

kbase-extension/static/kbase/js/common/cellComponents/fieldTableCellWidget.js
kbase-extension/static/kbase/js/common/cellComponents/filePathWidget.js
nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/bulkImportCell/tabs/configure.js
test/data/testAppObj.js
test/unit/spec/common/cellComponents/fieldTableCellWidget-Spec.js
test/unit/spec/common/cellComponents/filePathWidget-Spec.js
test/unit/spec/nbextensions/bulkImportCell/tabs/configure-spec.js

Check for duplicate outputs across tabs.
This has a few fairly major changes, and **will require making a new bulk import cell.**
1. Track the output parameter ids in the bulkImportCell metadata now (just list and store them along side the fileParamIds and otherParamIds so we don't have to scrounge for them).
2. The configure tab now fetches and sends the output parameter for all of the unselected tabs to the filePathWidget of the selected tab.
3. Modifies the filePathWidget and fieldTableCellWidget to deal with the cross-tab changes.
There's some code in there to try to track the exact rows in each tab where there are duplicates, but that doesn't exactly work right because when multiple duplicates are made, they don't really get stored or flagged as such. So that code's in there, but …

DATAUP-551 duplicate outputs

---

src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

* Refresh when getting `job.child_jobs` and `job.retry_ids` & rippling effects
* Add/update tests
* Refactors & bug fixes

DATAUP-557 `job_id_list` for `job_status` and `job_info` etc.

---

docs/design/job_architecture.md
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

* `start_job_update` and `stop_job_update` now are tailored to use field `job_id_list` from FE
* Add `start_job_update_batch` and `stop_job_update_batch`, which will use field `job_id` containing batch container job ID to expand to `start_job_update` and `stop_job_update` requests with `job_id_list` fields containing the batch container and children job IDs.
- [n/a] [Version has been bumped](https://semver.org/) for each …

DATAUP-557 Listify `*_job_update`, Add `*_job_update_batch`

---

kbase-extension/static/kbase/js/common/jobManager.js
nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/bulkImportCell/bulkImportCellStates.js
package-lock.json
test/unit/mocks.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

- fixed up `runStatusListener` and cancel operations so they act in a uniform matter
- add in `switchToTab` method for automatic tab switching without having to worry about the tab being open already
- added new tests, updated existing bulk import cell tests
- fixed a few bits related to job cancellation in the jobManager and tests

DATAUP-532: a few more bits and pieces and finishing touches

---

kbase-extension/static/kbase/js/common/jobCommChannel.js
test/unit/mocks.js
test/unit/spec/common/jobCommChannel-spec.js
test/unit/spec/kbaseNarrativeSpec.js

Add the IDs of the current narrative cells to the generated python code that starts `jobcomm.py` in the narrative backend.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-519

DATAUP-519: Add cell IDs to the job comm channel init code

---

RELEASE_NOTES.md
src/requirements.txt

This consolidates the Python dependency updates from Dependabot for September.
No ticket here, but maybe we should have a routine maintenance one?
This whole checklist is N/A for this PR.

Update September Python dependencies

---

docs/design/job_architecture.md
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

* FE should be able to invoke `start_job_status_loop` with a `cell_list` so BE evermore does not have to send job state for job not in a cell
* Lookup loop and `all_status` requests now respect `"refresh"`
* Special batch parent cases
* Tests
- [n/a] I have made corresponding changes to the documentation
- [n/a] [Release notes](/RELEASE_NOTES.md) have been …

DATAUP-519 Refresh for init and all status

---

src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

The batch container job was previously being skipped when sending `job_info` requests BE->FE. That's because it couldn't quite fill the `"app_name"` field since it couldn't get an app spec due to its `app_id` being `"batch"`.
@ialarmedalien thought of a design where a batch container job's de facto `"app_name"` should be `"batch"`, thus allowing the batch container job to be included when sending `job_info` requests BE->FE. I.e., the `job` object's `app_name` attribute should be set to `"batch"` for batch container jobs.
`app_name` is not looked up in `__getattr__` because conventionally that's more for the attributes from the EE2 state. Also, `was_terminal` seems like it should be more an action than a `property` 
* Details for how to …

DATAUP-564 app_name for batch job info

---

kbase-extension/static/kbase/js/common/jobCommChannel.js
kbase-extension/static/kbase/js/util/appCellUtil.js
package-lock.json
test/unit/spec/common/jobCommChannel-spec.js

Removing some cruft associated with saving job IDs in the JobCommChannel widget. For now, the JobCommChannel  will not hold an index of the jobs associated with the narrative.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-575

DATAUP-575: remove frontend cruft

---

kbase-extension/static/kbase/js/util/appCellUtil.js
kbase-extension/static/kbase/js/util/stagingFileCache.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
test/unit/spec/nbextensions/bulkImportCell/tabs/configure-spec.js
test/unit/spec/util/stagingFileCacheSpec.js
test/unit/testUtil.js

This adds a wrapper call to the StagingService client's `list` function that caches the result for 30 seconds (same time as the refresh of the staging area viewer). This prevents spamming the service and bogging the browser down in the case that lots of bulk import cells try to find out how many missing files there are.
https://kbase-jira.atlassian.net/browse/DATAUP-468
* Run multiple bulk import cells with the network tab open
* Watch for traffic when toggling open/closed the Configure tab.
* Reload the page and see that there should only be one call to `StagingService.llist` (would probably show up as `<env>.kbase.us/services/staging_service/list/`)

DATAUP-468 cleanup - make StagingService cache

---

src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test_appmanager.py
src/biokbase/narrative/tests/test_jobcomm.py

* Set `jc._lookup_all_job_states` to query job states with `ignore_refresh_flag=True`. Upstream calls affected are `all_status` requests and `_lookup_job_status_loop`.
* Set `jm.register_new_job` to default set `"refresh"` to be the negation of the terminality of the last queried state.
* Test that `appmanager.AppManager.run_app*` has new jobs with `"refresh"` of `1`
- [n/a] [Release notes](/RELEASE_NOTES.md) have been updated for each …

DATAUP-575 JC ignore_refresh_flag

---

kbase-extension/static/kbase/js/common/jobCommChannel.js
package-lock.json
test/unit/spec/common/jobCommChannel-spec.js

Temporarily disable `cell_list` param to stop the backend from filtering out jobs that are still active.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-575

DATAUP-575: quick frontend fix

---

docs/design/job_architecture.md
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
kbase-extension/static/kbase/js/common/jobCommChannel.js
kbase-extension/static/kbase/js/common/jobManager.js
kbase-extension/static/kbase/js/util/jobLogViewer.js
nbextensions/bulkImportCell/bulkImportCell.js
src/biokbase/narrative/jobs/jobcomm.py
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobCommChannel-spec.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/util/jobLogViewerSpec.js

Some prep work for altering the job status table structure and general cleanup. It includes:
- save all the jobInfo in the model (including app ID, which will be needed for the next step)
- if the retry button is clicked, close the details row so that the job log doesn't keep showing info about the old job
- add a note above the table to indicate users should click on a row to view more details
General cleanup:
- remove the `job-log-deleted` message type, use the `job-logs` message type instead
- use `addEventHandler` and `removeEventHandler` in the jobManager in place of `addHandler` and `removeHandler` -- more descriptive
- switch to using the new `*-batch` endpoints in the backend
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-494

DATAUP-494: table layout change prep

---

.github/workflows/unit_test.yml
kbase-extension/static/kbase/js/util/jobLogViewer.js
nbextensions/bulkImportCell/bulkImportCell.js
package-lock.json
package.json
test/unit/karma.bulkImport.conf.js
test/unit/karma.conf.js
test/unit/run_tests.py
test/unit/spec/common/cellComponents/filePathWidget-Spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

- Fully implemented the bulk import reset action -- I added in code to terminate the batch job so there can be no doubt that this cell has been well and truly reset!
- added tests for the bulk import reset
- fixed failing bulk import tests
- added a separate karma config for the bulk import cell tests
- edited run_tests.py to run both the bulk import cell tests and the rest of the unit tests when `make test-frontend-unit` is called
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-450

DATAUP-450: Fully implement the bulk import reset action

---

src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py
src/biokbase/narrative/tests/util.py

- changing job.py so that if the widget info cannot be accessed, it does not change the status of the job
- adding cell_id to the output state of the job
- updating tests

DATAUP-338: widget info retrieval error

---

RELEASE_NOTES.md
src/biokbase/narrative/contents/narrativeio.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_narrativeio.py
src/biokbase/narrative/tests/util.py
src/biokbase/workspace/client.py

Cherry-picking the change from #2509 into `develop` to unblock some things. Thanks for the fixes, @n1mus!
(copied from other PR)
* WS API was changed so that list_objects requires 1-10000 ws ids.
* BE called ws.list_objects with 0 ws ids so thinks started breaking. E.g., spinning up local narrative with kbase-narrative would throw a huge error.
* Change it to call ws.get_workspace_ids and then call ws.list_objects with batches of ws ids
* Should be no visible changes, except viewing the Jupyter tree page should work again, as should the backend tests

Fix ws.list_objects requiring ws ids

---

docs/design/job_architecture.md
kbase-extension/static/kbase/js/common/jobCommChannel.js
kbase-extension/static/kbase/js/common/jobManager.js
kbase-extension/static/kbase/js/util/jobStateViewer.js
test/unit/spec/common/jobCommChannel-spec.js
test/unit/spec/common/jobManager-Spec.js

Plus a few other bits:
- remove job-does-not-exist listeners globally, replacing where appropriate
- jobManager.js: allow handlers to be added using just the handler name
- alter jobCommChannel to deal with status: ee2_error
- update tests
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-613
- [] Changes available by spinning up a local narrative and navigating to _X_ to see _Y_

DATAUP-613: remove job does not exist listeners

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/results/outputWidget.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/results/reportWidget.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/results/resultsTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
package-lock.json
test/unit/spec/common/cellComponents/tabs/results/outputWidget-spec.js
test/unit/spec/common/cellComponents/tabs/results/reportWidget-spec.js
test/unit/spec/common/cellComponents/tabs/results/resultsTab-spec.js

The results tab was crashing on a later load if any of the generated files were deleted in the meantime. This handles those errors in a somewhat more elegant way and shows some placeholder text for missing data.
This screenshot demonstrates the various missing data states:
Some of them, in a few rare cases, are recoverable - if there's no object name given in the results, the name from the fetched workspace object info can be used. Same for the type. However, these are also fetched from the workspace, so if there's an error with one ws call, there's likely an error with others, so this is kind of an odd edge case.
For the reports area, if the report itself isn't found, I left a row for it, and just put some dummy text with "report not found" next to it. These will only show up if there's …

DATAUP-600 results tab crashes with deleted files

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/function_output/samples/SampleSet.js
kbase-extension/static/kbase/js/widgets/function_output/samples/kbaseSampleSet.js
test/unit/spec/function_output/kbaseSampleSet/kbaseSampleSet-spec.js

The KBaseSets.SampleSet viewer was missing a "name" column; it has now been added.
This column represents the user provided "name" or "id" column of a sample. The sample service validation spec defines which sample files map to the name column. Existing examples are ENIGMA's "SampleID" column and SESAR's "Sample Name" column.
This also necessitated the addition of a new dynamic group "Sample", which currently contains the sample row number and the sample name.
- [-] I have made corresponding changes to the documentation
- [-] Any dependent changes have been merged and published in downstream modules
- [-] (Python) I have run Black and Flake8 on changed Python code manually or with a git precommit hook …

SAM-40: add name column to SampleSet viewer

---

kbase-extension/static/kbase/js/common/cellComponents/cellTabs.js
kbase-extension/static/kbase/js/common/fsm.js
nbextensions/appCell2/widgets/appCellWidget-fsm.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/tabs/status/logTab.js
nbextensions/bulkImportCell/bulkImportCell.js
package-lock.json
test/unit/spec/nbextensions/appCell2/widgets/appCellWidget-fsm-spec.js

Finishing off the work done in DATAUP-613_rm_job_does_not_exist_handlers:
- Removing job-does-not-exist handler from the appCell and add in handling for the "does_not_exist" job status.
- Compact the appCell FSM states
- Use the messages from DialogMessage for various app cell actions (cancel, retry, etc)
- Make the job status tab slightly more efficient
- minor object key/value assignment edits
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-613

DATAUP-613: remove 'job-does-not-exist' handler from the app cell

---

nbextensions/appCell2/appCell.js

Removing "info" dropdown menu item from the app cell, which was causing buggy behaviour with the "delete cell" item.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-323
- [n/a ] I have added tests that prove my fix is effective or that my feature works

DATAUP-323: remove "info" menu item

---

src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/tests/test_appmanager.py

Extremely minor cleanup: switch out BATCH_ID_KEY for the correct variable name, "batch_id"

DATAUP-497: very minor variable substitution

---

Dockerfile

In the last push, the Dockerfile wasn't updated properly to include the NodeJS LTS update. This resulted in the installation failing silently until someone tried to open a narrative on CI. So that's bad.
This fixes that problem to get things installed as expected. 
No code changes, just fixed the Dockerfile install process.
* Fetch the built image with `docker pull ghcr.io/kbase/narrative-develop:pr-2588`
* exec into it with `docker run -it --entrypoint bash ghcr.io/kbase/narrative-develop:pr-2588`
* run `kbase-narrative` then quit (or just run it in the background)
* verify that …

fix dockerfile, update nodejs

---

nbextensions/bulkImportCell/bulkImportCell.js
package-lock.json
src/biokbase/narrative/tests/narrative_mock/mockclients.py
test/unit/spec/common/cellComponents/tabs/results/reportWidget-spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

Prevent cell getting stuck in launching by resetting it to 'editingComplete'
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-587

DATAUP-587: reset cell stuck in launching

---

docs/adrs/0004-bulk-import-output-cells.md

This came up as an Action Item from a couple of Retrospectives - document the decision to have Bulk Import cells NOT produce output cells after individual app runs. Short version = would make a zillion, possibly unexpected, unordered data viewer cells.

add ADR for output cells from bulk import

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/bulkImportCell/tabs/configure.js
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/nbextensions/bulkImportCell/tabs/configure-spec.js

Pass in file type mappings from the bulk import cell, rather than generating them in the job status table and configure tabs

DATAUP-497: generate file type mappings centrally

---

nbextensions/appCell2/widgets/appCellWidget-fsm.js
test/unit/spec/nbextensions/appCell2/widgets/appCellWidget-fsm-spec.js

A minor regression on the app cell state management prevented enabling the job status tab when an app ended in error. This fixes that. Hooray!
https://kbase-jira.atlassian.net/browse/DATAUP-626
* Run an app that fails (like the App Fail app in CI), or any app with bad data

DATAUP-626 fix non-batch app cell disabling job status on error

---

kbase-extension/static/buildTools/loadAppWidgets.js
kbase-extension/static/kbase/js/common/monoBus.js
kbase-extension/static/kbase/js/common/spec.js
kbase-extension/static/kbase/js/common/validation.js
kbase-extension/static/kbase/js/util/util.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/customInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/sequenceInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/structInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/validation.js
kbase-extension/static/kbase/js/widgets/appWidgets2/validators/int.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/sequenceView.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/structView.js
nbextensions/advancedViewCell/widgets/appParamsWidget.js
nbextensions/viewCell/widgets/viewCellWidget.js
test/unit/spec/util/util-Spec.js

As talked about here: [#2593 comment](https://github.com/kbase/narrative/pull/2592#discussion_r750329883) , this PR moves the `common/lang` utility module to the `util` directory with the rest of them. It updates all the other module that used it to the new resource.
ESlint and Prettier threw a collective tantrum as well, so most of the code changes are due to that. Will comment inline.
https://kbase-jira.atlassian.net/browse/DATAUP-X
* should be no visible changes

DATAUP-614 (related) migrate common/lang -> util/util

---

docs/design/job_architecture.md
kbase-extension/static/kbase/js/common/jobCommChannel.js
kbase-extension/static/kbase/js/common/jobManager.js
kbase-extension/static/kbase/js/util/jobLogViewer.js
package-lock.json
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py
src/biokbase/narrative/tests/util.py
test/unit/spec/common/jobCommChannel-spec.js

There's a load of unnecessary conversion between back and frontend data; this PR aims to decrease that.
Convert backend to emit job data in format used by the frontend to cut down on conversions required
Update frontend to deal with new backend output format
Update job architecture docs

DATAUP-497: simplify conversions between backend and frontend jobs

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
kbase-extension/static/kbase/js/common/jobCommChannel.js
kbase-extension/static/kbase/js/common/jobManager.js
kbase-extension/static/kbase/js/util/jobLogViewer.js
kbase-extension/static/kbase/js/util/jobStateViewer.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/tabs/status/jobInputParams.js
nbextensions/appCell2/widgets/tabs/status/jobStateList.js
nbextensions/bulkImportCell/bulkImportCell.js
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobCommChannel-spec.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js
test/unit/spec/util/jobLogViewerSpec.js

A big search-n-replace to switch out strings representing job message types to values from the JobCommMessages module. This is to make it easier to rename the messages without having to find the zillion places in the code that they are mentioned. 😖 

DATAUP-497: simplify cell message types

---

src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

Tokenise input params for messages to the backend job comm. This will allow easy substitution of those params so the frontend doesn't have to do a load of translation of messages.
This is basically all search-n-replace, very little content change.

DATAUP-497: tokenising the input params for messages to the backend job comm

---

docs/developer/data_import.md
package-lock.json

The main goal of this PR is to provide documentation on how to add more bulk import apps to the Narrative configuration. I also wrote some pretty high level docs on how the Import tab is assembled, with some detail on how the import app mapping is configured.
No code changes here.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-608
no code changes - all of the checklist below is n/a

DATAUP-608 add uploader app docs

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
kbase-extension/static/kbase/js/common/jobManager.js
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobManager-Spec.js

The job status table was lagging behind the other places where job status is visible because it was using functions bound to instances of the job status table that were no longer extant. This PR fixes the issue by ensuring that the job manager always has the most current version of the handler functions (and their bound arguments) available. See inline notes for more.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-630

DATAUP-630: fix lagging job status table

---

kbase-extension/static/kbase/js/common/cellComponents/actionButtons.js
kbase-extension/static/kbase/js/common/cellComponents/cellControlPanel.js
nbextensions/bulkImportCell/bulkImportCell.js

When the bulk import cell first starts, if there's some lag in initial param and file validation, it can look like this:
This change immediately sets the button state to something possibly more expected while it figures out what state it should be:
screenshots are greyish because they're taken while paused in the browser debugger.
* open a new BI cell!
- [n/a] New and existing unit tests pass locally with my changes

DATAUP-653 set an initial action button state to avoid showing all buttons

---

.github/pull_request_template.md

Small edits to the PR template:
- turn the Jira ticket mention into an explicit link
- reorder the linting/dependent changes lines to make it easier to delete the irrelevant lines

Minor edits to the PR template

---

kbase-extension/static/kbase/js/common/jobManager.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

Adds a timestamp to the cell reset message -- will be used by the backend implementation of the cell reset.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-654

DATAUP-654: Add a timestamp to the cell reset message

---

docs/design/job_architecture.md
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
kbase-extension/static/kbase/js/common/jobCommChannel.js
kbase-extension/static/kbase/js/common/jobManager.js
kbase-extension/static/kbase/js/util/jobLogViewer.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
nbextensions/appCell2/widgets/tabs/status/jobInputParams.js
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobCommChannel-spec.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/util/jobLogViewerSpec.js

Continue simplification of job-related messages.
jobCommChannel.js: 
- more tokenising of message strings
- remove unused `RESULT` and `PING` message types and tests for those messages
- pass most backend messages as-is to the frontend without any faffing around with "translating" them
- remove nesting / "options" in job logs requests
jobManager, jobStatusTable, jobInputParams, jobLogViewer, kbaseNarrativeJobStatus:
- adapt code to account for new message structure
- update tests to take into account all the above changes

DATAUP-497: more job message edits

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js

Add listeners to the job status table after row creation, rather than waiting until after the table is drawn
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-666

DATAUP-666: no one is listening to those table rows!

---

kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/util/string.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
nbextensions/bulkImportCell/bulkImportCell.js
test/data/kb_uploadmethods.import_fasta_as_assembly_from_staging.spec.json
test/unit/spec/narrative_core/upload/stagingAreaViewer-spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js
test/unit/spec/util/StringSpec.js

As the title says - in both standard app cells for importers and in the bulk import cells, the suggested object name could include illegal characters. This fixes this in two ways for the two cases:
1. for non-bulk importers, this now runs the file name through `sanitizeWorkspaceObjectName` in `util/string`, which does exactly that, turning illegal characters into underscores. It also strips any file paths off.
2. for the bulk importer, as that is set during the cell initialization step, the sanitization work is done there. This also means that the suggested suffix gets passed along as an input - this gets stripped out of the inputs before they get serialized as metadata, since after the initial parameters are put together, the suffixes aren't useful anymore.
(in draft mode as tests are …

DATAUP-577 sanitize suggested output object name for import cells

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/dynamicDropdownInput.js

* fixes unresolved issue with esprima that can be found [here](https://github.com/jquery/esprima/issues/2034#issuecomment-818542469)

Remove object spread syntax that esprima 4.0.1 doesn't like

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
package-lock.json
test/unit/spec/narrative_core/upload/stagingAreaViewer-spec.js

The staging service can return any number of recommendations for file types. However, only those with a matching app configuration in the Narrative are usable as import inputs. This patch politely ignores any returned types from the staging service that do not match the Narrative configured types. It also graciously accepts any display names from the staging service and sets them aside in favor of its own configuration.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-570
* Kinda tricky without differences in the staging service. You could set up a local staging service, maybe?

DATAUP-570 Reconcile config with staging service recommendations

---

docs/design/job_architecture.md
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
kbase-extension/static/kbase/js/common/jobCommChannel.js
kbase-extension/static/kbase/js/common/jobManager.js
kbase-extension/static/kbase/js/util/jobLogViewer.js
kbase-extension/static/kbase/js/util/jobStateViewer.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/tabs/status/jobInputParams.js
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobCommChannel-spec.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js
test/unit/spec/util/jobLogViewerSpec.js

Another search and replace ticket, plus a bit more standardising of query names.
Added the parameters used for job-related requests to the `jcm` object as `jcm.PARAMS` and substituted any param strings found in the code with the appropriate `jcm.PARAMS.*` entry, e.g.
```js
bus.emit(jcm.REQUESTS.STATUS, { batchId: 'some-batch-id' })
```
is now
```js
bus.emit(jcm.REQUESTS.STATUS, { [jcm.PARAMS.BATCH_ID]: 'some-batch-id' })
```

DATAUP-497: Standardising the params used for job queries in the frontend

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/importSetup.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
package-lock.json
test/unit/spec/narrative_core/upload/importSetup-spec.js
test/unit/spec/narrative_core/upload/stagingAreaViewer-spec.js

The first step for setting up the xSV stuff is, in my opinion, factoring out the code that sets up data import app cells (both standard and bulk import). This PR does that, creating a new `importSetup.js` module. 
This is really just a refactor at this point with stubs for the flow of how the xSV integration will work. It takes the separate `initBulkImport` and `initImportApp` functions in the `stagingAreaViewer` module and combines them into a single `initImport` function. This then calls out to the new module that does all the logic around what file gets uploaded in which cell and how.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-636
* there should be no visual change
- [n/a] [Version has been bumped](https://semver.org/) for each …

DATAUP-636 xSV happy path setup

---

src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/tests/test_appmanager.py

Only one `NEW_JOB` message is emitted when bulk jobs are kicked off, rather than a message for every job initiated.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-680

DATAUP-680: cut down on new job messages

---

src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/tests/test_jobcomm.py
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

Adding the original request to the JobRequest object for better troubleshooting and error explication.
Temporarily disabled the dodgy bulkImportCell test that keeps on failing.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-681

DATAUP-681: add raw request to job error response

---

src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_appmanager.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

Alter the job logs retrieval commands to take a list, rather than a single job ID
The main purpose of this PR is to unify the job manager interface so all methods deal with lists of job IDs (instead of having a miso-mash of different interfaces) and emit errors as part of a set of results.

DATAUP-497: retrieve job logs for a list of job IDs

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/function_output/modeling/kbaseTabTable.js

Some modeling widgets, such as the FBAModel viewer, were reported to have broken landing page links. The user reported that the link included "functional-site" in the path, and that removing it resulted in a working link for the landing page. "functional-site" was the name of the precursor to kbase-ui, which was in use about 5 years ago ... so this link has been broken for a long time!
The fix was very simple - just an edit of one line. The overall change required a tad more work, as the modeling widget source (kbase-extension/static/kbase/js/widgets/function_output/modeling) required some repair to be compliant with current practices in the codebase. To wit, it required fixes to satisfy eslint, including two overrides for global modules.
Two major flaws were left in the file, though, in …

Fix PTV-1717/-1839 - landing page link with functional-site prefix

---

kbase-extension/static/kbase/config/staging_upload.json
kbase-extension/static/kbase/js/api/StagingServiceClient.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/importSetup.js
nbextensions/bulkImportCell/bulkImportCell.js
package-lock.json
test/unit/karma.conf.js
test/unit/spec/api/StagingServiceClient-spec.js
test/unit/spec/narrative_core/upload/importSetup-spec.js
test/unit/spec/narrative_core/upload/stagingAreaViewer-spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

At least, I think it's mostly happy? This adds the following changes.
* adds the `bulk_specification` endpoint to the staging service client
* uses that endpoint to fetch data from files tagged imported as `Import Specification`
* uses that information to initialize a bulk import cell, on the happy path, with a few caveats
* does not put up any warnings, errors, etc. for missing data (doesn't even check for missing data)
* merges the non-file parameters from the first row of the file input with the app defaults
* really not much error checking at all and might be oddly fragile if your file's busted
Tests pending - putting this up here as a draft for now.
- [n/a] (Python) I have run …

DATAUP-636 XSV happy path

---

src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/narrative_mock/mockcomm.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

This started off as a fairly benign search and replace and somehow... grew.
Lots of tidying and a bit of refactoring of jobcomm tests without much content change.
Comments inline.
- [-] Changes available by spinning up a local narrative and navigating to _X_ to see _Y_

DATAUP-497: a mess o' trouble

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/common/jobCommChannel.js
kbase-extension/static/kbase/js/kbaseNarrative.js
nbextensions/bulkImportCell/bulkImportCell.js
package-lock.json
test/unit/spec/common/jobCommChannel-spec.js
test/unit/spec/kbaseNarrativeSpec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

This addresses an issue where the "Narrative updated in another session" button would occasionally show up for no apparent reason. The reason was that race conditions are no fun.
See ticket for details, but the short version is that it was possible for the narrative's known document version to get out of sync with what's in the Workspace. This would happen when a timer that updates the available Workspace data (including the Narrative object) would fire while the Narrative was saving, in just the right time to cause problems. Couple this with a few asynchronous functions that were handling things poorly, and you get this intermittent, hard to reproduce, problem.
No guarantees that this fixes it for sure, but I identified a few places to make improvements and put in a number of tests …

PTV-1726 session version

---

kbase-extension/static/kbase/js/util/kbaseApiUtil.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/importSetup.js
package-lock.json
test/data/kb_uploadmethods.import_fastq_interleaved_as_reads_from_staging.spec.json
test/unit/spec/narrative_core/upload/importSetup-spec.js

Not so much on error handling in this one, but fixes a parameter issue. Now, the static dropdown and checkbox values are more precise. This change expects that the user provides the "display" value for the dropdowns, and either a "1" or "0" for checkboxes, as per design decisions here: https://kbase-jira.atlassian.net/browse/DATAUP-408?focusedCommentId=84578 . These get translated into the proper "value" and "unchecked_value"/"checked_value" properties, respectively. All other parameters are more or less text field based and would be unchanged. Except for the scary dynamic dropdown thing which will get solved later.
Also introduces a minor issue where the app specs get fetched multiple times on the way to starting a BI cell. This will get streamlined in a future PR.
Related Jira ticket: …

DATAUP-636 XSV happy path parameter fixes

---

src/biokbase/narrative/tests/generate_test_results.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

Message generation for the major message types (job status, info, retry, and logs) is now centralised in a single file. Hurrah!

DATAUP-497: move all test result generation to a single file

---

src/biokbase/narrative/tests/data/app_specs.json
src/biokbase/narrative/tests/data/ee2_job_test_data.json
src/biokbase/narrative/tests/generate_test_results.py
src/biokbase/narrative/tests/job_test_constants.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

- Move generation of data-dependent constants to `generate_test_results.py`
- substitute in up-to-date ee2 job data structures

DATAUP-497: PR V

---

src/biokbase/narrative/clients.py
src/biokbase/narrative/jobs/util.py
src/biokbase/narrative/tests/test_job_util.py

Remove unused code in job utils and clients python files

DATAUP-497 VI b: cruft removal

---

src/biokbase/narrative/clients.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

Alter ee2 error handling to remove the alteration of the job state object and put the error into a separate field
Alter behaviour on failure of job initialisation to return (rather than trying to run the lookup loop); add in a test
Uniform error behaviour in tests for ee2 errors

DATAUP-497 PR VII: error handling

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/importErrors.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/importSetup.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
package-lock.json
test/unit/spec/narrative_core/upload/importErrors-spec.js
test/unit/spec/narrative_core/upload/importSetup-spec.js

This is the first part of handling errors in XSV files. It mainly deals with errors that come straight from the Staging Service's bulk_specification endpoint. Data errors in the files themselves will come later.
This adds a new ImportSetupError class that knows how to parse out all of the registered error structures with the Staging Service and make a dialog out of them. There might be a few gaps in style, especially around handling multiple files/tabs describing the same data type - these'll get handled in a later PR if necessary.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-638
* Try to import some faulty XSV files as Import Specifications!

DATAUP-638 XSV errors part 1 - staging service

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
kbase-extension/static/kbase/js/common/jobCommChannel.js
kbase-extension/static/kbase/js/common/jobManager.js
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobCommChannel-spec.js
test/unit/spec/common/jobManager-Spec.js

Unify FE and BE job request/response params and update components and tests accordingly.

DATAUP-497: Params, Unite!

---

docs/design/job_architecture.md
kbase-extension/static/kbase/config/job_config.json
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
kbase-extension/static/kbase/js/common/jobCommChannel.js
kbase-extension/static/kbase/js/common/jobManager.js
kbase-extension/static/kbase/js/util/jobLogViewer.js
kbase-extension/static/kbase/js/util/jobStateViewer.js
kbase-extension/static/kbase/js/widgets/appWidgets2/customWidgetWrapper.js
kbase-extension/static/kbase/js/widgets/custom/advancedViewerOutputWrapper.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/appOutputWidget.js
nbextensions/appCell2/widgets/tabs/status/jobInputParams.js
nbextensions/appCell2/widgets/tabs/status/jobStateList.js
nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/outputCell/widgets/outputCell.js
package-lock.json
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobCommChannel-spec.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/common/jobs-Spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js
test/unit/spec/util/jobLogViewerSpec.js

Standardised all the frontend job vocab to use the singular form (e.g. `PARAM` instead of `PARAMS`) and to generally use `jcm.MESSAGE_TYPE` instead of `jcm.REQUESTS` or `jcm.RESPONSES`. Should really have done this in the first place but never mind...
Two other minor changes: (1) add missing underscore in job_config file, and (2) use `jcm.RESPONSES` in the job manager file where we do actually want to restrict the code to looking at valid response types.

DATAUP-497: big dumb regex

---

kbase-extension/static/kbase/config/staging_upload.json

As the title says - remove the option to load an XSV file as an import specification. This lets us keep working in the codebase  on `develop` but prevents unfinished features from leaking out to the upcoming 5.0.1 release (and others after that).

Remove "import specification" from the staging area options

---

kbase-extension/static/kbase/js/common/jobCommChannel.js
test/data/jobsData.js
test/unit/spec/common/jobCommChannel-spec.js

Use incoming kernel messages to generate a mapping of job IDs to batch IDs in the JobCommChannel module

DATAUP-497: create a job ID to batch ID mapping

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/upload/importErrors.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/importSetup.js
package-lock.json
test/unit/spec/narrative_core/upload/importErrors-spec.js
test/unit/spec/narrative_core/upload/importSetup-spec.js

The spreadsheet importer should throw errors when the data types are either invalid or not registered as bulk import data types. This adds the new data types and some tests around them.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-696
* Upload a xSV file where the data type in the top header row is something nonsensical.
* Upload a xSV file where the data type in the top header row is something not in the bulk import remit, like "media" or "matrix"

DATAUP-696 spec importer mismatch

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
kbase-extension/static/kbase/js/common/jobManager.js
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobManager-Spec.js

A couple of minor changes to the job manager module:
- specify the type of listener to be added to a channel instead of defaulting to 'JOB'
- add in channel info as argument to job manager event handlers and update tests accordingly
- change a couple of variable names for clarity

DATAUP-497: Prepping for batches

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/importErrors.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
test/unit/spec/narrative_core/upload/importErrors-spec.js
test/unit/spec/narrative_core/upload/stagingAreaViewer-spec.js

Server errors being displayed in the dialog for bulk specification files weren't being properly escaped. Neither were filenames. Neither, it turns out, were filenames in the staging area, so files named something like `<I'm a file>.txt` were just showing `.txt`.
This addresses all of that by escaping text on its way to display.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-638

DATAUP-638 properly escape file names and server errors

---

kbase-extension/static/kbase/js/common/jobCommMessages.js
test/data/jobsData.js
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobs-Spec.js

Minor change to the structure of the test data

DATAUP-497: Slight alteration to the structure of the test jobs data

---

docs/design/job_architecture.md
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/data/response_data.json
src/biokbase/narrative/tests/generate_test_results.py
src/biokbase/narrative/tests/test_jobmanager.py

Quick edit to include the retry_id field in the backend response to a retry request

DATAUP-497: Add retry_id to retry response from backend

---

src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/tests/data/response_data.json
src/biokbase/narrative/tests/generate_test_results.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py

Quickie - add the job ID to the output of the backend job status request

DATAUP-497: add job id to job status

---

kbase-extension/static/kbase/js/common/jobs.js
test/data/jobsData.js
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobCommChannel-spec.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/util/jobLogViewerSpec.js

Two changes in this PR:
- update the job state object validation to include the `job_id` key (change made in the last PR)
- more edits of the JS job test data; replace the valid message samples with those from the BE response data; and use constants for the job names

DATAUP-497: job data structure updates and  job test data edits

---

kbase-extension/static/kbase/js/common/jobCommChannel.js
package-lock.json
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test_appmanager.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py
test/unit/spec/common/jobCommChannel-spec.js

It was noticed that the job channel of the websocket was using a fairly colossal amount of bandwidth. This wound up being due to all job status being returned from an `all_job_status` call in the kernel-side job monitoring thread, even if all of those jobs were complete and nothing on the front end was tracking them.
After some discussion, we decided that one of the cores of the problem was using the "refresh" flag for each job as an integer. This would represent the number of front end things (widgets, viewers, etc.) that wanted to receive continual job status. As those things were created or destroyed, the count would go up and down, and as long as one thing wanted job status, it would get returned on each turn of the cycle.
This is horribly confusing and inefficient and led to the …

DATAUP-703 job channel bandwidth

---

kbase-extension/static/kbase/js/common/jobManager.js
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/nbextensions/appCell2/widgets/appCellWidget-spec.js
test/unit/spec/util/jobLogViewerSpec.js
test/unit/testUtil.js

Centralising all bus message sends in the TestUtils files for ease of manipulation.

DATAUP-497: Moving all bus message sending to the TestUtils file

---

kbase-extension/static/kbase/js/common/looper.js
test/unit/spec/common/looper-spec.js

A simple module to execute a function after a configurable delay.

DATAUP-497: Adding a simple looper module for scheduling function execution

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js

This fixes a minor rendering issue for Narrative names in the Narratives panel. Also applies the usual eslint workflow to the code for that panel.
It needs a deeper cleanup, but as it's meant to be replaced by similar functionality in the external Narrative Navigator, that may happen later, or not at all. This tackles an immediate issue.

Some minor Narratives panel fixes

---

kbase-extension/static/kbase/js/widgets/narrative_core/dataBrowser.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseDataCard.js

User-created text (like narrative names, also object type names and object names) was possibly being mangled in the slideout data browser. This converts a few auld jquery `.append` calls to `.text` to fix that.
- [n/a - previous PR notes apply] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge of feature branches)

fix a few other cases where user-created text was mangled

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
kbase-extension/static/kbase/js/common/jobManager.js
test/data/jobsData.js
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/common/jobs-Spec.js
test/unit/spec/nbextensions/appCell2/widgets/appCellWidget-spec.js

Minor changes to the job manager: update listener indexing to allow both JOB and CHANNEL listeners for a single ID; a couple of minor efficiency fixes for default job handlers

DATAUP-678: job manager updates

---

kbase-extension/static/kbase/js/common/jobManager.js
test/unit/spec/common/jobManager-Spec.js

Minor reorganisation of the Job Manager module, and addition of two new batch job methods -- request info and request status.

DATAUP-678: New and moved methods in the JobManager module

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
kbase-extension/static/kbase/js/common/jobManager.js
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

Updating job manager to add all relevant listeners for batch jobs, and convert the job status table over to using the batch channel to receive messages

DATAUP-678: universal batch listening for the job manager and the batch table

---

kbase-extension/static/kbase/js/common/jobManager.js
kbase-extension/static/kbase/js/common/looper.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

Rather than having the backend run the job status lookup loop, the frontend now requests job status updates when it desires them. It's strong and independent and empowered like that!
TODO: 
- add the request loop to the app cell and narrative job status widget
- do we need a fallback in case the request is not fulfilled?

DATAUP-678: Adding a looped job status request to the batch job manager

---

src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

Extremely minor PR, reordering methods in the py job manager and changing the names of some methods to be `get(_all)*_job` instead of `lookup(_all)*_job` for internal consistency in the module.

DATAUP-678: minor job manager edits

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/appWidgets2/input/selectInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/validation.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/importSetup.js
test/unit/spec/appWidgets/input/selectInputSpec.js

Actually adding error checks now! This one shows an error in select box dropdowns if an xsv file has an invalid entry (or, really, if any value is set that isn't one of the options).
Design from https://kbase-jira.atlassian.net/browse/DATAUP-408
Working example:
Another example with custom error text in different cases:
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-641

DATAUP-641 - add check for bad select box input from an xsv spec

---

kbase-extension/static/kbase/js/common/jobCommChannel.js
kbase-extension/static/kbase/js/common/jobManager.js
test/data/jobsData.js
test/unit/spec/common/jobCommChannel-spec.js
test/unit/spec/common/jobManager-Spec.js

Adding a mixin to allow the job manager to be used with single jobs, not just batches.

DATAUP-678: Adding mixin for using job manager with single jobs

---

kbase-extension/static/kbase/js/common/jobStateViewer.js
kbase-extension/static/kbase/js/common/simpleLogViewer.js
test/unit/spec/common/jobStateViewer-spec.js
test/unit/spec/common/simpleLogViewer-spec.js

This PR splitting out the job log viewer into a job state viewer and a simplified log viewer, both of which use the job manager. The next PR will switch over the job status table to use these new widgets, so that all the bulk import cell stuff uses the job manager.

DATAUP-678: split job log viewer into job state viewer and simple log viewer

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobActionDropdown.js
kbase-extension/static/kbase/js/common/jobs.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCellToolbarMenu.js
nbextensions/bulkImportCell/bulkImportCell.js
test/unit/spec/common/jobs-Spec.js

Some minor tidying noticed along the way. I would have integrated it into the previous PRs but don't want to have to rebase them again!
Changes:
- Switch methods using indexed jobs from the model to use `exec.jobs.byId`, rather than `exec.jobs`
- rename JobStateViewer (remove the "Managed" part)
- update tests

DATAUP-678: minor tidying

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTab.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/bulkImportCell/bulkImportCellStates.js
test/unit/spec/common/cellComponents/tabs/jobStatusTab-Spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

Two tab-related tasks:
- Add a new "launching" state to the bulk import cell, with a message saying that the job has been submitted to the job runner and the cell is waiting for a response. I've made this part of the job status tab as it doesn't need its own widget.
- Fix a tab switching error where the BI cell gets confused if no tab is selected/open when it has to change tabs.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-719

DATAUP-719: tab switch fix and new launching tab

---

kbase-extension/static/kbase/js/common/pythonInterop.js
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/batch.py
src/biokbase/narrative/tests/test_appmanager.py
src/biokbase/narrative/tests/test_job.py
test/unit/spec/common/pythonInterop-Spec.js

Noticed this whilst looking at the backend to see what could be optimised there.
Rename app manager methods to be more correct:
- `run_app_batch` (old batch method) ==> `run_legacy_batch_app`
- `run_app_bulk` (new batch ee2 endpoint) ==> `run_app_batch`
...plus renaming / changing other methods and references accordingly
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-719

DATAUP-719: app manager method rename

---

kbase-extension/static/kbase/js/common/jobStateViewer.js
kbase-extension/static/kbase/js/common/jobs.js
test/data/testBulkImportObj.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/common/jobs-Spec.js

Change `Jobs.jobArrayToIndexedObject` function to return an object comprising job IDs as keys and job states as objects, rather than having it wrapped in an object under a `byId` key. This will prevent creation/updates to the job index from trashing existing job info data.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-719

DATAUP-719: simplify job indexing command

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/function_output/kbasePanGenome.js

This change fixes the PanGenome viewer which in production is displays an error, “Bad object.”
The issue is caused by a failure of the viewer to determine a value object reference.
The fix is to observe that if there is a parameter property "this.options.upas.name" to use it. The existing techniques of determining the upa are left in place.
The  parameter property "this.options.upas.name" is set by "widgetmanager.py" based on the spec for the viewer.
This is discussed in more detail in the ticket https://kbase-jira.atlassian.net/browse/PTV-1765.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/PTV-1765.
- [-] I have made corresponding changes to the documentation
- [-] I have added tests that prove my fix is effective or that my feature works …

Fix PanGenome viewer error [PTV-1765], & addressing pre-commit linting errors

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/common/cellComponents/paramsWidget.js
nbextensions/bulkImportCell/bulkImportCell.js

There was a flaw in the implementation of the "show advanced" button in the bulk import params widget. This led to that message (and the "X parameters hidden" message) never being toggled to "hide advanced". It also made it really hard to work on DATAUP-642, which involves adding a further error message there, so this got fixed first.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-525

DATAUP-525 fix issue with advanced parameter labels not changing

---

src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/tests/test_appmanager.py

To reduce the data sent from the FE to BE upon submitting a bulk import job, any shared parameters are condensed into its own field. The BE's responsibility is to, in `am.run_app_bulk`, merge the shared parameters back into the child jobs' parameter sets.
- [] (Python) I have run Black and Flake8 on changed Python code manually or with a git precommit hook

DATAUP-728 am.run_app_bulk: merge shared_params into param_sets

---

docs/adrs/0004-bulk-import-output-cells.md
kbase-extension/static/kbase/config/staging_upload.json
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/narrative_core/upload/stagingAreaViewer-spec.js
test/unit/spec/util/appCellUtil-spec.js

The original names for the import types for the Bulk Import were confusing for some beginner users because some thought GFF/FASTA meant GFF or FASTA file. This ticket is to make the names more precise and consistent.
Renaming:
* `Assembly` -> `FASTA Assembly`
* `GFF/FASTA Genome` -> `GFF+FASTA Genome`
* `GFF/FASTA Metagenome` -> `GFF+Fasta Metagenome`
All the changes are in the frontend. The frontend tests are not passing, but I don't know if they're in an interim state of not passing anyway. (The backend tests fail as they always do because of those 2 tests that only work in the appdev environment.) Furthermore, I tried to spin up a local narrative, but I tried giving it the token on prompt with the `kbase_session` cookie, then the `narrative_session` cookie, then finally a dev token, …

PTV-1776 Re-Scheme Import Type Names

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
package-lock.json
test/unit/spec/narrative_core/kbaseNarrativeDataList-spec.js

The object history reversion feature in the left hand data panel has apparently not been working for some time. The issue was an incorrect way of array value iteration.
It took some willpower to not refactor the whole widget. But I managed.
Just a couple lines of change for the fix, and over 200 for tests. As usual.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/PTV-1784
* Open a narrative with some data in it
* Click the "..." button that appears on mouseover on one of the data cards
* Click the "history" button (little clock with a circle with a counterclockwise arrow)
* It should now show a table of prior versions

PTV-1784 obj history fix

---

src/biokbase/narrative/tests/test_jobmanager.py

`jm.list_jobs` includes a time in the output string. A test was added to make sure it could be run twice because of a previous pass-by-reference bug. This introduced a new intermittent bug when the time between two successive `jm.list_jobs` calls would occasionally be off by 1s. A fix was made so that it would fail less, only if the two calls literally fell on different sides of an hour.
This fix is to make the test of calling `jm.list_jobs` twice deterministically always pass if the testee method works but the time is off by a second.

DATAUP-740 compare in detail ts for jm.list_jobs()

---

kbase-extension/static/kbase/js/common/ui.js
nbextensions/bulkImportCell/tabs/configure.js
nbextensions/bulkImportCell/tabs/xsvGenerator.js
test/data/kb_uploadmethods.import_fastq_noninterleaved_as_reads_from_staging.spec.json
test/data/kb_uploadmethods.import_sra_as_reads_from_staging.spec.json
test/unit/spec/nbextensions/bulkImportCell/tabs/xsvGenerator-spec.js

Adding a rough template generation form to the XSV Generator for user testing on Thursday.

DATAUP-747: rough template generation form

---

src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test_jobmanager.py

Did a brain fart on previous patch for this. If you look at the code being tested, `datetime`s or `deltatime`s are used to produce output time strings. Plus, they can repeat. So, this requires a little more sophistication to handle off-by-1s times.

DATAUP-740 Handle testing jm.list_jobs date/delta times

---

kbase-extension/static/kbase/js/common/cellComponents/filePathWidget.js
kbase-extension/static/kbase/js/common/cellComponents/paramsWidget.js
kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidget.js
kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidgetBare.js
kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidgetCompact.js
kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidgetMicro.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/sequenceInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/structInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/sequenceView.js
nbextensions/advancedViewCell/widgets/appParamsWidget.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/appParamsWidget.js
nbextensions/appCell2/widgets/configureTab.js
nbextensions/bulkImportCell/tabs/configure.js
nbextensions/editorCell/widgets/editors/readsSet/create.js
nbextensions/editorCell/widgets/editors/readsSet/editor.js
nbextensions/editorCell/widgets/editors/readsSet/update.js
nbextensions/viewCell/widgets/appParamsViewWidget.js
nbextensions/viewCell/widgets/appParamsWidget.js
test/data/testBulkImportObj.js
test/unit/spec/appWidgets/input/structInputSpec.js
test/unit/spec/common/cellComponents/paramsWidget-Spec.js
test/unit/spec/narrative_core/kbaseNarrativeAppPanel-spec.js
test/unit/spec/narrative_core/kbaseNarrativeDataList-spec.js

This adds the `paramDisplay` metadata component to the app cell and bulk import cell. Other rarely used app cell variants might not work yet. This enables the dynamic dropdown input to serialize and load its initial display value (instead of getting weird `undefined`s).
This also has some test fixes that stem from mocking dynamic services. The dynamic service client has a somewhat global cache of what services map to what URLs. When making mocks, there are a couple of test specs that use the same fake service name. If they use different urls, then when having the dynamic service url "looked up," the cache will return the other URL. 
Ideally, at the end of a test run, the cache would be invalidated. That doesn't happen, because Jasmine keeps everything in the test browser's state between …

DATAUP-639 add paramDisplay metadata

---

kbase-extension/static/kbase/js/common/errorDisplay.js
kbase-extension/static/kbase/js/common/jobs.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/bulkImportCell/bulkImportCell.js
test/data/jobsData.js
test/unit/spec/common/errorDisplay-Spec.js
test/unit/spec/common/jobs-Spec.js
test/unit/spec/nbextensions/appCell2/widgets/appCellWidget-spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

Part I of fixing app cell error display in response to public tickets
- add more tests
- convert fatalErrors to a displayable format in the app cell
- realise that a can of worms has been opened
Related Jira ticket: https://kbase-jira.atlassian.net/browse/PTV-1753

PTV-1753: fixing app cell error display, pt I

---

nbextensions/bulkImportCell/tabs/configure.js
nbextensions/bulkImportCell/tabs/xsvGenerator.js
test/unit/spec/nbextensions/bulkImportCell/tabs/xsvGenerator-spec.js

Some text changes to the UI for XSV generation:
- change the button and dialog names to refer to 'import specification' instead of CSV
- add some info about what can be done with the import spec templates
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-745

DATAUP-745: Updates to the UI based on user testing feedback

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/appWidgets2/input/dynamicDropdownInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/validation.js
package-lock.json
test/unit/spec/appWidgets/input/dynamicDropdownInputSpec.js
test/unit/spec/appWidgets/validationSpec.js

When `exact_match_on` is given to an app spec's `dynamic_dropdown_options` map, it's intended to do the following:
1. Automatically do a dynamic search using the `initialValue` as search term
2. The results will be a list of objects. Search out the first one who's `exact_match_on` key exactly matches the value (case insensitive).
3. Use that to populate the field and get the value out of it.
For example, if we're doing the scientific name search (which is the first case this is supposed to work for), and the given initialValue is "Escherichia coli K-12", then when this dropdown initializes, it starts by doing a search with "Escherichia coli K-12" as the input. When it gets a response, it looks for the EXACT match, of the term given by the `exact_match_on` field, case insensitive. In this …

DATAUP-639 add "exact_match_on" support to dynamic dropdown

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/upload/uploadTour.js
package-lock.json

What it says about - adds a blurb of text and a link to docs to the first page of the staging area tour. No real code changes.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-751
- [n/a] I have added tests that prove my fix is effective or that my feature works

DATAUP-751 add link to docs to upload tour

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/appWidgets2/input/selectInput.js
test/unit/spec/appWidgets/input/selectInputSpec.js

Dynamic dropdowns and dropdowns for new object inputs have a copy-to-clipboard button next to them. This applies the same thing to regular dropdowns. When clicked, these will copy the displayed text to the clipboard, or an empty string if nothing is selected.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-756

DATAUP-756 add copying to select dropdowns

---

kbase-extension/static/kbase/js/common/sdk.js
kbase-extension/static/kbase/js/widgets/appWidgets2/validation.js
test/unit/spec/appWidgets/validationSpec.js
test/unit/spec/common/sdk-Spec.js

Some minor changes to ready the world for select elements with multi select capabilities.

DATAUP-747: get ready for multi select

---

.github/workflows/build_and_push_image.yml
.github/workflows/build_test_pr.yaml
.github/workflows/integration_test.yml
.github/workflows/unit_test.yml
kbase-extension/static/kbase/js/widgets/appWidgets2/input/selectInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/validation.js
test/unit/spec/appWidgets/input/selectInputSpec.js
test/unit/spec/appWidgets/validationSpec.js

Enabling multi selection in the dropdown element. About ruddy time!

DATAUP-747: multi select ahoy!

---

src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/tests/data/response_data.json
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/util.py

Removing the 'updated' timestamp from jobs, which isn't used in the FE or BE.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-729

DATAUP-729: Remove unhelpful "updated" timestamp from jobs

---

kbase-extension/static/kbase/js/widgets/appWidgets2/validators/resolver.js
test/unit/spec/appWidgets/validators/resolver-spec.js

When running `spec.validateModel()`, the validation resolver needs a bit of help in directing multi selection inputs to the correct validator.

DATAUP-747: Add in special option for resolving multiselections

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/checkboxInput.js
test/unit/spec/appWidgets/input/checkboxInputSpec.js

Fixing the checkbox input so that it starts up in the correct state if the initial value is 0
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-759

DATAUP-759: fix the checkbox input

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/selectInput.js
package-lock.json
test/unit/spec/appWidgets/input/selectInputSpec.js

This adjusts selectInputs (so, all the dropdowns that aren't for workspace objects) to only render up to 20 items at once at startup. If there are more than that (like, 500+ file path options), then don't render any and only put them in the DOM when the dropdown is clicked.
The 20 is kinda arbitrary, but seemed like a decent cutoff. I don't have real statistics, but there's a touch of a performance hit when having to render all dropdown items each time, which now happens for the >20 item dropdowns.
Still, this means that for having 500 file paths in a bulk import cell, we're not shoving 25,000 `<option>` elements in the DOM. So that's helpful.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-718
- [n/a] [Version has been …

DATAUP-718 config tab performance boost part 2

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

Some old code referring to an element that no longer exists was being triggered by a narrative with a large number of data items. Removed the offending stanzas and reality was restored.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/PTV-1798

PTV-1798: datalist not loading

---

docs/testing/HeadlessTesting.md
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobmanager.py

This extracts the parts of the stalled DATAUP-729 PR that have already been OK'd into a separate PR so they can be used in a fix for DATAUP-765.
The first commit is @n1mus 's work, the second is a few bits and bobs that I added in.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-729

DATAUP-729: non job ts changes

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/common/cellComponents/filePathWidget.js
nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/bulkImportCell/tabs/configure.js
nbextensions/bulkImportCell/tabs/fileTypePanel.js
nbextensions/bulkImportCell/tabs/multiAppInfo.js
package-lock.json
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js
test/unit/spec/nbextensions/bulkImportCell/tabs/configure-spec.js
test/unit/spec/nbextensions/bulkImportCell/tabs/fileTypePanel-spec.js
test/unit/spec/nbextensions/bulkImportCell/tabs/multiAppInfo-spec.js

This addresses an error where, when either reloading a bulk import cell or loading a bulk import cell that's been shared / copied, it would always show that each tab's configuration was in error - each icon for each file type button on the left selector would have a red exclamation mark.
This happened for a couple of reasons:
1. Staging area files would have gone missing for some reason - either they weren't available, or were from another user's workspace (in the case of a copy).
2. There were objects with the same name and different data types present.
This all got triggered because when the Configure and View Configure tabs start up, they trigger an evaluation of the parameter state for the whole cell, regardless of who owns it, or what state the cell is in. The solution here was …

DATAUP-763 Bulk Import datatypes always showing error in certain states

---

kbase-extension/static/kbase/config/icons.json
test/unit/spec/util/iconSpec.js

With the last icon color change in #3076, a couple errors were introduced. This fixes the test errors and a typo in the icon file.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/UFI-22
- [n/a] (Python) I have run Black and Flake8 on changed Python code manually or with a git precommit hook

fix icon tests, typo

---

RELEASE_NOTES.md
nbextensions/bulkImportCell/tabs/xsvGenerator.js
test/unit/spec/nbextensions/bulkImportCell/tabs/xsvGenerator-spec.js

Fixes a bug where the xsvGenerator expects a paramDisplay value to be present and stalls if it is not.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-778

DATAUP-778: Fix bug where lack of a paramDisplay value was causing widget to stall

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/common/html.js
test/unit/spec/common/html-Spec.js

This sanitizes text used for display in app inputs to remove HTML. This has had the potential for damage for a long time, and now, with a recent security update to the Bootstrap framework that drives the tooltips, has started to cause problems.
This turns what would be otherwise HTML into just the plain text via the `escape` function.
ETA:
It turns out that there's 39 apps in production that'll be affected by this. The effects are minor yet annoying. For example, in the "Cluster Expression Data - K-means" text changes from "Number of Clusters (_k_)" to "Number of Clusters(<i>k</i>)". I'm of the opinion that having huge swaths of unsafe HTML injected in input text fields is not a good thing, but some basic highlighting and italicizing is probably very useful.
So version one of this PR was …

PTV-1514 clean HTML from input text fields

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

* PTV-1859 outlines a bug where a filtered data panel does not remain filtered after renaming or deleting a data object.
* No dependency changes.
Related Jira ticket: [PTV-1859](https://kbase-jira.atlassian.net/browse/PTV-1859)
[PTV-1859]: https://kbase-jira.atlassian.net/browse/PTV-1859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PTV-1859: Add search to fetchWorkspaceData to fix.

---

.github/workflows/build_and_push_image.yml
.github/workflows/build_test_pr.yaml
.github/workflows/integration_test.yml
.github/workflows/pr_build.yml
.github/workflows/unit_test.yml

A couple issues that show up downstream of the previous PR.
1. We still need some additional Docker build args for the Narrative containers, so we can't use the KBase-provided build actions. These were modified here.
2. There was some leftover debugging script that's now causing an issue.
3. The parallel PR-build script (which uses the reusable docker build actions) was made manual, but the non-manual bit was left commented out for possible further use.
4. Also fixes a bug in how image names are referenced - `narrative` vs `narrative-develop`, for example. Tests were using `narrative` while the previous PR fixed the issue and created `narrative-develop` properly. But that was masked by already having a `narrative` image for that PR while it was in progress. Tricksy!
Related Jira ticket: …

UIP-19 fix build image issues

---

RELEASE_NOTES.md
package-lock.json
package.json
src/config.json

As the title says. webdriverio has an 8.3.0 update, which dependabot chose not to tell us about until we merged the previous one. 
Related Jira ticket: https://kbase-jira.atlassian.net/browse/UIP-23
all below = n/a

bump webdriverio because dependabot is spiteful

---

RELEASE_NOTES.md
src/requirements.txt

Python deps update for April 2023.

Dependency updates for April 2023, python version

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/select2ObjectInput.js

This commit updates the select2 input widget to use refs for the selection values instead of names. This solves a problem where renamed objects disappear from selection.
Related Jira ticket: [PTV-1810](https://kbase-jira.atlassian.net/browse/PTV-1810)
1. Create a narrative with a data object and an app cell with a select2 widget.
2. Use the select2 widget to select the data object.
3. Save the narrative, reload.
4. Rename the data object to a new name.
5. (optional) Reload
6. Observe that the select2 widget reflects the updated name and displays the object version number.
[PTV-1810]: https://kbase-jira.atlassian.net/browse/PTV-1810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PTV-1810 Update select2 inputs to store ref.

---

RELEASE_NOTES.md
docs/developer/local-docker.md
kbase-extension/static/kbase/js/common/cellComponents/tabs/infoTab.js
kbase-extension/static/narrative_paths.js
package-lock.json
package.json
test/unit/karma.conf.js
test/unit/karma.local.conf.js
test/unit/spec/appWidgets/view/dynamicDropdownViewSpec.js
test/unit/spec/common/cellComponents/tabs/infoTab-Spec.js
test/unit/spec/narrative_core/kbaseNarrativeDataList-spec.js

This fixes an issue reported by a user in https://kbase-jira.atlassian.net/browse/PUBLIC-2378, reported as a broken link. The link in question should be to the Data Upload and Download Guide. The url for this guide changed when the single kbase.us public information site was reimplemented as separate documentation and marketing sites. It seems that most import apps invoked by the Import panel, and subsequently managed by the bulk import cell, include hardcoded links to this documentation.
Now, the wisdom of that aside, at least some apps still, after over a year, have now-obsolete links to that documentation. Although the response in the public ticket is that the app has not been updated, there is indeed a fix in this PR that will repair such obsolete links. The fix is to simply replace …

PTV-1877 - wrong url for data upload/download guide in bulk import cell's "info" tab

---

RELEASE_NOTES.md
src/config.json
src/config.json.templ

This updates the various Google Analytics tags to use GA4 tags. In theory, no other changes are necessary.  
Next steps include updating Auth to generate an anonymous user id, and propagating that through to GA.  
For now, however, no code changes.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/UIP-28
Hard to test - but fire up the narrative locally and ensure that a number of local google cookies get created with the proper tag.
- [n/a] My code follows the guidelines at https://sites.google.com/lbl.gov/trussresources/home?authuser=0
- [n/a] I have performed a self-review of my own code
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [n/a] My changes …

UIP-28 update google analytics id tags

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/appWidgets2/view/select2ObjectView.js
test/unit/spec/appWidgets/view/select2ObjectViewSpec.js

The short version of the PTV-1810 ticket is that when object names change or when their version gets bumped, they get lost in existing apps. The overall fix is not to store the object name in the metadata, but to store the ref. However, this means refactoring both Select2ObjectView and Select2ObjectInput to handle loading/storing refs and some other things.
This PR updates the View form of the widget that appears in the "View Configure" tab of app cells. We do a few things here:
1. accept either strings (i.e. object names) or UPAs as inputs
2. if the input is an UPA (or a workspace_name/object_name ref), look up the relevant object info and display the name from it.
3. if not, just show the given string.
It also fixes a few other small things.
1. This uses code that had a side effect of …

PTV-1810 - spruce up select2objectview, add tests

---

src/biokbase/narrative/tests/test_app_util.py

See #3320 for details
This PR creates regression tests for `app_util.transform_param_value`, which will get modified and
updated in the next PR.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/PTV-1810

PTV-1810 fix obj input 2

---

src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/data/response_data.json
src/biokbase/narrative/tests/generate_test_results.py
src/biokbase/narrative/tests/job_test_constants.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_appmanager.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py
src/biokbase/narrative/tests/test_narrativeio.py
src/biokbase/narrative/tests/test_widgetmanager.py

This PR adds the user and wsid to the job objects returned by the narrative backend.
I added typing to quite a few of the methods so the diff looks bigger than it really is.
There's still some dodgy stuff going on with the job methods, but whatever. That can go in the next PR!
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-765
- [] (JavaScript) I have run Prettier and ESLint on changed code manually or with a git precommit hook
- [] Any dependent changes have been merged and published in downstream modules
- [] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge of feature branches)

DATAUP-765: add user and wsid to job output

---

Dockerfile

A misplaced semicolon in some shell script in the Dockerfile was masking errors that might have occurred in commands earlier in the script.
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works

Fix semicolon error masking

---

.github/dependabot.yml

A bit of a tangent to the posted ticket, but still hopefully useful.
The Dependabot config docs include rules for adding multiple dependency files from multiple sources (like we're using for the production image vs. local installation of Python deps), and a configuration for grouping updates into a single PR, per package-ecosystem.
I think I have it configured right, we'll see if it works and doesn't flood us with a zillion PRs at the top of each month!
Related Jira ticket: https://kbase-jira.atlassian.net/browse/UIP-41
Most of this is N/A as no code is changed, so just deleted.

UIP-41 update dependabot config to be (hopefully) less annoying

---

Makefile
src/biokbase/narrative/common/util.py
src/setup.py

Removing some old stuff that built documentation, back in the days when documentation was something that was built (py 2.7 days). I did try to revive the documentation builder but there were still errors after updating the command to py 3, and rendering the docs as html is not particularly useful when we have them as markdown.
N/A

Removing obsolete code to build documents

---

RELEASE_NOTES.md
nbextensions/install.sh
src/biokbase/narrative/app_util.py
src/biokbase/narrative/tests/test_viewers.py
src/biokbase/narrative/viewers.py
src/biokbase/narrative/widgetmanager.py
src/requirements.txt

This PR updates the clustergrammer widget to the new version.
Next PR will be another small one with an update to the Comm class that comes up in the pytest output.
I'll check on the various python updates needed and if they look straightforward, make a PR to update them, too.
I'll update the release notes and version once all this kerfuffle is done.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/UIP-47

UIP-47: Updating clustergrammer widget to v2 and un-skip clustergrammer test

---

src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/tests/narrative_mock/mockcomm.py

Pytest was issuing a warning that `Comm()` has been replaced by `create_comm`, so I have duly updated the code.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/UIP-47
JS tests failed but the ol' faithful python tests completed successfully.

UIP-47: using newer "create_comm" function in place of antiquated "Comm()" call

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDownloadPanel.js
src/config.json
src/config.json.templ
test/unit/spec/narrative_core/kbaseNarrativeDownloadPanel-spec.js

As it says. Out with the old, in with the new.
Also removes refs to unused variables and the DIE url from the download panel, and a few minor things mentioned inline.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/UIP-44

UIP-44 Convert DIE download URL to Blobstore

---

package-lock.json
src/biokbase/narrative/app_util.py
src/biokbase/narrative/tests/test_app_util.py
src/biokbase/narrative/tests/test_appmanager.py

A warning appears when running the upload JSON object to Staging app. This skips the code that would trigger that warning. Also a bit of linting to make ruff happy.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/UIP-43

UIP-43 fix printed warning when running an app with a wildcard allowed type

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js
test/unit/spec/function_output/kbaseReportView-spec.js

Some reports have files that can be downloaded. Currently, these use the data_import_export service, which we're working on removing. This updates those links to use the Blobstore service instead. It also updates those links so they behave as links and show an HTML on hover in the usual browsers, where it didn't before.

UIP-45 update the report widget to use the new blobstore links for file downloads

---

nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/tabs/resultsViewer.js
test/unit/spec/nbextensions/appCell2/widgets/tabs/resultsViewer-spec.js

Adds a text-only output option for apps.
If the app has output widget `text-only` and includes `result_text` as an output value, then it will just display that text in the results, unformatted (save for HTML escaping).
I don't really like the magic names here, either, but they're a mimic of the report stuff. To do it the right way would be much more work (and should include changing up how we handle reports at the NMS level).

UIP-45 add text only output

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/infoTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDownloadPanel.js
test/unit/spec/common/cellComponents/tabs/infoTab-Spec.js
test/unit/spec/narrative_core/kbaseNarrativeDownloadPanel-spec.js

As reported, the Info tab in app cells running the new JSON exporter (which allows any time in an input field) renders this:
The * link goes to a broken type spec page. Since any data type is allowed there, it shouldn't really have a link at all, so this checks for a wildcard in the allowed types, and if present, doesn't list the types.

UIP-46 fix bug with displaying wildcard in data type input in app cell info tab

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDownloadPanel.js
test/unit/spec/narrative_core/kbaseNarrativeDownloadPanel-spec.js

The downloader apps (from the STAGING and JSON button options) make app cells that should (used to) get autopopulated with the object used to trigger the download, but haven't for a while. They should now do so again!
FWIW, I think this is more bleedover from moving to setting object inputs to UPAs sometime last year.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/UIP-51
- [n/a] (Python) I have run Ruff `format` and `check` on changed Python code manually or with a git precommit hook

UIP-51 fix downloader app inputs

---

test/integration/specs/narrative_basic_test.js
test/integration/wdio.conf.js

The last batch of JS updates played some havoc with the webdriverio configs.
Mainly, in a previous major version of wdio, they started wrapping the most popular browser drivers into wdio itself, which made the `wdio-chromedriver-service` obsolete. Which, it hasn't been updated in 2 years and has been marked obsolete on Github, so that's a good thing anyway.
But the configs needed a little patching and updating to tell wdio we're not using that service anymore.
Eventually, we'll need to do the same for the standalone-selenium-service (which was put in to talk to firefox), and do some fiddling with browserstack (which I don't think we're actually using).
Chrome alone gets used in GHA, so that gets priority here.
There's a bunch of other little bits of polish to add to the config situation, …

Fix WebdriverIO configs
