kbase/narrative

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

There's a deeper bug in how fast-running methods (possibly all non-app methods) get run and their outputs displayed, but this PR adds some fixes to the front end.

Fix fast-running method results.

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/page.html

New mods for the newest method gallery. Mostly works and sorta looks okay. Confidence abounds.

method gallery updated doodads

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/page.html

..in order to not have share pulldown dialog go off the right edge

swapped share and save icon positions

---

src/biokbase/narrative/common/kblogging.py
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseLogging.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseNarrative.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

added KBFail, KBError, KBFatal and some usages

---

src/biokbase/narrative/common/url_config.py
src/biokbase/narrative/services/__init__.py
src/biokbase/narrative/services/transform_service.py
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseNarrative.js

Does nothing for now, but needed for testing autofilling of UI. Will fill in details when xform service is ready.

Add tranform service py backend code

---

src/biokbase/narrative/services/transform_service.py

[Xform AssyFile->Contigs] update incoming type name

---

RELEASE_NOTES.md
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeCellMenu.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js

Still need to do method cells, but app cells alone will be useful.
Also added "running" spinner that shows whether cell is minimized or not.
Also added "error" icon for failed runs.

Minimize app and method cells

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterDropdownInput.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterTextInput.js

currently highlighted option are selected when dropdowns lose focus

---

.gitmodules
src/notebook/ipython_profiles/profile_narrative/kbase_templates/notebook.html
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/components/bootstrap-extensions/js/dataTables.bootstrap.js

Add revised fba and model output widgets to use the new "kbaseTabTable.js" output widget.  This requires PR https://github.com/kbase/narrative_method_specs/pull/86

Revised widgets

---

docker/proxy_mgr.lua
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_input/create_metagenome_set.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseAbundanceDataView.js

- text changes
- better response with nginx/lua command
- fix custom input widget to work

minor updates

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js

see https://atlassian.kbase.us/browse/NAR-492

Workspaces with proper metadata set can appear in data slideout

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeExampleDataTab.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePublicTab.js

see https://atlassian.kbase.us/browse/NAR-486

example data section for "Transcriptomes" was added

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseDomainAnnotation.js

The widget has two tabs:
1. Overview and general statistics
2. Table of domains and associated lists of genes
Each gene in a table is clickable. A new tab is created by click to visualizze all domains for a selected gene.

New implementation of the narrative widget to visualize DomainAnnotation object

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeExampleDataTab.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePublicTab.js

should address https://atlassian.kbase.us/browse/NAR-445

Better error messages in data list and data slideout

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js

together with bc07f9486cbf59, this completes https://atlassian.kbase.us/browse/NAR-483

added link to app man page from app cell

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js

fixes https://atlassian.kbase.us/browse/NAR-477

Fixed bug in propagating parameters to next step

---

RELEASE_NOTES.md
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/css/kbaseNarrative.css
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

See JIRA issue https://atlassian.kbase.us/browse/NAR-423
After a person runs an app or method, adds "suggested next steps" to the bottom of the output boxes. 
Current list set of app/methods to list is hardcoded in function called getNextSteps() in both kbaseNarrativeAppCell.js and kbaseNarrativeMethodCell.js . Only a few apps and a few methods have anything at all right now.

Suggested Next Steps after running an app or method

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/notebook.html

This should be deployed after my PR for the method store specs: https://github.com/kbase/narrative_method_specs/pull/114

adding media, phenotypeSet, and phenotypeSimulationSet output widgets

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js

should fix https://atlassian.kbase.us/browse/NAR-534

bugfix in copying some narratives

---

src/biokbase/narrative/kbasewsmanager.py
src/biokbase/narrative/monkeypatch.py
src/biokbase/narrative/ws_util.py
src/notebook/ipython_profiles/profile_narrative/kbase_templates/notfound.html

for JIRA issue https://atlassian.kbase.us/browse/NAR-552

separate page for narrative not found errors

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/css/kbaseNarrative.css
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDownloadPanel.js

Looks nicer, and download status is shown directly in the data list rather than a modal.

Updated export/download layout and behavior

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterTextInput.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDownloadPanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeSharePanel.js

and some minor display tweaks and fixes

Added front-end support for reads & models downloaders

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDownloadPanel.js

Including media, phenotypeset, phenotypesimulationset and fba.

Added support for more types for download

---

RELEASE_NOTES.md
src/notebook/ipython_profiles/profile_narrative/kbase_templates/notebook.html
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/css/kbaseNarrative.css
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseNarrative.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

All future development should use KBFatal(location, reason) to log unrecoverable errors.

Give a better error dialog on Fatal errors.

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js

Temporary spit & polish fix.
see https://atlassian.kbase.us/browse/NAR-650

Block 'Queue Position' unless the status contains the token 'queue'

---

src/biokbase/narrative/kbasewsmanager.py
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/api/NarrativeManager.js

Addresses Narrative save failures due to missing metadata keys.
See:
- https://atlassian.kbase.us/browse/NAR-657
- https://atlassian.kbase.us/browse/KBASE-1527

Save failure fix

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/page.html

Addresses https://atlassian.kbase.us/browse/KBASE-1461
(and probably others)

Force the config fetch call to not use the browser cache.

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/api/NarrativeManager.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbnetwork/css/datavis.css

Updated text in NarrativeManager's generated intro cell to reflect Nomi's changes.

Welcome cell change

---

docker/proxy_mgr.lua
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseAbundanceDataTable.js

fix for https://atlassian.kbase.us/browse/NAR-660

update sync_containers, add to REST api

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/page.html
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/css/kbaseNarrative.css
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseNarrative.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

- disable editing narr. name in view-only mode
- disable, visually, inputs in view-only
- add "Narrative" link in view-only that will show the narrative management panel when clicked
- minor tweaks to icons for user-initiated view-only mode

More changes to readonly mode

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

fixes https://atlassian.kbase.us/browse/NAR-692

Fix data list viewer bug

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

This fixes
https://atlassian.kbase.us/browse/NAR-690

Add missing data types from search filter

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterTextInput.js

related to https://atlassian.kbase.us/browse/KBASE-1586

Added proper parameter checks for max/min ints and floats in parameters

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/base/js/dialog.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/notebook/js/savewidget.js

fields in Data List and Method Panel.

Focus request and Escape button listener were added for search text

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/page.html

This is critical to reroute urls. Addresses https://atlassian.kbase.us/browse/NAR-633

Updated urls and menu for release.

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/components/jquery-extensions/js/jquery.svg.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_input/create_metagenome_set.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseAbundanceDataTable.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseAbundanceDataView.js

Bug fixes to widgets that were producing confusing or incorrect output based on different uses.
Resolve this tickets:
https://atlassian.kbase.us/browse/NAR-699
https://atlassian.kbase.us/browse/NAR-700

bug fixes to some javascript widgets

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseGenomeAnnotation.js

This modifies the kbaseGenomeAnnotation widget so that it can better display transcriptome objects.

mods to display of transcriptome objects

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePublicTab.js

Please change narrative config.json to test it (before new Search API goes into Prod) like:
-------------------------
"search": "http://dev01.berkeley.kbase.us/search/getResults",
-------------------------

Fix for search of meta-genomes in public data tab.

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePublicTab.js

https://atlassian.kbase.us/browse/NAR-762

Fix for bug with duplicated results in public data tab.

---

test/selenium_scripts/README.md
test/selenium_scripts/app.Build_and_Normalize_Metagenomic_Functional_Abundance_Data.json
test/selenium_scripts/kb-test-narrative-app.py
test/selenium_scripts/kb-test-narrative-method.py
test/selenium_scripts/method.Generate_Taxonomic_Abundance_Data.json

This adds a testing harness for the Narrative that uses Selenium to automatically start and run apps and methods. An example for an app and method is supplied.
Obviously, there's much more work to be done, but this is a start.

Added base directory for Selenium test scripts.

---

src/biokbase/narrative_method_store/client.py

This updates the Narrative Method Store client to expose three new methods: validate_method, validate_app, and validate_type.
This is pretty harmless, as it doesn't affect any existing methods. However, those are only available on ci.kbase.us right now.

Updates the narrative method store client.

---

src/biokbase/narrative/common/generic_service_calls.py
src/biokbase/narrative/services/app_service.py
src/biokbase/narrative/services/generic_service_calls.py

1) Fix for new lines in text area method parameters;
2) Fix for null values in method parameters under ref transformations.

Two fixes related to bugs in build-featureset method.

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js

The method cell had some missing dependencies that weren't always loaded up at the right time, as found on narrative-ci. This should fix it.

Missing dependencies in method cell

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterTextareaInput.js

Previously placeholder text was only supported in text field parameters, not textareas.

Added support for placeholder text in Textarea method parameters

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/api/KBaseFeatureValues.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionGenesetBaseWidget.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionHeatmap.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionMatrix.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionPairwiseCorrelation.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionSparkline.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/narrative_paths.js

do not except before PR from the expression_sprint2

pair-wise correlation and expression profiles

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterTextSubdataInput.js

This is a minor update with a couple performance improvements and bug fixes.
First, it adds a lazy fetch of the subdata, so that subdata isn't fetched on render or refresh, only when a user actually selects the method input.  This is important if many methods in one narrative use this parameter type.
Second, the autocomplete list is sorted.
Third, the parameter now supports lists/maps of scalars.  (So you can now display items for a simple list of strings, or a map<string,string>). Previously the subdata list/map had to be composed of objects.

Minor update to subdata method parameter

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js

Adam wants us to use a capital N to refer to Narratives

narratives -> Narratives

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/narrative_paths.js

This should include recent feature-value widget updates and some path adjustments to their location.

Updated submodule pointers and some paths

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionEstimateK.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionFeatureClusters.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionGenesetBaseWidget.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionHeatmap.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionMatrix.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionPairwiseCorrelation.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionSparkline.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbnetwork/css/datavis.css

Fixes a number of small bugs, and improves basic usability of a number of feature-value widgets.  These visualization tools are now in a pretty good state.
We also added a minor change to improve filtering of methods/apps in the narrative method panel.  Instead of matching absolute strings, it breaks up the query into individual words that are searched individually so, for instance, we can filter things by both type and keyword.  This also happens to address NAR-528

More updates and bug fixes to expression/feature-values widgets

---

RELEASE_NOTES.md
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/kbaseNarrative.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionEstimateK.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionFeatureClusters.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionHeatmap.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionMatrix.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionPairwiseCorrelation.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseExpressionSparkline.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeExampleDataTab.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeSideImportTab.js

Mostly minor bug fixes and general improvements to the Expression / feature-values visualizations.  This PR also addresses a Narrative issue whereby the uploader options extend pass the bottom of lower sized displays.
There is also the addition of a new widget that allows viewing a table/heatmap of expression data across all features for selected conditions, which is complementary to the existing widget that shows data across all conditions for selected features.

Improved Expression widgets

---

README.md

For some reason, the README in master and staging aren't caught up with develop. Poking this should fix it.

Tiny tweak to README so it can propagate to master correctly.

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js

Two small but critical bugfixes:
1) due to a single missing letter! (see d4300ab, completely my fault says git blame), individual step outputs of Apps were not being displayed.
2) App state saving/reloading was never working properly for apps in the error or complete state (parameters were editable again, apps did not look like they had an error after a save/reload).

Bugfix- individual app step output was hidden; App states not reloaded properly

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseBlastOutput.js

fixed score issue, alignment colors and sequence alignment issue

Updated kbaseBlastOutput.js 

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js

See JIRA ticket: https://atlassian.kbase.us/browse/NAR-643
The '## filtered' in the method panel should read '## filtered out'

Updated 'filtered' in method panel to 'filtered out'

---

src/biokbase/narrative/common/generic_service_calls.py
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js

Support for method-specs with namespaces and pointing to versioned

---

src/biokbase/narrative/common/generic_service_calls.py
src/biokbase/narrative/services/generic_service_calls.py
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseRegisterRepoState.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js

This PR has a few minor bug fixes:
- links in the methods/apps to user profiles (submitted by text) had broken links
- methods would throw an error if a service is called with no return values, that's fixed
- the sdk register repo widget now saves state (if it completes) instead of fetching the latest module state

Minor bug fixes

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/function_output/kbaseRegisterRepoState.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js

-finally added a refresh button to the data panel
-added a release/beta/dev temporary button to toggle which method versions to show (this will eventually need to be replaced or only activated in a narrative 'developer' mode)
-fixed some small issues and improved the register repo output widget

More minor improvements to support the catalog/sdk

---

old-install.sh

Revert "Update old-install.sh"

---

DEPENDENCIES

This is to trigger a CI deployment of Narrative when data_api has updates.

Create DEPENDENCIES file that includes data_api

---

.travis.yml
kbase-extension/static/custom/custom.js
src/biokbase/narrative/kbasewsmanager.py
test/unit/run_tests.py

Finally tracked this down. It was partly my mistake, partly some missing docs.

Fixed issue with narrative names not always appearing.

---

src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeSideImportTab.js

This change adds support for upload of three data types developed by ENIGMA-KBase integration project into narrative.

Added uploader for GrowthMatrix, ChromatographyMatrix and WellSampleMatrix

---

old-install.sh

Fixes problems with the local installer. It was trying to activate a virtual environment with a relative path while in a separate directory.

Installer fixes

---

src/biokbase/catalog/Client.py

Adds a couple useful methods, most importantly to list running builds.

Update catalog client to latest api

---

kbase-extension/jupyter_notebook_config.py
test/unit/karma.conf.js
test/unit/test-main.js

This will (hopefully) fix the issues with front end tests not finding the right files.

Fixing front end testing harness.

---

Dockerfile
kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/kbaseNarrativePrestart.js
kbase-extension/static/narrativeTreeMain.js

Merging this now to test changes and tags on Dockerhub.

Some changes, bumped narrative dockerfile to use narrbase 4.3

---

kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterFileInput.js

See https://atlassian.kbase.us/browse/KBASE-3365 and https://atlassian.kbase.us/browse/KBASE-3267 for details.

File upload input parameter: cleanup of shock nodes switched off, debug messages added.

---

kbase-extension/kbase_templates/tree.html
scripts/build_narrative_container.sh

Pending the go-ahead for the right path from Dan.

Update narrative_version file creation path.

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionAnalysis.js
kbase-extension/static/narrative_paths.js

viz for SDK method Evaluate Flux Balance Analysis Against Gene Expression

---

kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/api/NarrativeManager.js
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/util/bootstrapDialog.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePublicTab.js
narrative_object.spec

…  instead of skip/limit params.
Also includes a little cleanup to the Public slideout tab to use Promises.
Update - this is going to take a little refactor of the My Data and Shared With Me panels. Right now, there's no guarantee that they get everything for large (>10K elements) workspaces, or for users who have lots of workspaces.

Updated list_objects calls to use min/maxObjectID

---

RELEASE_NOTES.md
kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/kbaseNarrativePrestart.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePanel.js

A few things:
* Some updated release notes
* Made the blinking kernel button listen to the right kernel_busy event
* Tied KBase-layer startup to kernel connection. This fixes a few out-of-sync problems.
* Added tests for kernel connectivity and some rational behavior to a few kernel commands (Jobs panel, error logging)

Made initialization dependent on kernel connection, some ux fixes.

---

kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/kbaseNarrativePrestart.js
kbase-extension/static/kbase/js/widgets/function_input/kbaseInputTest.js
kbase-extension/static/narrative_paths.js

The save icon should now spin while saving and stop when done - should be more communicative (should also disable itself while saving... maybe later).
Also added a small boilerplate-ish custom input widget - kbaseInputTest.js - that fetches an object on selection, and puts an alert about what was selected.

Spinning save icon, input widget example

---

kbase-extension/static/custom/custom.css
kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeCellMenu.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js

* Removed padding between widgets and cell boundaries.
* Put method subtitle back where it belongs.
* Got rid of automatic black borders around tables.
* Added a left-side border for selected method/output cells.

Another pass at styling

---

kbase-extension/kbase_templates/notebook.html
kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/kbaseNarrativePrestart.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

This new little caret button will toggle the side panel, without putting the narrative in read only mode.

Add a toggle for the side panel

---

kbase-extension/static/kbase/js/widgets/narrative_core/catalog/app_card.js

The "more..." links from the catalog browser slideout were not correct. Also fixed a small whitespace issue in the favorites counts display that was causing some jitter when favoriting methods.

Minor catalog browser bug fixes

---

src/biokbase/catalog/Client.py

This simply adds the client methods for setting/getting favorites and fetching method run statistics so they are available in code cells.

Updated Catalog client

---

kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js

.nearest -> .closest
I love to hate that plugin.

Fix silly problem with finding a Jupyter cell from a KBase id.

---

kbase-extension/static/kbase/js/kbaseNarrative.js

Tweak load order for side panel widget.

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionFeatureClusters.js

It wasn't showing up (see also KBASE-3630).

Fix for bug in kbaseExpressionFeatureCluster widget with "Explore Cluster" menu

---

kbase-extension/static/kbase/css/kbaseEditor.css
kbase-extension/static/kbase/js/api/ModelingAPI.js
kbase-extension/static/kbase/js/widgets/function_input/editors/kbaseEditHistory.js
kbase-extension/static/kbase/js/widgets/function_input/editors/kbaseMediaEditor.js
kbase-extension/static/kbase/js/widgets/function_input/editors/kbaseModelEditor.js
kbase-extension/static/kbase/js/widgets/function_input/kbaseEditMedia.js
kbase-extension/static/kbase/js/widgets/function_input/kbaseEditModel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseModal.js
kbase-extension/static/narrative_paths.js

prototype model editor and other minor edits

---

kbase-extension/static/kbase/js/widgets/narrative_core/catalog/app_card.js
kbase-extension/static/kbase/js/widgets/narrative_core/catalog/kbaseCatalogBrowser.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js

Fixes a couple bugs:
- In some cases the app catalog items would be hidden when the methods are refreshed
- my favorites icon when methods are in multiple categories is shown properly
- inactive legacy apps are hidden properly based on categories

Minor catalog slideout bug fixes

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeExampleDataTab.js

Removed AssemblyInput and community types, and fixed a bug causing some sections to be hidden even if there were some examples in that section.

Minor example data tab fix

---

kbase-extension/static/kbase/js/widgets/function_input/kbaseSampleProperty2DPlotInput.js

side effect of switching to Config last night...

Small typo corrected in SampleProperty2DPlotInput (does not work without it)..

---

kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/config.json
kbase-extension/static/kbase/js/widgets/narrative_core/catalog/kbaseCatalogBrowser.js

Since this lives in a form (for pretty styling), it needs the enter key disabled. This also disables the Jupyter command mode keyboard manager while that input box is focused.

Tweak the catalog browser search box

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseViewLiveRunLog.js

Also lower refresh rate to every 2s (instead of every second).

Log fetching works, so remove debug messages

---

bower.json
kbase-extension/kbase_templates/page.html
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/util/bootstrapDialog.js
kbase-extension/static/kbase/templates/update_dialog_body.html
kbase-extension/static/narrative_paths.js

Also tinkering with templating dialog HTML.

Added Shutdown menu option

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePublicTab.js

Public data from workspaces were not showing- this fixes the basic problems.

Fixes to side public tab

---

RELEASE_NOTES.md

Adding a minor fix to the actual next narrative deploy...

Small changes to staging

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js
scripts/build_narrative_container.sh

Found another missing handlebars dependency that might cause problems (similar to the previous PR), and updated the build container image script to put the data source config in the webroot on completion.

Fix dependency and update build script

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionAnalysis.js

This is just changing text of the kbaseExpressionAnalysis legend.  I know I missed the "last call", but it is just a text change, if you could merge.  This line had a bad typo https://github.com/kbase/narrative/compare/fix-legend?expand=1#diff-7cb269041e5febb6e6444eeaa053ad8aL99 .

just changing text

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotation.js

Mods to the genome annotation viewer widget to cause all objects with the domain "Eukaryota" (whether transcriptome or not) to use the plants-style view.
This style also does not display the subtype value in the overview tab.
There was other talk about renaming labels, but for now I'm kicking that can down the road, this just expands the domain.

mods to expand plant-style view to eukaryota

---

kbase-extension/static/kbase/js/widgets/function_input/kbaseHomologySearch.js
kbase-extension/static/kbase/js/widgets/function_input/kbaseNarrativeMethodInput.js
kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterAjaxTextSubdataInput.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseBlastOutput.js
kbase-extension/static/narrative_paths.js

- bug fixed and improved Homology method output widget
- added another input type (kbaseNarrativeParameterAjaxTextSubdataInput.js), which basically loads dropdown options via ajax call.
- using new input method, homology method UI can add public genome name as an input.

Homology SDK method update

---

docker/proxy_mgr.lua

fix session_lock.unlock usage to session_lock:unlock
refine placement of unlock to improve clarity and reduce code
The first is a just a lua newbie mistake which caused a 500 on the first access for a user (ok after that). How that got by testing ...

fix bug in unlock usage

---

src/biokbase/service/Client.py

Example of usage in Narrative code cell (this is case of non-dynamic service):
```
from biokbase.service.Client import Client
cl = Client("https://ci.kbase.us/services/ws", use_url_lookup=False)
cl.sync_call("Workspace.list_workspace_info", [{'perm' : 'w'}])[0]
```

Generic python client is added (for dynamic services testing).

---

kbase-extension/static/kbase/config/upload_config.json

Basic entries in the upload config for KBaseGenomeAnnotations.Assembly and KBaseGenomeAnnotations.GenomeAnnotation.

reactivating new Genome types

---

kbase-extension/static/kbase/config/data_source_config.json

Adding new reference genomes and ontology to public data tab in narrative.

Adding new reference genomes and ontology

---

kbase-extension/static/kbase/js/common/fsm.js
kbase-extension/static/kbase/js/common/monoBus.js
kbase-extension/static/kbase/js/common/unodep.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
kbase-extension/static/narrative_paths.js
nbextensions/methodCell/widgets/fieldWidget.js
nbextensions/methodCell/widgets/input/singleSelectInput.js
nbextensions/methodCell/widgets/jobLogViewer.js
nbextensions/methodCell/widgets/methodCellWidget.js
nbextensions/methodCell/widgets/methodExecWidget.js
test2/specs/active/monoBus-Spec.js

initial integration of job log viewing into method cell (extracted from job status widget) [wip, totally]
enhancement of message bus to support sticky messages, listener removal
code cleanup
ui cleanup
fixes
CDN module paths isolated for easier config

Method cell updates

---

kbase-extension/static/kbase/js/common/fsm.js
kbase-extension/static/kbase/js/common/monoBus.js
kbase-extension/static/kbase/js/common/unodep.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
kbase-extension/static/narrative_paths.js
nbextensions/methodCell/widgets/fieldWidget.js
nbextensions/methodCell/widgets/input/singleSelectInput.js
nbextensions/methodCell/widgets/jobLogViewer.js
nbextensions/methodCell/widgets/methodCellWidget.js
nbextensions/methodCell/widgets/methodExecWidget.js
test2/specs/active/monoBus-Spec.js

Whenever I see `fsm.js` I read `flying_spaghetti_monster.js`
(yes, I know it's finite state machine. 😄 )

Vis cell refactor (resolving @eapearson conflicts)

---

kbase-extension/static/kbase/config/data_source_config.json

Changes to fix new reference genomes in narrative

Changes to fix new reference genomes in narrative

---

bower.json
kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionVolcanoPlot.js
kbase-extension/static/narrative_paths.js

@briehl please review and merge.

support for interactive volcano plot

---

RELEASE_NOTES.md
kbase-extension/static/kbase/css/kbaseNarrative.css
src/biokbase/narrative/__init__.py
src/config.json

There were overlapping sort icons in datatables. That was obnoxious, yet nobody reported it or even brought it up...

Fixed sort icons in datatables.

---

kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/js/widgets/narrative_core/ipythonCellMenu.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCellToolbarMenu.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeOutputCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
kbase-extension/static/narrative_paths.js
src/biokbase/narrative/widgetmanager.py

Viewer widgets should get their own code cell representation now.

Update widget viewers.

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSideImportTab.js

(until it's wired up with job panel).

Temporary import job status cell shows up in Narrative for SDK methods

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/narrativeViewers.js
src/config.json

Better error messaging when failing to load a viewer

---

kbase-extension/static/kbase/js/widgets/appWidgets/input/singleSubdata.js

It's using this new feature added into NMS: https://github.com/kbase/narrative_method_store/pull/35

First version of support for generic functions in sub-data selection.

---

RELEASE_NOTES.md
kbase-extension/static/custom/custom.css
kbase-extension/static/kbase/js/common/appUtils.js
nbextensions/appCell/main.js
nbextensions/appCell/widgets/appCellWidget.js
nbextensions/viewCell/main.js
nbextensions/viewCell/widgets/viewCellWidget.js
src/config.json

* Restored correct icons in various cells
* Changed "app ref" to "more..." in app heading bar
* fiddled with cell container css a touch (got a padding again on the right side, so it doesn't look like everything leans right)

Some UI fixes

---

kbase-extension/static/kbase/js/api/GenericClient.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionGenesetBaseWidget.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionMatrix.js

Also switching KBaseFeatureValues widgets back to dynamic service.

Fix for bug in Generic Client related to wrong promise in URL lookup.

---

RELEASE_NOTES.md
kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/singleSubdata.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCellToolbarMenu.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
nbextensions/appCell/widgets/appCellWidget.js
nbextensions/appCell/widgets/appOutputWidget.js
src/biokbase/narrative/contents/narrativeio.py
src/config.json

Saving should now properly make metadata for the dashboard.

Fix Narrative metadata

---

RELEASE_NOTES.md
scripts/install_narrative_docker.sh
src/config.json

- the docker install config had not been updated with the extensions, now it is
- version and release notes bumped up to 3.0.0-alpha-13

Bump up version and fix config

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotationAssembly.js
kbase-extension/static/narrative_paths.js

Basics are functional, but still needs some styling improvements.  Also need to fix an intermittent Assembly server error, but that should be independent of this widget.  We will probably add more to this PR today.

Narrative viewer for the new GenomeAnnotation.Assembly type

---

narrbase-image/Dockerfile

This fixes a build issue for narrbase.  I need this to get an automated build on dockerhub.

Narrbasefix

---

kbase-extension/static/kbase/js/common/props.js
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/appWidgets/input/multiCustomSelect.js
kbase-extension/static/kbase/js/widgets/appWidgets/paramInputResolver.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
nbextensions/appCell/widgets/appCellWidget-fsm.js
nbextensions/appCell/widgets/appCellWidget.js
nbextensions/appCell/widgets/appExecWidget.js
nbextensions/appCell/widgets/appOutputWidget.js
src/biokbase/narrative/handlers/narrativehandler.py
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/jobmanager.py
test2/specs/active/props-Spec.js

Primarily job cancellation improvements
- new canceling and launching states
- simplified launch events
- remove job deletion logic from front end
- fix some logging usage
- issue 401 on narrative get if no cookie

Job cancellation improvements

---

nbextensions/appCell/widgets/appCellWidget.js
nbextensions/appCell/widgets/appOutputWidget.js
nbextensions/outputCell/main.js
nbextensions/outputCell/widgets/outputCell.js

implement the typical main + widget pattern for output cell to help
isolate certain cell handling hooks like deletion

fix output cell deletion regression

---

kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js
nbextensions/appCell/widgets/appCellWidget.js
test/unit/run_tests.py

Currently just a checklist of things to address re: app versions (@msneddon @rsutormin @eapearson)

Fixing App version confusion

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeComparison.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseTree.js

Also there is some clean up in mouse/tooltip interactions in two widgets related to recent change in output cell UI components (in particular it's "position: relative" style added in some top level output cell panel).

Switching to genome annotation API in proteome comparison viewer.

---

kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/css/kbaseTour.css
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/tour.js
kbase-extension/static/kbase/templates/tour/tour_panel.html
test/unit/karma.conf.js
test/unit/run_tests.py
test/unit/spec/tourSpec.js
test/unit/test-main.js

Changed around colors, etc., in bootstrap tour. Added test spec.

Tour styling

---

.gitignore
docker/lua-dependencies.txt
docker/proxy_mgr.lua
docs/design/startup-errors.md
docs/install/deployment_eap.md
kbase-extension/kbase_templates/page.html
kbase-extension/static/kbase/css/buttons.css
kbase-extension/static/kbase/js/common/monoBus.js
kbase-extension/static/kbase/js/common/ui.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
nbextensions/appCell/widgets/appCellWidget-fsm.js
nbextensions/appCell/widgets/appCellWidget.js
nbextensions/appCell/widgets/appParamsWidget.js
nbextensions/appCell/widgets/jobLogViewer.js
src/nginx/default
src/nodejs/NarrativeServer/admin.js
src/nodejs/NarrativeServer/auth.js
src/nodejs/NarrativeServer/htdocs/index.html
src/nodejs/NarrativeServer/htdocs/main.js
src/nodejs/NarrativeServer/main.js
src/nodejs/NarrativeServer/narrativeapp.js
src/nodejs/NarrativeServer/nbproject/project.properties
src/nodejs/NarrativeServer/nbproject/project.xml
src/nodejs/NarrativeServer/package.json
src/nodejs/NarrativeServer/reset-docker.sh
src/nodejs/NarrativeServer/templates/containers.html
src/nodejs/NarrativeServer/utils.js
src/nodejs/narrative.conf

Initial work for the UI sprint app cell refactoring
- based on the new design
- gathers together various widgets
- works
Still todo (some will happen by tomorrow, some next week)
- align closer with the mockups (e.g. hide some buttons, replace icons with labels)
- test with all types of error conditions
- split all inline widgets into separate files (the app cell widget is too big and cluttered)
- and at the same time, code cleanup
The loading page fixes are modest. I have more work coming later based on this which makes further improvements and better integrates into kbase-ui.

UI sprint app cell refactor, some loading page fixes

---

kbase-extension/static/kbase/js/common/ui.js
nbextensions/appCell/widgets/appCellWidget-fsm.js
nbextensions/appCell/widgets/appCellWidget.js
nbextensions/appCell/widgets/appParamsWidget.js
nbextensions/viewCell/widgets/appParamsWidget.js

refactored (minor) action button configuration, simplifies fsm config

"tab" buttons now utilize text not icon

---

kbase-extension/static/kbase/js/api/AssemblyAPIClient.js
kbase-extension/static/kbase/js/api/GenomeAnnotationAPIClient.js
kbase-extension/static/kbase/js/api/GenomeSearchUtilClient.js
kbase-extension/static/kbase/js/api/TaxonAPIClient.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotation.js
kbase-extension/static/narrative_paths.js

Not fully complete, but opening the PR so people can start testing in CI.  It adds a new tab to the genome widget (all the old behavior is still functional).

Genome Widget update

---

kbase-extension/static/kbase/js/api/GenomeSearchUtilClient.js
kbase-extension/static/kbase/js/widgets/function_output/contigBrowserPanel.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotation.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotationAssembly.js
kbase-extension/static/kbase/js/widgets/kbaseTabs.js

Still missing contig viewer table, but basics for features are there.  Opening this now to get some eyes on it in CI.

Updated Genome viewer widget

---

kbase-extension/static/custom/custom.css
kbase-extension/static/kbase/css/appCell.css
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCellToolbarMenu.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
nbextensions/appCell/widgets/appCellWidget-fsm.js
nbextensions/appCell/widgets/appCellWidget.js

Update button/tab layout, color matching, structural changes to enable css settings, app cell uses all available cell area.
Still another round required today, but closer.

app cell layout improvements - closer to new design

---

kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/tour.js
kbase-extension/static/kbase/templates/tour/tour_panel.html

Still a few minor things to finish before merging. But mostly there!

Updated tour to (mostly) match Ben's script.

---

kbase-extension/static/custom/custom.js
kbase-extension/static/kbase/css/appCell.css
kbase-extension/static/kbase/css/kbaseJobLog.css
kbase-extension/static/kbase/js/common/fsm.js
kbase-extension/static/kbase/js/common/ui.js
kbase-extension/static/kbase/js/widgets/appWidgets/fieldWidget.js
kbase-extension/static/kbase/js/widgets/appWidgets/infoPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCellToolbarMenu.js
nbextensions/appCell/main.js
nbextensions/appCell/widgets/appCellWidget-fsm.js
nbextensions/appCell/widgets/appCellWidget.js
nbextensions/appCell/widgets/appInfoDialog.js
nbextensions/appCell/widgets/tabs/errorTab.js

fixes for:
- cell deletion sometimes fails (unexpected cell state)
- cell init error if unsupported initial state (cell created during dev churn)
- job log line count overflowing for long logs
changes:
- fatal-error -> internal-error, better handling of this state (tip)
- app cell style "improvements"
- code cell title support
- app info into menu (from "more..." link)
- internal improvements to support the above
as usual, feel free to change any of the somewhat subject improvements.

Fixes and improvements:

---

bower.json
kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionVolcanoPlot.js
kbase-extension/static/narrative_paths.js

@scanon - I'm assuming you want to keep appdev on master, otherwise, we can merge this elsewhere.
This should bring the kbaseExpressionVolcanoPlot widget from the develop branch (with a slightly adjusted widget style) to the master branch, with no other changes. It also updates the Bower file to include that widget's external dependencies - jquery.tipsy and bootstrap-slider.

Volcano plot widget for appdev

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotation.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotationAssembly.js

Some minor styling improvements, plus assembly widget always displays correct version.

Minor genome/assembly widget updates

---

nbextensions/appCell/widgets/appCellWidget-fsm.js

I just wanted to edit "You may edit the parameters for this App. All required parameters are not currently entered. When they are complete, you will be able to run the app" to make it clearer, but then I made a bunch of other very minor changes to other messages (capitalizing App, using periods consistently, etc.). Nothing major.

Some improvements to messages in app cells

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js
nbextensions/appCell/widgets/tabs/resultsTab.js

Red Team (GO TEAM RED!) new report view object.
This'll embed an HTML view and file links, if present into the output of a Report object.
Please merge and deploy ASAP.

New report view

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js
nbextensions/appCell/widgets/appCellWidget.js

html files can now be downloaded, if not opened in a new window yet.

html links

---

src/biokbase/narrative/exporter/run_narrative.py
tox.ini

Moved run_narrative script from RunNarrative repo into the narrative repo, along with tox.ini file

Added helper functions to the execute preprocessor to run narrative from cmdline

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js

Just changed a section header name from HTML Files -> Links

changed header name from HTML Files -> Links

---

docker/notelauncher.lua
docker/proxy_mgr.lua

This allows the image to be set in the nginx init.  This helps support legacy narratives.
@briehl and @sychan  Can you review?

Add support to specify narrative image in the config block.

---

.travis.yml
docs/install/local_install.md
kbase-extension/static/kbase/js/revised-widgets
kbase-extension/static/kbase/js/ui-common
scripts/install_narrative.sh
scripts/install_narrative_docker.sh

1. Removes `git submodule init/update` commands during install.
2. No longer installs data api local scripts (those are now captured in dynamic service calls).
3. Little bit of Travis directive adjustment so it'll hopefully cache JS objects.

Some post-submodule cleanup

---

kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSideImportTab.js
src/config.json

Staging hotfix types

---

kbase-extension/static/kbase/js/widgets/narrative_core/catalog/kbaseCatalogBrowser.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodPanel.js
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/tests/test_appmanager.py

See tickets:
https://atlassian.kbase.us/browse/TASK-138 (running app problem with validator) and
https://atlassian.kbase.us/browse/TASK-139 (inserting app cell from the catalog slideout)
TASK-138 still needs some stronger tests written. I'll work on those now, but this should be ready to merge.

Fix ci problems

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
src/biokbase/narrative/__init__.py
src/config.json

The red Add Data button got itself broken. Neat.

Fix Add Data button

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
nbextensions/editorCell/main.js
nbextensions/editorCell/widgets/editorCellWidget.js
nbextensions/editorCell/widgets/editors/readsSetEditor.js
nbextensions/editorCell/widgets/editors/readsSetEditor2.js

Forked the readsSet editor into widgets/editors, the generic version still exists as well.
New editors can be created by copy/pasting the readsSetEditor.js file, and adding the dispatch logic into main.js

Dynamic dispatch on editor based on input widget value

---

RELEASE_NOTES.md
kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/util/display.js
kbase-extension/static/kbase/js/util/icon.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseReadsViewer.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
src/config.json

Putting in some suggested changes, and getting it up to eslint snuff, and fixing errors.

[WIP] Reads view update

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseReadsViewer.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

Changes to make the reads view look like the reads set view.

Reads view update

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js

Updates the report view to use the html service. This'll allow the links section to open up in new windows.
Also breaks apart the summary into a separate Summary section.
It should work, but it needs more eyeballs on it and further testing with real methods to confirm it's properly functional.

report view updated to use html service

---

kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataCell.js
kbase-extension/static/narrative_paths.js

JIRA Issue: TASK-130 https://atlassian.kbase.us/browse/TASK-130

Display generic object metadata in narrative widget

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDownloadPanel.js

Please do not merge until this change (https://github.com/kbase/data_import_export/commit/f79e6e17f2d2c1f6d69b2427c01fef9cdd96f2a5) is redeployed in CI.

Removing KBase AuthTokens from URLs in Download panel.

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/singleObjectRefInput.js
nbextensions/editorCell/widgets/editorCellWidget.js

@eapearson 's PR #846 re-introduced the removed submodules, which were breaking tests. This is an exact copy of that PR, but without the renewed module info.

Reads set editor datapanel

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeComparisonViewer.js

Fix for bug with Function links in kbaseGenomeComparisonViewer.

---

kbase-extension/static/kbase/css/appCell.css
kbase-extension/static/kbase/js/widgets/appWidgets/input/autocompleteSingleTextInput.js

Better styling on the autocomplete drop down.
Also now searches on both public and private data, broken apart.

better styling on autocomplete

---

kbase-extension/static/kbase/js/common/sdk.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/autocompleteSingleTextInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/multiStructInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/singleSelectInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/structInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/inputParamResolver.js
kbase-extension/static/kbase/js/widgets/appWidgets2/paramInputResolver.js
nbextensions/appCell2/appCell.js
nbextensions/appCell2/main.js
nbextensions/appCell2/widgets/appCellWidget.js

- Jim's autocomplete needed to be merged into the code tree which supports grouped params
- Also hooked the autocomplete selection event to the parameter change event to propagate entry into app cell
- remove "enabled" checkbox from required grouped param
- ignore "advanced" setting for parameters inside group

fix autocomplete, grouped param tweaks

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/singleSubdata.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionFeatureTableHeatmap.js
nbextensions/viewCell/widgets/viewCellWidget.js
src/biokbase/narrative/app_util.py
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/tests/test_app_util.py
src/biokbase/narrative/tests/test_appmanager.py

Corresponding change in FeatureValues method-spec is here: https://github.com/kbaseapps/FeatureValues/commit/2825d3190ce1664e079aefbb69f15038ec3563f0

Fixing KBASE-3659 (bug in View Expr. Matrix Heatmap In Feature Table).

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/singleSelectInput.js

Saving and reloading was a little tricky, but works also.

Update string dropdown input to use select2

---

kbase-extension/static/kbase/config/icons.json
kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/util/icon.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

Adjustments to the hierarchical view.
1. Dan was right - we should have a toggle button to show set members, not just click on the icon. So it does that now, and clicking the icon always puts the object in the page.
2. Shrunk the stacked icons for sets so they take up the same width as the others.
3. Added a reads set icon - just the same as the reads icon.

Change data panel hierarchical view

---

kbase-extension/static/kbase/js/widgets/narrative_core/catalog/kbaseCatalogBrowser.js

See https://kbase-jira.atlassian.net/browse/KBASE-4579

Set catalog browser default sorting to "Category"

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
kbase-extension/static/kbase/templates/data_staging/ftp_file_table.html

Removed the non-functional 'imported as' column and replaced with an 'import as' column.
That new column gives an option of what object types to upload as, inserts an app, and fills out some fields for you.

Added auto-app-insertion and form fill-out to staging area.

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDownloadPanel.js

@briehl: Bill, please DO NOT MERGE this PR until Keith redeploys data_import_export in CI!!!

Support for reference paths in download panel.

---

kbase-extension/static/kbase/config/data_source_config.json

This is a simple change, but needs to be done before PAG (mid-January)

Updating so that Phytozome genomes appear in other environments

---

RELEASE_NOTES.md
src/biokbase/narrative/__init__.py
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/tests/test_appmanager.py
src/config.json

This fixes a couple problems with how app parameters get validated, especially those that make use of randomized input strings.
Also added more tests to that module.
Note that some of this will need to be tweaked when merging develop up to staging, but that'll be handled elsewhere.

Address 'generated_value' bug

---

kbase-extension/static/custom/custom.js

See:
https://kbase-jira.atlassian.net/browse/KBASE-4752

Limit Markdown cell titles to not include newlines or paragraph symbols

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionVolcanoPlot.js

The slider value wouldn't show up all the way at the max, so this resolves it.
The values are still imprecisely beyond 2 decimal places.

fixed the slider value on the volcano plot

---

kbase-extension/static/kbase/js/widgets/function_input/kbaseNarrativeMethodInput.js
kbase-extension/static/kbase/js/widgets/function_input/parameter_input/kbaseNarrativeParameterTextInput.js

A "select" tag should have been an "input" tag for those that don't use select2.

Fix problem with certain input fields in importers

---

kbase-extension/static/kbase/config/feature-config.json

Needed for promoting up to next/appdev.

Re-disable the staging area.

---

kbase-extension/static/kbase/js/common/sdk.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/sequenceInput.js

- pass correct default values through to sub-widget
- ensure validation after widget initialization

Fix sequence default behavior

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js

Only adds in the Summary or Report sections if there is actual content in them; changes the text of the placeholder in Links

filters out empty sections

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js

filters out the download and links sections if not available, adds in default text if no summary or html.

Report view

---

nbextensions/viewCell/widgets/appParamsWidget.js

- was breaking subdata widget because the new paramter routing in the appCell had not been implemented in the viewCell.

add missing parameter routing

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionVolcanoPlot.js
kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseCummerbundPlot.js

adds missing incrementation of magic variable.
accidentally brought along the cummerbund impossible error as well. Sorry. :-/

Volcano table fix

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/floatInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/intInput.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js

- fix float and int inputs -- they didn't like the value 0
- add support for label in report view

Fix float/int input, support label for report view

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/structInput.js

- it was an uintuitive and poorly labeled checkbox
- not is a button whose label correctly reflects the consequence of the button-press, and a dialog to help prevent unintentionally losing parameter data.
fixes https://kbase-jira.atlassian.net/browse/KBASE-4870

improve struct parameter enable/disable control

---

RELEASE_NOTES.md
kbase-extension/kbase_templates/page.html
kbase-extension/static/kbase/config/staging_upload.json
src/biokbase/narrative/__init__.py
src/config.json

Added upload apps for SRA reads and genbank genomes
Also fixed (suppressed) a problem with the ipywidgets loader being noisy and complaining that it can't make a menu item.

Added staging upload apps

---

kbase-extension/static/kbase/config/staging_upload.json

Fixes uploader for SRA reads and genbank files

Changed config for staging area upload methods.

---

kbase-extension/static/kbase/js/common/sdk.js
kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidgetCompact.js
kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidgetMicro.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/sequenceInput.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
scripts/build-from-pr.sh
src/biokbase/narrative/jobs/jobmanager.py

- Takes care of https://kbase-jira.atlassian.net/browse/TASK-378, ensuring that sub-input widgets properly enforce and display the "required" constraint.
- Fixes label-display in report viewer
- Fixes import job panel not updating job status

lists of inputs enforcing "required" constraint, and couple of fixes

---

RELEASE_NOTES.md
kbase-extension/kbase_templates/page.html
kbase-extension/static/kbase/css/kbaseNarrative.css
src/biokbase/narrative/__init__.py
src/config.json

Help menu has the tour, link to the narrative guide, and link to Contact us.
Some work to support tickets:
https://kbase-jira.atlassian.net/browse/KBASE-4937
https://kbase-jira.atlassian.net/browse/KBASE-4355 (indirectly)

Made a help menu, migrated some options there from the hamburger menu.

---

kbase-extension/static/kbase/js/widgets/appWidgets2/view/checkboxView.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/fileView.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/floatView.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/intView.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/select2ObjectView.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/selectView.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/taxonomyRefView.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/textView.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/textareaView.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js

- commonly used view widgets properly defanged: read-only and no change-detection code
- report viewer iframe could render scrollbar in some circumstances resulting to jittering

Fix parameter view widgets, and report viewer iframe issue

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionVolcanoPlot.js

Minor text change Log2 to Log2 FPKM+1

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/select2ObjectInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/select2ObjectView.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/sequenceView.js
src/biokbase/narrative/app_util.py

- addresses https://kbase-jira.atlassian.net/browse/TASK-426 in which object ref inputs in lists were not showing their value in view-only mode
- addresses bug reported via slack (Shinjae) that object refs in lists within grouped parameters were causing a Narrative back end error.

Fix bug in view-only object input, repeated object inputs within grouped parameter

---

kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseRNASeqAnalysisNew.js

Changing from name -> id screwed up the display.
Fortunately, we were already loading the info for the objects, so just re-tooled slightly to display something else.

fixed display of sample - now name again, instead of id

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseReportView.js
nbextensions/appCell2/widgets/tabs/resultsTab.js

- the flag was not being set in the app cell
- the object list link was also a bar not a pointer
- ui needs work -- probably should be a button, not link, and scroll to the object inserted in the narrative.

enable output objects in report viewer

---

nbextensions/viewCell/widgets/appParamsWidget.js

Should fix a problem with viewer apps, eg. the Volcano viewer.

Fixed missing parentBus issue in view cell

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

"Show Methods with this as input" -> Show Apps with this as input

Methods -> Apps

---

Dockerfile

typo in dockerfile

---

kbase-extension/static/kbase/js/util/timeFormat.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSharePanel.js

* Safari timestamps - https://kbase-jira.atlassian.net/browse/NAR-780 , also reporting wrong time.
* Safari sharing panel should accept inputs.

Browser compatibility fixes

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/uploadTour.js

Will want to revisit these instructions later, but I made some minor improvements.

Some improvements to data staging tour

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionVolcanoPlot.js

The slider action needed to be debounced to ensure that the final value displayed in the button is accurate.
Side note - the cnt variable here is effectively used as a global, so several different functions are fiddling with it and using it as a side effect for their own purposes. This should be refactored...just not right now.

debounces the slider function

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionVolcanoPlot.js

Same as the last one...there's just another slider that also needed to be debounced.

needed another debounce

---

src/config.json

It was just missing this config line.

Fix missing icons in appdev.

---

kbase-extension/static/kbase/js/common/pythonInterop.js
kbase-extension/static/kbase/js/common/sdk.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/sequenceInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/structInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/validators/struct.js
kbase-extension/static/kbase/js/widgets/appWidgets2/validators/text.js
src/biokbase/narrative/app_util.py
test/unit/spec/erik/pythonInterop-Spec.js

While implementing the testing narrative requested in 
https://kbase-jira.atlassian.net/browse/KBASE-4989
several previously un-encountered parameter states were found to be incorrectly handled. More specifically interactions between constraints on multiple and grouped parameters were not always handled well. 
In addition the regular expression constraint on text inputs, unused in the wild, was tested and fixed in the front and back end code.
A testing app 
https://ci.kbase.us/#catalog/apps/eapearson_GroupedParametersTest/validate_seq_params
proved very useful in teasing out these cases.

Improve parameter input behavior 

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
kbase-extension/static/kbase/templates/report_error_button.html

See https://kbase-jira.atlassian.net/browse/KBASE-5008

Fix copying workflow in view only mode

---

kbase-extension/static/kbase/js/util/display.js

Please don't ever use help @ kbase as the contact. It should be http://kbase.us/contact-us/

Updated contact info

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

See - https://kbase-jira.atlassian.net/browse/TASK-452

Data panel should now show download button in read only mode.

---

kbase-extension/static/kbase/config/data_source_config.json

Corrected the stupid typo.

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseTaxonomyBrowser.js
kbase-extension/static/narrative_paths.js

It ain't pretty yet and is missing pieces, but it's something.

rough initial tax viewer. Missing methods AND HARDWIRED TAXA_REF

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSharePanel.js

The share panel input box width is really narrow. This fixes that.

Fix the sharing panel width layout.

---

kbase-extension/static/kbase/config/data_source_config.json
kbase-extension/static/kbase/config/feature-config.json
kbase-extension/static/kbase/js/util/string.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePublicTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
kbase-extension/static/kbase/templates/data_slideout/action_button_partial.html
kbase-extension/static/kbase/templates/data_slideout/object_row.html
src/config.json

Makes JGI data available from the Public data dropdown.
This is still a work in progress, but functional enough to put out there for some feedback.

JGI Public Data 

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
kbase-extension/static/kbase/templates/job_status/log_panel.html

- Was requiring user click the play button to get the log to appear, counterintuitive
- Also the "next" button was not working correctly
- Now initializes the job status and log, and starts polling if necessary
- Also refactor job log buffer code into separate internal module

Improve job log viewer behavior

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/customInputs/PetInput.js
kbase-extension/static/kbase/js/widgets/custom/CustomOutputDemo.js

- it is breaking upon insertion. 
- should really be made more interesting as a base demonstration, but at least not breaking is an improvement.

Fix demo/testing custom input widget

---

README.md
docs/install/local_install.md
kbase-extension/static/kbase/config/staging_upload.json
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/util/bootstrapDialog.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSharePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePublicTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
kbase-extension/static/narrative_paths.js
scripts/install_narrative.sh

Also brings in some other minor fixes.
* a potential crash bug if the data source config isn't found
* adds a bash header to install script

Fix sharing panel again

---

docker/proxy_mgr.lua

- do not merge as-is
- for bill to pickup or not, untested (since the original work months ago).
- the diff with develop is just about the same

Narrative loading changes [wip]

---

RELEASE_NOTES.md
bower.json
package.json
src/biokbase/narrative/__init__.py

Bump version and release notes

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseBinnedContigs.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotationAssembly.js
kbase-extension/static/narrative_paths.js

It's really really not finished, but we need to do a demo soon.

First pass at binned contigs widget

---

kbase-extension/kbase_templates/page.html
kbase-extension/static/kbase/css/kbaseStylesheet.css
kbase-extension/static/kbase/js/widgets/dynamicTable.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseBinnedContigs.js

Official first version - no plots or anything, but fancy dynamic-service-powered tables.

Binned Contigs Viewer

---

Dockerfile
Makefile
package.json
test/functional/spec/smoketest/loadLoginPageSpec.js

Pull request for fixes to Narrative:
1) Update Dockerfile for versions of beautifulsoup4 and pandas so that they now run once again
2) Pin geckodriver and selenium to versions that work with firefox properly

Pandas fix TASK-674 #start-review

---

RELEASE_NOTES.md
kbase-extension/kbase_templates/page.html
kbase-extension/static/kbase/js/widgets/dynamicTable.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseBinnedContigs.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotationAssembly.js
kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseRNASeqAnalysisNew.js
kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseRNASeqPieNew.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js
kbase-extension/static/narrative_paths.js
package.json
src/biokbase/narrative/__init__.py
src/config.json
test/functional/spec/smoketest/loadLoginPageSpec.js

Also includes cherry-picked widget updates for deployment tomorrow, from these PRs:
#1055 
#1052

Update hamburger menu search to the right path

---

kbase-extension/static/kbase/css/appCell.css
kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidget.js
kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidgetCompact.js
kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidgetFull.js
kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidgetMicro.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/floatInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/intInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/sequenceInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/structInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/unused/dataAttachmentInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/unused/multiCustomSelect.js
kbase-extension/static/kbase/js/widgets/appWidgets2/parameterSpec.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/floatView.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/intView.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/sequenceView.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/structView.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/unused/multiCustomSelect.js
nbextensions/editorCell/styles/main.css

Includes:
- mouseover highlight of rows
- removes most borders around parameter elements
- changes the style of the feedback indicator to a line instead of an arrow
- moves the 'more info' button per parameter to a click on the parameter field name
- remove numbering in list inputs

In progress updates to App parameter styling TASK-701

---

bower.json

The kbase-common-js dependency seems to be in a strange version state on bower. This is an emergency pre-demo fix to try to get this to build on CI...

Dependency fix

---

bower.json
kbase-extension/kbase_templates/notebook.html
kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidgetFull.js

fix dependencies and parentheses

---

kbase-extension/static/kbase/js/narrativeLogin.js

Just a reasonably minor change to the narrative login widget.

Added option to paste in an auth token in a dev environment.

---

RELEASE_NOTES.md
bower.json
kbase-extension/static/kbase/js/util/display.js
kbase-extension/static/kbase/js/util/kbaseApiUtil.js
kbase-extension/static/kbase/js/widgets/dynamicTable.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseBinnedContigs.js
kbase-extension/static/kbase/js/widgets/function_output/kbasePanGenome.js
package.json
src/biokbase/narrative/__init__.py
src/biokbase/narrative/common/kblogging.py
src/biokbase/narrative/common/log_proxy.py
src/biokbase/narrative/handlers/authhandlers.py
src/config.json

Somehow, the mongo logger was capturing auth_tokens from the environment. That's bad.

Strip any refs to auth_token from logging.  (TASK-786)

---

RELEASE_NOTES.md
nbextensions/appCell2/widgets/appCellWidget.js

I know I'm cheating by going out of band on this, but it was a pretty simple fix. But still pending product team testing.

KBASE-5101 Hide outdated view

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js

Copying **any** narrative through the Narratives panel would only copy the currently open one. Now it should behave as expected.

PTV-409 fix copying narratives

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionVolcanoPlot.js

Nothing urgent - the widget works fine, I just left in some debugging code. This nukes it.

removed debugging lines. Whoops. [TASK-816]

---

RELEASE_NOTES.md

getting ready to push ver 3.4.3 up to master

add release notes

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenericSetViewer.js
kbase-extension/static/narrative_paths.js

Sorry, I must've forgotten to put in the pull request for this one.

Generic set viewer

---

kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseExpressionSampleTableNew.js

Updates kbaseExpressionSampleTableNew (aka, "The histogram widget") to support KBaseSets.ExpressionSet.
It now supports KBaseRNASeq.RNASeqExpressionSet, KBaseRNASeq.RNASeqExpression, and KBaseSets.ExpressionSet.
It's also a viewer for all three types.

histogram widget update [TASK-933]

---

kbase-extension/kbase_templates/page.html
kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/util/timeFormat.js
test/unit/spec/Util/TimeFormatSpec.js

Change the color to an attention-getting red.
Fix timestamps in Safari. Might have broader timestamp fixes along for the ride.

TASK-1041 - minor adjustments to button

---

RELEASE_NOTES.md

Minor addition, just going to merge.

add to release notes

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js

Change from "suspend" to "error"

TASK-588 change status message for importer cells.

---

kbase-extension/static/kbase/js/widgets/loadingWidget.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobsPanel.js
nbextensions/codeCell/main.js
src/biokbase/narrative/jobs/jobmanager.py
test/unit/spec/narrative_core/kbaseNarrativeJobStatus-spec.js

See the ticket, but it should address most concerns for now.
(also KBASE-5275)

TASK-1079 Fix problems with code cells and app status widgets

---

kbase-extension/static/kbase/css/kbaseNarrative.css

-change combination of oxygenRegular + font-weight:bold to OxygenBold

change oxygenRegular to oxygenBold for kbase-list-items

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js

-kept track of last ran filter/method so that workspace update does not reset data pane

[KBASE-4186]

---

kbase-extension/static/custom/custom.css
kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/css/narrative.css
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeControlPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePanel.js

- accounted for margin of header in height
- change notebook container from having padding bottom to adding a hidden element with margin. Workaround for Firefox/EE. Padding only works with overflow on Chrome/Safari

kb side panel last item is not cut off [KBASE-3683]

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js

Adding the old auth back since the rest of the file still depends on user variable. Will need to refactor for new auth

re add old auth

---

kbase-extension/static/kbase/js/widgets/narrative_core/catalog/kbaseCatalogBrowser.js

There's other problems with that widget, too (it could probably use some rewriting...), but this fixes the immediate issue.

fix problem with clicking in catalog not inserting app cells

---

kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseAppCard.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCardLayout.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseDataCard.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeExampleDataTab.js

-updates button text in all tabs at same time
-fix bug with star
-update app card to look the same as prior card

bug fixes from giant pull request [TASK-1158]

---

kbase-extension/static/kbase/templates/data_staging/dropzone_area.html

Replaced old text saying only genomes and short reads supported
(May want to change this text again soon to note that this UI will replace the Import tab.)

improved wording

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js

Just a bug fix. It wasn't properly handling files with spaces in the names - all better now.

handles files with spaces. whoops

---

kbase-extension/static/kbase/config/data_source_config.json

Fixes https://kbase-jira.atlassian.net/browse/PTV-795

Take ContigSet out of Example Assemblies

---

kbase-extension/static/kbase/config/staging_upload.json
kbase-extension/static/kbase/js/widgets/appWidgets2/input/dynamicDropdownInput.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js

Includes tweaks to the staging viewer to set the path as the file input, not just the filename.

Upload Reads Demo with staging area dropdown

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataPanel.js

No time for code reviews or travis tests!
Just merge it!
Don't think about it!
Don't pause or consider the ramifications or address what horrible things it may do!
Merge! Integrate! Merge! Integrate!
Users need this!
Approve and merge now!

ADDS CRITICAL MISSING FEATURE!

---

kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCardLayout.js

-css magic to so that the hover border and card info border matches up

fix border layout of cards on hover [TASK-1247]

---

RELEASE_NOTES.md

The release notes got mangled somehow. This fixes them.

fix release notes for 3.5.1

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/dynamicDropdownInput.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js

Now it just shows the subpath and file name instead of always showing the username in a selected file.

Fix minor display problem in staging area dropdown input

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js

The importers are updated to generate UPAs (although there are issues in CI regarding importing genomes related to NewTempGenomes.Genome-2.0. Uma knows more than I do about it).
Currently, the staging panel will display the raw UPA if it is present (and omit the "Imported as..." item from the list if there is no UPA). This update tweaks it - it plops in a loading icon while it does a get_object_info_new call and uses that to get the name of the imported object.
The imported object name is then displayed as a link to the user, which opens up the landing page in a new tab when clicked.

pretties up the UPA field

---

kbase-extension/static/kbase/css/kbaseNarrative.css

[KBASE-5417]wrap word

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotation.js

cdss, mrnas & non_coding_features)

Tweak to allow loading of data from alternative feature arrays 

---

kbase-extension/static/kbase/js/widgets/function_output/modeling/KBaseBiochem.Media.js

We still need to fix kbase-ui but I don't know that repo

SCT-405: custom compounds now will not break media viewer

---

kbase-extension/static/kbase/templates/data_staging/dropzone_area.html

SCT-417 Removed "in development!" text from staging area

---

kbase-extension/static/kbase/config/staging_upload.json
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/uploadTour.js
kbase-extension/static/kbase/templates/data_staging/ftp_file_header.html

Adds a link to spawn the web uploader app in the right release state.

SCT-417 import panel punchlist

---

kbase-extension/kbase_templates/page.html

addresses https://kbase-jira.atlassian.net/browse/PTV-640

Taking "Bulk Import" off of hamburger menu

---

kbase-extension/static/kbase/config/staging_upload.json

Just removed the (TEST) FASTQ entry from the json.

removed TEST FASTQ reads [SCT-533]

---

RELEASE_NOTES.md
bower.json
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
package.json
src/biokbase/narrative/__init__.py
src/config.json

That's a fragile piece of code. :P

Fix problem with opening read-only narratives

---

kbase-extension/kbase_templates/page.html

(it links to the old search)
as per https://kbase-jira.atlassian.net/browse/PTV-958

remove "search data" from menu in Narratives

---

kbase-extension/static/kbase/config/data_source_config.json

Rewording public tab Fungal Genomes -> MycoCosm Genomes

re-wording Fungal Genomes -> MycoCosm Genomes

---

kbase-extension/kbase_templates/loading.html
kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/loadingWidget.js
test/unit/karma.conf.js
test/unit/spec/Util/TimeFormatSpec.js
test/unit/spec/loadingWidgetSpec.js

Adds a warning to the loading widget that shows up after 20s of inactivity.
Ticket here: https://kbase-jira.atlassian.net/browse/SCT-637

SCT-637 - Adds a lag warning to the narrative loading widget

---

RELEASE_NOTES.md
bower.json
package.json
src/biokbase/narrative/__init__.py
src/config.json

- update semver in all places that 3.7.0 exists
- and added release notes for 3.7.1
Able to test this locally against CI; still working to test it against prod locally.

prepare release 3.7.1 [SCT-793]

---

nbextensions/appCell2/widgets/appCellWidget.js

- also some code cleanup and removal of long-unused features
- note that the narrative must be saved after the output cell is deleted

prevent successfully completed app from re-inserting deleted output cell upon reload [SCT-791]

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseDifferentialExpressionMatrixSetViewer.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionVolcanoPlot.js

Updates to the volcano plot.
* calculates logs of q-values, since those are no longer provided.
* Also adds in the ability for the user to adjust the min/max x/y values. This is rough around the edges, but we want it up on CI for Ranjan/Sunita to start playing with it.
Yes, it redraws the svg in a very lazy manner when the min/max values change, but my d3 is a little rusty and as I said, it's rough around the edges.
Once it's up on CI, we'll probably need to iterate more, but we don't necessarily need to prevent an unintentional release.

Volcano plot updates [SCT-380]

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionVolcanoPlot.js

Just avert your eyes and kick it up to CI.
There was some sort of delay that'd occur when the 'Show Selected genes' button was clicked, which could cause it to fail. Apparently because it was re-calculating values at the time of the click. They're now cached in advance.
The table structure was also mostly empty, because the new object contains different values from the original method output.
And the export button was failing, because now the upload method takes a q_cutoff instead of a  p_cutoff. I'm handing in a -Log10(q_cutoff), so hopefully that's adequate, since that's what the user is actually working with.
At this point, the widget is completely incompatible with the original one that dealt with the output of whatever the original method was. I'm not going to make it backwards …

fixes table; create button [SCT-380]

---

kbase-extension/static/kbase/config/data_source_config.json
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeExampleDataTab.js

Updates to two files that describe the data in the example tab. @sychan @scanon @briehl

KBASE-1916 - Improve descriptions of data types in the Example tab

---

kbase-extension/static/kbase/js/common/pythonInterop.js
nbextensions/appCell2/widgets/appCellWidget.js
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_job.py
test/unit/spec/common/pythonInterop-Spec.js

...nevermind. Got trapped in a rathole of sprucing up backend tests. Once this passes, will merge, then move on to next step in a new pr.

SCT-961 test update

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotation.js
test/unit/spec/appWidgets/input/dynamicDropdownInputSpec.js
test/unit/spec/narrativeViewersSpec.js

- fixed the widget to catch insufficient constructor args and enter an error state, rather than continue and throw internal unexpected errors
- a couple of other minor test spec fixes

Fix  genome view widget to behave better under test conditions [SCT-1021]

---

kbase-extension/static/kbase/js/util/jobLogViewer.js

-fix scroll up animation of job logger

Fix Job Logger Scroll Up Animation

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseConditionSetViewer.js
kbase-extension/static/narrative_paths.js

It's pretty basic but it's something to show for the demo

Add first draft of condition set viewer

---

kbase-extension/static/kbase/js/api/KBaseSearchEngineClient.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/dynamicDropdownInput.js
kbase-extension/static/narrative_paths.js

Super excited about this! I'm not very familiar with select2 so let me know if I did anything wonky. You can play with the widgets with this narrative: http://ci.kbase.us/narrative/notebooks/ws.33517.obj.1
The search widget is pretty straight forward, the custom one points to a service that only works will full  ids (not a great demonstration) but you can see results with search text like"rxn00001".

Dynamic dropdown with search and custom modules

---

kbase-extension/static/kbase/js/widgets/kbaseVisWidget.js

Could we just get this reviewed and kicked up to CI ASAP?
I *think* this'll work, but this is the issue that has unearthed all of these CORS related content-type header issues, so I can't actually test the change locally. But it's a one liner that *shouldn't* break anything.
If we can approve this and boot it up to CI, I can at least look at it and confirm if the functionality is there and defer the service stuff.

added xmlns to svg tag [SCT-1094]

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseConditionSetViewer.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionMatrix.js

This PR adds the datatable buttons to expression matrices as Sunita requested

Condition set

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/dynamicDropdownInput.js

Shine up the dynamic dropdowns a bit more by displaying the selection template when a field is selected as well.

Dynamic Dropdowns

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/dynamicDropdownInput.js
nbextensions/install.sh
test/unit/spec/appWidgets/input/dynamicDropdownInputSpec.js
test/unit/spec/narrative_core/kbaseNarrativeAppPanel-spec.js

Adds the mock and the missing values to the dynamic_dropdown spec. Also fixed the case where the dynamic_dropdown_options are missing

fix dynamic_dropdown tests

---

nbextensions/advancedViewCell/widgets/advancedViewCellWidget.js
nbextensions/appCell2/widgets/appCellWidget-fsm.js
nbextensions/appCell2/widgets/appOutputWidget.js
nbextensions/codeCell/widgets/codeCell.js
nbextensions/dataCell/widgets/dataCell.js
nbextensions/editorCell/widgets/editors/readsSet/editor.js
nbextensions/outputCell/widgets/outputCell.js
nbextensions/viewCell/widgets/viewCellWidget.js

@briehl Ran across these when I was looking at the widgets

Fix user message typos

---

nbextensions/advancedViewCell/widgets/advancedViewCellWidget.js
nbextensions/appCell2/widgets/appCellWidget-fsm.js
nbextensions/appCell2/widgets/appOutputWidget.js
nbextensions/codeCell/widgets/codeCell.js
nbextensions/dataCell/widgets/dataCell.js
nbextensions/editorCell/widgets/editors/readsSet/editor.js
nbextensions/install.sh
nbextensions/outputCell/widgets/outputCell.js
nbextensions/viewCell/widgets/viewCellWidget.js
src/biokbase/narrative/__init__.py
src/biokbase/narrative/tests/test_viewers.py
src/biokbase/narrative/viewers.py
src/requirements.txt
test/unit/karma.conf.js

**Ready for review**
Compatible data to test this viewer is available here: https://ci.kbase.us/narrative/ws.28852.obj.1 but the viewer should also work with expression or differential expression matrices. 
To invoke in WS code cell:
```
from biopython.narrative import viewers
viewers.view_as_clustergram(<ws_ref>)
```

SCT-1234: Clustergram widget

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotation.js

The GenomeAnnotation Widget shouldn't display the demo POC IGV genome viewer on anything other than CI.
This changes how it determines which environment it's in.

changed how the CI environment is determined

---

kbase-extension/static/kbase/js/common/spec.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseGenericMatrix.js
kbase-extension/static/narrative_paths.js
src/requirements.txt
test/unit/spec/function_output/kbaseGenericMatrix-spec.js

Tabular view of generic matrices

GenericMatrix viewer

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCellToolbarMenu.js
nbextensions/appCell2/widgets/appCellWidget.js

This adds a new "app needs to be updated" icon, and removes the big yellow alert.
@sychan and I went back and forth on where to put the icon. For the demo tomorrow, we settled on the location in this PR - to the left of the app title - but 3 others are commented out. I figure after the demo and we make a decision, I'll do some cleanup.
Clicking the icon makes a popover with a friendlier version of the warning text.
The attached screenshot shows all 4 possibilities.

SCT-1261 outdated icon

---

.travis.yml
RELEASE_NOTES.md
bower.json
package.json
src/biokbase/narrative/__init__.py
src/requirements.txt

Also remove numpy, scipy, and pandas from the requirements.txt. May have been a problem.

Add release notes, bump version to 3.8.1

---

nbextensions/install.sh
src/biokbase/narrative/__init__.py
src/biokbase/narrative/tests/test_viewers.py
src/requirements.txt

This might break things, and is really only intended as an experiment. Let's see if numpy and pandas come back!

remove the clustergrammer_widget for now

---

scripts/narrative_backend_tests.sh
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/batch.py
src/biokbase/narrative/jobs/specmanager.py
src/biokbase/narrative/tests/data/app_full_infos.json
src/biokbase/narrative/tests/data/app_specs.json
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test.cfg
src/biokbase/narrative/tests/test_appmanager.py
src/biokbase/narrative/tests/test_batch.py

I just need a checklist, basically, and this seems as good a place as any...
Hope to get this complete-ish by the demo tomorrow. This has functions and documentation to help with building parameter sets for a batch app.
**get_input_scaffold**
**list_objects**
**list_files**
**generate_input_batch** -- goes in another PR based on this one.
- docstring (revise first!)
- implement
- test

SCT-1171 Batch API

---

.travis.yml
nbextensions/install.sh
src/biokbase/narrative/tests/test_viewers.py
src/install.sh
src/requirements.txt

This is my attempt to fix the clustergramer widget. I'm installing it w/o dependancies and this seems to resolve the thrashing between versions of numpy I was seeing in the logs.

Fix clustergrammer?

---

scripts/install_narrative_docker.sh

So unfortunately I was editing the wrong file earlier. This version should actually enable the widget in the built image

Clustergrammer build

---

kbase-extension/static/kbase/js/common/spec.js
kbase-extension/static/kbase/js/widgets/appWidgets2/fieldWidgetCompact.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/newObjectInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/validation.js
kbase-extension/static/kbase/js/widgets/appWidgets2/validators/workspaceObjectName.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/appParamsWidget.js

Multiple output objects should now throw an error when trying to give the same name to multiple output objects in the same app run.

SCT-1219 Fix multiple output handling

---

Dockerfile
narrbase-image/conda-requirements/biokbase-requirements.txt
scripts/build_narrative_container.sh
src/scripts/kb-update-config

Add numpy, scipy, scikit-learn to the base image.

update the base image

---

src/biokbase/narrative/viewers.py

Slight tweak to make the category name on the viewer correct

---

kbase-extension/static/kbase/js/widgets/function_output/GenomeCategorizer.js
kbase-extension/static/kbase/js/widgets/function_output/GenomeClassifierTrainingSet.js
kbase-extension/static/narrative_paths.js
test/unit/spec/function_output/GenomeCategorizer-spec.js
test/unit/spec/function_output/GenomeClassifierTrainingSet-spec.js

Adds simple viewers for GenomeCategorizer and GenomeClassifierTrainingSet

GenomeClassifier Viewers

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenericMatrix.js

I wanted to add in data from attribute mappings into the display for Generic Matrix if present. This required a bit of gymnastics that unfortunately make it hard to mock a unit test for this widget (a call to a dynamic service and up to 3 calls to WS).

Add attribute mapping info into GenericMatrix

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotation.js

@eapearson These relationships seem to have been commented out a few months ago during a refactor but a few are still needed.

add back parent gene and parent mrna relationships

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseExpressionFeatureClusters.js

I'd like to go back a refactor this module more extensively but this should address the pop up that Sunita saw.

Minimal fix for FeatureCluster viewer w/ new genome

---

src/biokbase/narrative/tests/test_viewers.py
src/biokbase/narrative/viewers.py

Some major tweaks:
1. Refactor Condtionsset to attribute mapping
2. Use refpaths for attribute mappings
3. Rename _get_df to get_df and default to returning multiindex

Update generics viewers

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDownloadPanel.js
test/unit/spec/narrative_core/kbaseNarrativeDownloadPanel-spec.js

The allowed types are hard-coded for now. We can change this later. Just putting something together for the demo.
@Tianhao-Gu

Add 'staging' button to some types for download

---

kbase-extension/static/kbase/js/api/StagingServiceClient.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
kbase-extension/static/kbase/templates/data_staging/ftp_file_table.html

Adds a download button for each item in the staging area

Sct-1547: Staging area download

---

kbase-extension/static/kbase/js/api/auth.js
kbase-extension/static/kbase/js/userMenu.js
kbase-extension/static/kbase/js/util/display.js
kbase-extension/static/kbase/js/util/string.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSharePanel.js
test/unit/spec/Util/DisplaySpec.js
test/unit/spec/Util/StringSpec.js

Some cheeky user on CI set his username to a little blob of JS that makes an alert popup appear.
This fixes that.

Fix HTML injection of usernames

---

kbase-extension/static/kbase/js/api/StagingServiceClient.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js

SCT-1509 Added link to add globus ACL before going to link

---

docker/notelauncher.lua

We found that we needed some additional changes once we started testing in prod. These never made it back into the source repo

These config tweaks never made it back into the source repo

---

kbase-extension/static/kbase/js/kbaseNarrativePrestart.js
kbase-extension/static/kbase/js/narrativeConfig.js
src/biokbase/narrative/contents/kbasewsmanager.py

just missing the end-of-line matcher

fix frontend ws id lookup regex

---

kbase-extension/kbase_templates/403.html
kbase-extension/kbase_templates/500.html
kbase-extension/kbase_templates/basic_header.html
kbase-extension/kbase_templates/narrative_header.html
kbase-extension/kbase_templates/notebook.html
kbase-extension/kbase_templates/page.html
kbase-extension/static/permErrorMain.js
src/biokbase/narrative/contents/kbasewsmanager.py
src/biokbase/narrative/handlers/narrativehandler.py
src/config.json.templ

Now, instead of a 403 error page, this gives a warning that you can't see a narrative, and a button to request access.
Kinda messes around with all of the templates, too, so it should be tested pretty thoroughly in CI.

KBASE-2041 Front-end half of requesting narrative permission

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDownloadPanel.js

So I missed this last place to inject the generics module level logic.

use module level downloaders if present

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppPanel.js
test/unit/spec/narrative_core/kbaseNarrativeAppPanel-spec.js

Should cut down on network calls and data transfer by quite a bit.

SCT-1785 Update the app panel to fetch all of its data from narrative service

---

kbase-extension/static/kbase/js/util/display.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeManagePanel.js

It's not perfect, but only makes a few calls now, instead of one for each user.
I also refactored and deleted a bunch of code.
Honestly, this widget is still a mess of mashed together logic and view and whatever, but it's much more contained.

SCT-1783 Some refactor of the manage panel

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSharePanel.js

Not sure how I missed this in review...

Fix "Associate" spelling in share panel

---

kbase-extension/static/kbase/js/widgets/appWidgets2/subdataMethods/manager.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseAttributeMapping.js

Changed the syntax for accessing nested subdata a bit. Now "<WSREF>" in the path to subdata will trigger the WS lookup of the ref at that point before resuming the path to subdata.

Fix nested subdata

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSharePanel.js

added group list, icon, and links that are associated with the narrative on share panel.

added group list, icon, and links

---

kbase-extension/kbase_templates/page.html
src/biokbase/narrative/handlers/narrativehandler.py
src/config.json.templ

one extra tag for monitoring conversion.

addad ad conversion tag

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotation.js

Update kbaseGenomeAnnotation.js to fix typo: issue #1487

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeExampleDataTab.js

Fixes #1489 
Also add some RELEASE NOTES text with update from #1487

fix copying from example tab

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeComparisonViewer.js
kbase-extension/static/kbase/js/widgets/function_output/kbasePanGenome.js

From the document https://docs.google.com/document/d/1vktk2Wq6NrovJ9MOSRZm5HuNM54r0N7HP_96fKcVSZY/
Proposed changes #3/4/5, #6, #9a, #9b/c, and #9f, in that order.
@briehl

More formatting updates for Pangenome and Compare Genomes from Pangenome

---

kbase-extension/static/kbase/js/util/jobLogViewer.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/tabs/jobStateViewer.js
nbextensions/appCell2/widgets/tabs/resultsViewer.js
src/biokbase/narrative/app_util.py
src/biokbase/narrative/tests/test_app_util.py

finish output viewer still has some problems.

fix app cell errors due to ee2

---

src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/data/ee2_job_test_data.json
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_job.py

update some ee2 client call. It allows me to do `_construct_job_status` with code cell but it seems the front end is still not picking it up correctly yet.

update check_job call

---

src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/data/ee2_job_test_data.json
src/biokbase/narrative/tests/test_jobmanager.py

all of the time fields in ee2 are updated to use epoch time in milliseconds.

Fix timestamp from ee2

---

src/biokbase/narrative/app_util.py
src/biokbase/narrative/tests/test_app_util.py

the token system var removal part is covered in a separate PR, but this builds on it.

Timestamp system variable

---

nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/tabs/jobStateViewer.js
src/biokbase/execution_engine2/execution_engine2Client.py

update ee2 clients and fix job status due to ee2 time fields update.

ee2 tiemfields update

---

kbase-extension/static/kbase/js/narrativeConfig.js

This fix is very simple. I discovered it when implementing the fix for PTV-1315 and inadvertently formed urls which included a url fragment. Initially I presumed I had introduced a bug, but the error occurred in the app cell extension itself, which is a big stretch from a viewer widget.
The changes here are primary:
- use the window location pathname not the href -- all of the information the narrative needs is in the path itself; this also ensures that the fragment/hash is not present
- improved, perhaps, or at lest simplified the regex usage
I left quite a few notes in the code to address these concerns:
- there is no explicit handling of a non-match in the narrative url. it looks like the separate parsing and interpretation of the url in the back end catches most if not all cases of …

Fixes SCT-2291, in which a url hash (fragment) causes app cell failure.

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/narrativeConfig.js

Includes a version bump on develop, hence the little changes.

Merge from develop -> Py3-update

---

RELEASE_NOTES.md
bower.json
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json.templ

The main thing is updating versions. Nothing else really changed, but there's a ton of code revision/refactor.

bump version to 4.0.0, smallish release notes

---

README.md

Small readme fix for the conda commands

Fix conda command in docs

---

kbase-extension/static/kbase/config/feature-config.json
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/widgets/narrative_core/staticNarrativesManager.js
kbase-extension/static/kbase/templates/static_narrative.html

Still early(ish) progress - move the UI generation to a template.
This also implements removing the feature (the Share menu option) in the feature config.

Static narrative UI changes

---

test/unit/spec/narrative_core/upload/stagingAreaViewer-spec.js

It's not perfect, but adds another test that got left off last time.

add more staging area viewer tests

---

nbextensions/appCell2/widgets/tabs/jobStateViewer.js
nbextensions/appCell2/widgets/tabs/logTab.js
package-lock.json

Turned out to be a lot smaller than expected, but I want to close the branch off. Will add missing commentary to that widget before doing so.

EE2 issue 203 - cancelling

---

package-lock.json
src/config.json

Minor changes, don't affect anything other than dev workflow.

Revert config.json change, bump package-lock version

---

kbase-extension/static/kbase/js/util/jobLogViewer.js
test/unit/spec/Util/jobLogViewerSpec.js

Should better handle the startup, not-running case.
Not going deep on these changes, since most of the work at this point should be done to support EE2. There shouldn't be much of a lag between this release and the release of EE2. Otherwise, this could go on and on and on...

Issue #1619 - disable button at start

---

kbase-extension/static/kbase/js/util/bootstrapSearch.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppPanel.js
test/unit/spec/narrative_core/kbaseNarrativeAppPanel-spec.js

This addresses the following issues in the app panel search box:
* Search by module name doesn't work
* Search and re-render is very slow
* There's an extra click required after searching
* Should only search ~200ms after last input

SCT-2473 app search

---

src/biokbase/narrative/jobs/job.py

fixes https://github.com/kbase/execution_engine2/issues/236

fallback to an empty dict if job params are not available

---

kbase-extension/static/kbase/js/common/utils.js
nbextensions/appCell2/widgets/appCellWidget-fsm.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/tabs/infoTab.js

This pull request Adds the info tab to app cells in narratives. Right now it is configured to always be present, regardless of job or cell state.

Fixes SCT-2559: Add info tab to App Cells

---

package-lock.json
package.json

Reverts kbase/narrative#1667 -- This was meant to go into a different branch.

Revert "Bump geckodriver from 1.16.2 to 1.19.1"

---

.github/dependabot.yml

Can revert this down if desired.

Upping PR limits for demo sake.

---

nbextensions/appCell2/widgets/tabs/errorTab.js

Update advice to more useful messsage.
It would be great to get a link to miriam's common errors page or a guide on what to do for errors linked as well, once that page exists. 
Also I guess we shouldn't use email anymore as per https://kbase.slack.com/archives/C5Z8X8DS4/p1589233536170200?thread_ts=1589233498.169700&cid=C5Z8X8DS4
Or maybe thats for outreach actually.

PTV-1515 Update advice to more useful messsage

---

RELEASE_NOTES.md
bower.json
nbextensions/appCell2/widgets/appCellWidget-fsm.js
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

Also, hide information tab in app cells for now.

Version bump to 4.2.1, release notes

---

kbase-extension/static/kbase/js/widgets/function_output/kbaseVariation.js
kbase-extension/static/narrative_paths.js

- Added support for kbaseVariation widget 
- Uses Jbrowseserver dynamic service

Working kbaseVariation widget

---

kbase-extension/static/kbase/js/api/kbase-client-api.js
kbase-extension/static/kbase/js/patched-components/select2/select2.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseAnnotatedMetagenomeAssembly.js
kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotation.js
kbase-extension/static/kbase/js/widgets/kbaseVisWidget.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCellToolbarMenu.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/editorCell/widgets/editors/readsSet/editor.js
test/unit/karma.conf.js
test/unit/spec/common/validate-Spec.js

Hopefully these deletes will not be controversial. This is not a complete pass over the codebase to remove commented out code, but it is a start. The code removed represents .25% of the JS in this repository, so coverage should at least improve with this change.

Removing commented out code to offset inserts.

---

README.md

Testing new CI

---

README.md

Testing. Ignore.

---

bower.json
kbase-extension/static/kbase/css/appCell.css
kbase-extension/static/kbase/js/common/unodep.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/sequenceInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/view/sequenceView.js
test/unit/spec/common/unodepSpec.js

Certain values are not as easy to copy and paste from within KBase app cells, and this PR trials a clipboard button to sequence input and view elements. This PR also upgrades the select2 dependency to 4.0.13.

Added clipboard functionality to inputs and views.

---

docs/developer/local-docker.md
kbase-extension/static/kbase/js/narrativeLogin.js
scripts/local-dev-run.sh

* Add entire `kbase-extension` directory to the mount
* Automatically map port 8888 to the host (so localhost:8888 works) (this should still work with the kbase-ui network mapping)

Tweak local dev image script

---

README.md

New CI Test 1 - Ignore

---

.github/pull_request_template.md

Adds a pull request template for future PRs as per https://kbase-jira.atlassian.net/browse/DATAUP-69

DATAUP-69 Create pull_request_template.md

---

.gitignore
docs/adrs/0001-git-workflow.md

The purpose of this PR is to create an ADR to document the git workflow developers will use to contribute to the narrative repo.
NOTE: Please feel free to comment and add additional reasons for a given alternative or disagreements. 
https://kbase-jira.atlassian.net/browse/DATAUP-62
- [ x] Added the Jira Ticket to the title of the PR e.g. (DATAUP-69 Adds a PR template)
N/A
- [ x] My code follows the guidelines at https://sites.google.com/truss.works/kbasetruss/development
- [x ] I have performed a self-review of my own code
- [N/A ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [N/A  ] I have added tests that prove my fix is effective or that my feature works
- [ …

Git Workflow ADR DATAUP-62

---

README.md
docs/testing.md

Instructions for how to use the karma debugger were added to docs/testing.md. I also created a table of contents for the file and fixed some of the markdown styling. I altered the Readme.md to reference the testing files, so there isn't duplicated documentation. 
https://kbase-jira.atlassian.net/browse/DATAUP-120

DATAUP-120 Update narrative repo testing to include how to use karma debugger

---

docs/adrs/0002-integration-testing-library.md

This ADR selects an integration and end-to-end testing framework. Adding integration and e2e tests will provide additional test coverage and development confidence. 
https://kbase-jira.atlassian.net/browse/DATAUP-195
No code changes
No code changes
N/A

DATAUP-195 Integration Testing Framework ADR

---

src/config.json.templ

* Please include a summary of the change and which issue is fixed. 

Test for PR action

---

kbase-extension/static/kbase/css/kbaseNarrative.css

center icon

---

.travis.yml
test/unit/karma.conf.js

This is to fix the test files in the karma conf. This error slipped in when we were working though race conditions last week. The karma conf files now reads all specs for the unit tests.
to test, run make test-frontend-unit.

fix test path

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
test/unit/spec/nbextensions/appCell2/widgets/appCellWidget-spec.js

This PR fixes the zip file icon. It is now visible. 
https://kbase-jira.atlassian.net/browse/DATAUP-204
To test, start the narrative locally, go to the import tab, drag and drop a zip file into the drop zone, and refresh the staging area. You should now see the icon again.

DATAUP-204

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCellToolbarMenu.js
test/unit/spec/narrative_core/kbaseCellToolbarMenu-spec.js

* Moves options menu to be first
Before
After
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-202

DATAUP-202 Moves options menu to be first

---

kbase-extension/static/kbase/css/appCell.css
kbase-extension/static/kbase/css/batchMode.css
kbase-extension/static/kbase/css/bootstrapHelper.css
kbase-extension/static/kbase/css/buttons.css
kbase-extension/static/kbase/css/contigBrowserStyles.css
kbase-extension/static/kbase/css/kbaseEditor.css
kbase-extension/static/kbase/css/kbaseIcons.css
kbase-extension/static/kbase/css/kbaseJobLog.css
kbase-extension/static/kbase/css/kbaseNotify.css
kbase-extension/static/kbase/css/kbaseStylesheet.css
kbase-extension/static/kbase/css/kbaseTour.css
kbase-extension/static/kbase/css/landing-pages.css
kbase-extension/static/kbase/css/methodCell.css
kbase-extension/static/kbase/css/widgets.css
kbase-extension/static/kbase/custom/custom.css
nbextensions/advancedViewCell/main.js
nbextensions/advancedViewCell/styles/main.css
nbextensions/appCell2/main.js
nbextensions/appCell2/styles/main.css
nbextensions/editorCell/main.js
nbextensions/editorCell/styles/main.css
nbextensions/editorCell/styles/old.css
nbextensions/viewCell/main.js
nbextensions/viewCell/styles/main.css

Revert "DATAUP-246: css to sass: css cleanup, part 1"

---

kbase-extension/static/kbase/css/kbaseNarrative.css

* Update css as requested for refresh button
* Approved by mallory

DATAUP-188 Finish Refresh Button Changes

---

kbase-extension/static/kbase/css/kbaseNarrative.css

Fix margin for staging area text

Fix margin for staging area text

---

docs/adrs/0002-integration-testing-library.md

This ADR was updated to reflect the recent decision to use selenium webdriver as the integration testing library in the narrative repo. 
https://kbase-jira.atlassian.net/jira/software/projects/DATAUP/boards/57

DATAUP-235 Update Integration Testing ADR

---

kbase-extension/static/kbase/css/kbaseNarrative.css

This is a follow up PR to address the comment from andy:
"The ACs seem to be met, but can the clear all button get a pointer cursor on hover?"
https://kbase-jira.atlassian.net/browse/DATAUP-213

Dataup 213 review edits

---

docs/adrs/0003-bulk-import-ui.md

This PR contains an ADR for the new bulk import UI. Let's discuss!

DATAUP-278 bulk import UI ADR

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js

See changes in https://github.com/kbase/staging_service/pull/93

DATAUP-296 Update stagingAreaViewer.js

---

nbextensions/bulkImportCell/actionButton.js
nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/bulkImportCell/cellControlPanel.js
nbextensions/bulkImportCell/cellTabs.js

This is the first pass at several components for the bulk import cell. These are all under `nbextensions/bulkImportCell` and are broken down into the following:
* `bulkImportCell` - the main controller that lays out and manages everything else
* `cellControlPanel` - the container for everything in the control panel, including the action button and tabs
* `actionButton` - the action button itself
* `cellTabs` - the tabs
This is really just an initial scaffold that I worked on with @ialarmedalien, @bio-boris, @eamahanna, and @leia-sefkin this afternoon. It's set up so that each module can be worked on roughly independently.
No tests yet, and lots of refactor ahead, but it's a start.
The ticket's for the tab component work, but this was all necessary to get that going
No automated tests yet, …

DATAUP-287 Mobbing on the bulk import cell

---

.github/workflows/test.yml

Updating GitHub actions to fix issues with images not building.

Update github action to use most recent version of miniconda

---

kbase-extension/static/kbase/js/common/cellComponents/filePathWidget.js
kbase-extension/static/kbase/js/common/cellComponents/paramsWidget.js
nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/bulkImportCell/main.js
nbextensions/bulkImportCell/tabs/configure.js
test/.eslintrc.yml
test/data/testAppObj.json
test/unit/mocks.js
test/unit/spec/nbextensions/appCell2/widgets/appCellWidget-spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js
test/unit/spec/nbextensions/bulkImportCell/main-spec.js
test/unit/spec/nbextensions/bulkImportCell/tabs/configure-spec.js

This is meant to start fixing front end tests that keep failing on the `truss` branch, due to some rapid dev work.
It's not quite complete, but I think I need help. There's tests that, when the test files are run individually, all pass fine without warnings. But when run in a batch often show console errors. They behave as though they're trying to access mocked fixtures after they've been cleared up, or are continuing to try to execute after the test ends. They might be due to dangling Promises or something happening deep in the stack - specifically in the `fieldTableCellWidget` or the `dynamicDropdownInput`. I can point out the issues in the logs once they run.
Additionally, while trying to check this work in, some form of pre-commit tried to run tests. But they were somehow …

DATAUP-330 test fix

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStateListRow.js
nbextensions/bulkImportCell/testAppObj.json
package-lock.json
test/data/testAppObj.json

Adding some extra job IDs and statuses to the PR.
See https://github.com/kbase/execution_engine2/blob/14b71779fd005c86f24b728f253cdb6f1e3d8864/execution_engine2.spec#L334 for the job statuses. Sample screenshot:

DATAUP-313: test data

---

kbase-extension/static/kbase/js/util/display.js
kbase-extension/static/kbase/js/util/icon.js
kbase-extension/static/kbase/js/widgets/narrative_core/catalog/app_card.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseAppCard.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseDataCard.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeAppCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeCellMenu.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePublicTab.js
test/unit/spec/Util/DisplaySpec.js
test/unit/spec/Util/iconSpec.js

This PR consists entirely of Prettier and ESLint changes to files that are affected by the icon build methods updates. The next PR for DATAUP-322 will contain the actual code changes!
The first commit in the PR is the Prettier run, and the second is ESLint.
Note that the base for this PR is currently the branch up for PR in https://github.com/kbase/narrative/pull/2053.
https://kbase-jira.atlassian.net/browse/DATAUP-322
- [N/A] I have made corresponding changes to the documentation
- [N/A] I have added tests that prove my fix is effective or that my feature works

DATAUP-322: icon build methods II

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/results/resultsTab.js

Fixing a little case-sensitive typo. So annoying that it didn't present a problem locally, but does when deployed.
As far as I know, this has to be deployed through a non-MacOS system. MacOS is more permissive about file case sensitivity.

fix typo common/UI -> common/ui

---

.github/pull_request_template.md
docs/developer/running_tasks.md

Update of the PR request template, prompted by the repeated mention of 'travis'; also updated dev docs on Prettier and ESLint.
N/A

Updating the PR request template

---

.eslintrc.yml
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStateList.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStateListRow.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTab.js
kbase-extension/static/kbase/js/common/error.js
kbase-extension/static/kbase/js/common/jobs.js
kbase-extension/static/kbase/js/common/ui.js
kbase-extension/static/kbase/js/util/jobLogViewer.js
kbase-extension/static/kbase/js/util/jobStateViewer.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/tabs/errorTab.js
nbextensions/appCell2/widgets/tabs/status/logTab.js
nbextensions/bulkImportCell/bulkImportCell.js
package-lock.json
test/unit/spec/Util/BootstrapDialogSpec.js
test/unit/spec/Util/BootstrapSearchSpec.js
test/unit/spec/Util/DisplaySpec.js
test/unit/spec/Util/StringSpec.js
test/unit/spec/Util/TimeFormatSpec.js
test/unit/spec/Util/jobLogViewerSpec.js
test/unit/spec/common/cellComponents/tabs/jobStateList-Spec.js
test/unit/spec/common/cellComponents/tabs/jobStateListRow-Spec.js
test/unit/spec/common/cellComponents/tabs/jobStatusTab-Spec.js
test/unit/spec/common/jobsSpec.js

ESLint + Prettier on the files that are/will be affected by the changes for the job status updating thing.
Also removed some cruft and fixed some issues identified by ESLint.
I've updated the ESLint config to remove some rules that were made obsolete by Prettier, and added in some extra rules to use more of the exciting ES6+ features.
More comments inline.
https://kbase-jira.atlassian.net/browse/DATAUP-314

DATAUP-314: Pre-PR file cleanup and prep

---

kbase-extension/static/kbase/js/common/clock.js
kbase-extension/static/kbase/js/common/error.js
kbase-extension/static/kbase/js/common/html.js
kbase-extension/static/kbase/js/common/jobs.js
kbase-extension/static/kbase/js/common/runClock.js
kbase-extension/static/kbase/js/common/ui.js
nbextensions/appCell2/widgets/appCellWidget.js
test/unit/spec/common/jobsSpec.js
test/unit/spec/common/ui-Spec.js

A few changes in this PR:
- ran eslint / prettier on a couple of modules that I was using/referencing
- moved the `runClock` module to `kbase/js/common`
- add new methods to `kbase/js/jobs.js` as required by the new job status pane
More comments inline.

DATAUP-314: job status tab pt I

---

bower.json

Update bluebird promises package to the current version.
- [N/A] Added the Jira Ticket to the title of the PR (e.g. `DATAUP-69 Adds a PR template`)
- [x ] My code follows the guidelines at https://sites.google.com/lbl.gov/trussresources/home?authuser=0

Update bluebird to the latest release

---

bower.json

update bluebird to the latest version, which includes a number of bug fixes

update bluebird to the latest version

---

.eslintignore
.eslintrc.yml
.gitattributes
.github/workflows/test.yml
.prettierignore
.prettierrc.yaml
Gruntfile.js
docs/developer/running_tasks.md
package-lock.json
package.json
test/unit/karma.conf.js

Copying over various bits of npm candy to the `develop` branch, including:
- prettier config
- eslint configs
- .gitattributes file to enforce unix line endings
- a few npm shortcuts for running eslint, prettier, etc.
- JSON result reporter for Karma, which outputs frontend unit test results in JSON format; this is integrated into the GitHub actions, and failed unit test runs will produce a `karma-results.json` file with details of the tests run and their results

Test error reporting and npm modules

---

test/unit/testUtil.js

Cleaning up linting errors and unused functions in the `testUtils.js` file.

DATAUP-330: clean up testUtils.js

---

kbase-extension/static/kbase/js/api/upa.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeOutputCell.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeStagingDataTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/uploadTour.js
test/unit/mocks.js
test/unit/spec/function_output/GenomeClassifierTrainingSet-spec.js
test/unit/spec/function_output/kbaseAlignment-spec.js
test/unit/spec/function_output/kbaseAttributeMapping-spec.js
test/unit/spec/function_output/kbaseDefaultObjectView-spec.js
test/unit/spec/function_output/modeling/msPathway-spec.js
test/unit/spec/narrative_core/kbaseAppCard-spec.js
test/unit/spec/narrative_core/kbaseNarrativeAppPanel-spec.js
test/unit/spec/narrative_core/kbaseNarrativeDataList-spec.js
test/unit/spec/narrative_core/kbaseNarrativeDownloadPanel-spec.js
test/unit/spec/narrative_core/kbaseNarrativeJobStatus-spec.js
test/unit/spec/narrative_core/kbaseNarrativeOutputCell-spec.js
test/unit/spec/narrative_core/kbaseNarrativeStagingDataTab-spec.js
test/unit/spec/narrative_core/staticNarrativesManager-spec.js
test/unit/spec/narrative_core/upload/stagingAreaViewer-spec.js

- Fixed a couple of tests with no expectations, disabled a couple more that had no expectations and required some investigation to fix.
- 

DATAUP-330: narrative_core test fixes

---

kbase-extension/static/kbase/js/tour.js
kbase-extension/static/kbase/js/userMenu.js
test/unit/karma.conf.js
test/unit/spec/kbaseNarrativeSpec.js
test/unit/spec/util/BootstrapDialogSpec.js
test/unit/spec/util/BootstrapSearchSpec.js
test/unit/spec/util/DisplaySpec.js

Minor fixes to tests and modules in the `util/` directory.
Turn on Karma's setting to ensure that tests fail if there are no expectations.

DATAUP-330: util base dir test fixes

---

RELEASE_NOTES.md

Non-functional commit to trigger rebuild of the image in develop.

---

kbase-extension/static/kbase/js/common/cellComponents/filePathWidget.js
kbase-extension/static/kbase/js/common/cellComponents/paramsWidget.js
kbase-extension/static/kbase/js/common/events.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/checkboxInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/customSubdataInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/input/newObjectInput.js
kbase-extension/static/kbase/js/widgets/appWidgets2/paramResolver.js
nbextensions/bulkImportCell/tabs/configure.js
test/unit/spec/appWidgets/paramResolverSpec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js
test/unit/spec/nbextensions/bulkImportCell/tabs/configure-spec.js

A few more little fixes to enable further tests.
See comments inline.

DATAUP-330: Fix linter errors; fix configure test input to allow tests to pass

---

kbase-extension/static/kbase/js/util/jobLogViewer.js
nbextensions/bulkImportCell/bulkImportCell.js
test/unit/spec/util/jobLogViewerSpec.js
test/unit/testUtil.js

DATAUP-314: Job Log Viewer update: add status lines!

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStateList.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStateListRow.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTab.js
nbextensions/bulkImportCell/bulkImportCell.js
test/data/testAppObj.js
test/unit/spec/common/cellComponents/tabs/jobStateList-Spec.js
test/unit/spec/common/cellComponents/tabs/jobStateListRow-Spec.js

https://kbase-jira.atlassian.net/browse/DATAUP-314

DATAUP-314: activate buttons

---

kbase-extension/static/kbase/js/common/html.js
kbase-extension/static/kbase/js/common/ui.js
nbextensions/appCell2/widgets/appCellWidget.js
test/unit/testUtil.js

A few bits and pieces I found whilst working on DATAUP-314
Integration tests have failed in both runs.

DATAUP-314: misc tweaks

---

kbase-extension/static/kbase/js/common/cellComponents/actionButtons.js
kbase-extension/static/kbase/js/common/cellComponents/filePathWidget.js
kbase-extension/static/kbase/js/common/cellComponents/paramsWidget.js
kbase-extension/static/kbase/js/common/pythonInterop.js
nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/bulkImportCell/fileTypePanel.js
nbextensions/bulkImportCell/tabs/configure.js
test/unit/spec/common/pythonInterop-Spec.js

This includes a few minor fixes, the generated Python code for running the cell, and toggles the action button to run when ready.
https://kbase-jira.atlassian.net/browse/DATAUP-312
1. You might need to make a new bulk import cell with these changes
2. Fill out all parameters and file paths
3. It should now show check marks in both file type buttons, and make the Run button available to click.
4. Clicking that run button should put a Pythonic error at the bottom of the cell, as the `run_app_bulk` function isn't written in this PR.

DATAUP-312 write Python code for running

---

nbextensions/bulkImportCell/bulkImportCell.js
test/unit/spec/common/cellComponents/tabs/jobActionDropdown-Spec.js

I think these were caused by a thing in a recent PR that I missed. Oops!

minor test fixes

---

nbextensions/appCell2/appCell.js
nbextensions/appCell2/main.js
nbextensions/appCell2/widgets/appCellWidget-fsm.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/appOutputWidget.js
nbextensions/appCell2/widgets/appParamsViewWidget.js
nbextensions/appCell2/widgets/appParamsWidget.js
nbextensions/appCell2/widgets/configureTab.js
nbextensions/appCell2/widgets/undefinedWidget.js

Fixing up the relevant code before embarking upon bug fixing and testing:
- removing unnecessary workspace pieces from app cell -- the code now more closely mirrors that of the bulk import cell
- fixing linter errors in the various app cell widgets
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-253
- [] I have added tests that prove my fix is effective or that my feature works

DATAUP-263: prep work

---

RELEASE_NOTES.md
bower.json
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

While this is mostly a bugfix release, the code and deployment changes are feature-rich enough to warrant a minor version bump.
Most of the checklist is N/A, as this is bumping various version tags.

release 4.4.0

---

RELEASE_NOTES.md
docs/testing/integration-testing.md
kbase-extension/static/kbase/js/widgets/appWidgets2/input/select2ObjectInput.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePublicTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeStagingDataTab.js
kbase-extension/static/kbase/js/widgets/narrative_core/publicDataSources/search2DataSource.js
kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
scripts/local-dev-run.sh
test/integration/specs/kbaseNarrativeSidePublicTab_test.js

The primary functional change is to enhance the existing search query used by the RefSeq data slideout tool to also search against the "taxonomy" field. The taxonomy field of a Genome object contains a text representation of the organism's lineage, and when indexed for search is searchable by the whole word components of the lineage.
This satisfies an internal request https://kbase-jira.atlassian.net/browse/SCT-3062.
The effective change is simply adding this field to the set of fields searched against, just a few lines of code, and is isolated in this commit:
https://github.com/kbase/narrative/commit/591bc20c66fb90ae4d745b6a448c78fdd0526022
Another functional change is to fix a latent bug which would cause incorrect results in some cases after an initial search. The cause was setting the …

Implements SCT-3062: Search by lineage for the RefSeq data slideout tool

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobActionDropdown.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStateList.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStateListRow.js
kbase-extension/static/kbase/js/common/jobManager.js
kbase-extension/static/kbase/js/common/jobMessages.js
kbase-extension/static/kbase/js/widgets/narrative_core/jobCommChannel.js
nbextensions/bulkImportCell/bulkImportCell.js
test/unit/spec/common/cellComponents/tabs/jobActionDropdown-Spec.js
test/unit/spec/common/cellComponents/tabs/jobStateList-Spec.js
test/unit/spec/common/cellComponents/tabs/jobStateListRow-Spec.js
test/unit/spec/common/cellComponents/tabs/jobStatusTab-Spec.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

This PR has two main purposes: it standardises and centralises job-related functions in the job manager module, and it moves functionality out of the jobStateListRow module in preparation for switching all job row generation and functionality over to DataTables (and getting rid of the jobStateListRow module). Unfortunately these two goals are very closely linked and it was very difficult to keep the PR size down to something semi-reasonable, especially since there was a lot of moving chunks of code around in and between files.
I have also transferred a lot of tests out of the jobStateListRow test module and into the jobStateList tests instead.
The results tab test fails about every other time with the following error:
```
3016    test the bulk import cell results tab
3017    ✖ should …
```

DATAUP-427: job manager updates

---

kbase-extension/static/kbase/js/common/jobs.js
kbase-extension/static/kbase/js/common/props.js
kbase-extension/static/kbase/js/util/jobLogViewer.js
package-lock.json
test/data/jobsData.js
test/unit/spec/common/jobCommChannel-spec.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/common/jobs-Spec.js

Main change in this ticket is adding in some batch job data and updating functions to take account of retried jobs. See inline comments for details.

DATAUP-532: Using batch job data for tests

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
kbase-extension/static/kbase/js/common/jobManager.js
package-lock.json
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobManager-Spec.js

Updating job status table to be capable of handling retries

---

nbextensions/appCell2/widgets/tabs/resultsViewer.js

Fix Lazy Loading with Scroll Debounce

---

kbase-extension/static/kbase/css/kbaseNarrative.css
kbase-extension/static/kbase/js/util/display.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeOutlinePanel.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeSidePanel.js
kbase-extension/static/narrative_paths.js
test/unit/mocks.js
test/unit/spec/narrative_core/kbaseNarrativeOutlinePanel-spec.js

Adds an outline panel to the narrative sidebar. Nesting depth is determined by markdown header levels H1-H3, with all cells assumed to be H4 by default, H4/H5/H6s will not effect nesting.  It's render is throttled to 100ms, and it will only re-render elements when the title, icon, or nesting depth of a cell changes. The "tree" style of the outline is created via CSS, the dom structure is nested ULs.
- Click-to-scroll to cell from the outline
- Selected cell highlight (green)
- Visible cells highlight (gray)
e.g. https://kbase-jira.atlassian.net/browse/SCT-3088
- [N/A] (Python) I have run Black and Flake8 on changed Python code manually or with a git precommit hook

SCT-3088 Add Narrative Outline Panel

---

docs/testing/unit-test-mock-library.md
kbase-extension/static/kbase/js/common/dialogMessages.js
kbase-extension/static/kbase/js/util/appCellUtil.js
kbase-extension/static/kbase/js/util/jobStateViewer.js
kbase-extension/static/narrative_paths.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/bulkImportCell/tabs/configure.js
test/unit/spec/appWidgets/view/newObjectViewSpec.js
test/unit/spec/appWidgets/view/selectViewSpec.js
test/unit/spec/common/cellComponents/filePathWidget-Spec.js
test/unit/spec/common/dialogMessages-spec.js
test/unit/spec/nbextensions/appCell2/widgets/appCellWidget-spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js
test/unit/spec/nbextensions/bulkImportCell/main-spec.js
test/unit/spec/nbextensions/codeCell/main-spec.js
test/unit/spec/util/appCellUtil-spec.js

Fixed various bugs and did a bit of general formatting for good measure.
Changes to note (will be commented in the PR):
- fix message for cancelling batch jobs and add tests for dialog message generation (fixes DATAUP-579)
- add function to generate file type mappings (used by the bulk import cell configure tab and soon by the job status table)
- fix bulk import cell to use correct data to create the status line in the cell header (fixes DATAUP-484)

DATAUP-532: misc fixes

---

kbase-extension/static/narrative_paths.js

Temporarily exclude jobCommChannel from the minified JS build for troubleshooting
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-575

DATAUP-575: debug jcc

---

kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js

Job Status Table layout changes:
- removed status details column
- added import type and output columns
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-494

DATAUP-494: table layout changes

---

bower.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

This is just here to test deployment of different version tags on CI.

test version bump deploy

---

kbase-extension/static/kbase/custom/custom.js
kbase-extension/static/kbase/js/common/jobs.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseCellToolbarMenu.js
test/unit/spec/common/jobs-Spec.js
test/unit/spec/common/props-Spec.js

Adding collapsed cell states for the bulk cell. 
Misc tidying / eslint error fixes in custom.js
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-496

DATAUP-496: add summary to collapsed cell state

---

src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/job.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/jobs/jobmanager.py
src/biokbase/narrative/tests/data/ee2_job_test_data.json
src/biokbase/narrative/tests/narrative_mock/mockclients.py
src/biokbase/narrative/tests/test_job.py
src/biokbase/narrative/tests/test_jobcomm.py
src/biokbase/narrative/tests/test_jobmanager.py

New method to fetch jobs by cell ID.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-583

DATAUP-583: get jobs by cell ID

---

RELEASE_NOTES.md
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

Bump the version string to 5.0.0 in the various places.
No other code changes.

version bump to 5.0.0

---

kbase-extension/static/kbase/js/common/busEventManager.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTab.js
kbase-extension/static/kbase/js/common/jobManager.js
nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/bulkImportCell/tabs/configure.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

Some fixes to bugs found during testing on CI. See inline comments.
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-!!!

DATAUP-654: Cell reset fix and other little bits and pieces

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/uploadTour.js
test/unit/spec/narrative_core/upload/uploadTour-spec.js

The staging area viewer and assorted components have all changed during this project, and the help tour hasn't kept up, leading to some odd behavior and failures.
This fixes that and adds some minor tweaks to show a tour of newer items. This isn't necessarily intended to be the Final Word of information, but a place to start and for the outreach and docs team to help wordsmith.
A note about testing - an `uploadTour` test suite was added. It's not as thorough as it could be, with unit testing through all of the steps, as that was problematic. I suspect there are conflicts with in Jupyter-installed (and developed) BootstrapTour module, with our usage of jquery and how other things are working, specifically with how Bootstrap Popovers work. From research on the errors I've seen, other …

DATAUP-651 fix staging tour

---

RELEASE_NOTES.md

This is a test PR to see if images are being made that have missing changes. Hopefully, if merged, then the image deployed to CI will contain everything it should...

TESTING - update release notes

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/uploadTour.js

Update the staging area tour text based on  feedback.
No actual code changes.

update staging tour text

---

docs/design/job_architecture.md
kbase-extension/static/kbase/js/common/jobCommChannel.js
kbase-extension/static/kbase/js/common/jobs.js
src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/tests/test_appmanager.py
src/biokbase/narrative/tests/test_jobcomm.py
test/data/jobsData.js
test/unit/spec/common/jobCommChannel-spec.js

Final batch of job name standardisations.

DATAUP-497: more search and replace

---

docs/developer/data_import.md

Address some clarifying comments in the previous PR #2605 to add to the uploader app configuration documentation.
No code changes.

DATAUP-608 add uploader docs

---

kbase-extension/static/kbase/js/common/jobManager.js
test/unit/spec/common/jobManager-Spec.js

The JS job manager relied on the `updated` field of the job state object to see whether or not it had changed since last seen. This risks missing some updates, so this PR implements a comparison of the whole jobState object when assessing whether or not to update.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-687

DATAUP-687: ensure FE gets job updates

---

kbase-extension/static/kbase/js/widgets/appWidgets2/input/dynamicDropdownInput.js

Dynamic dropdown changes

---

kbase-extension/static/kbase/config/staging_upload.json
test/unit/spec/narrative_core/upload/stagingAreaViewer-spec.js

Changed upload type selector labels:
* GFF Genome -> GFF/FASTA Genome
* GFF Metagenome -> GFF/FASTA Metagenome
This is just a configuration change, no code changes.

DATAUP-633 change GFF uploader dropdown names

---

src/biokbase/narrative/tests/data/app_specs.json
src/biokbase/narrative/tests/test_appmanager.py

This is mostly a big search-and-replace of repeated strings, plus I added some missing app specs to the test data.
The frontend tests failed but backend tests passed.

DATAUP-497: more cleanup

---

docs/design/job_architecture.md

Updating the jobs docs with the info about the shared controlled vocabulary for jobs stuff.

DATAUP-497: Updating jobs architecture docs

---

docs/design/job_architecture.md
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobStatusTable.js
kbase-extension/static/kbase/js/common/jobCommChannel.js
kbase-extension/static/kbase/js/common/jobCommMessages.js
kbase-extension/static/kbase/js/common/jobManager.js
kbase-extension/static/kbase/js/kbaseNarrative.js
kbase-extension/static/kbase/js/util/jobLogViewer.js
kbase-extension/static/kbase/js/util/jobStateViewer.js
kbase-extension/static/kbase/js/widgets/appWidgets2/customWidgetWrapper.js
kbase-extension/static/kbase/js/widgets/custom/advancedViewerOutputWrapper.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeJobStatus.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeWorkspace.js
nbextensions/appCell2/widgets/appCellWidget.js
nbextensions/appCell2/widgets/appOutputWidget.js
nbextensions/appCell2/widgets/tabs/status/jobInputParams.js
nbextensions/appCell2/widgets/tabs/status/jobStateList.js
nbextensions/bulkImportCell/bulkImportCell.js
nbextensions/outputCell/widgets/outputCell.js
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobCommChannel-spec.js
test/unit/spec/common/jobCommMessages-spec.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/common/jobs-Spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js
test/unit/spec/util/jobLogViewerSpec.js

- split out JobCommMessages into a separate module
- add validation tests for run_status and a general message validator for incoming kernel messages

DATAUP-497: job comm channel 

---

kbase-extension/static/kbase/js/common/jobCommChannel.js
kbase-extension/static/kbase/js/common/jobs.js
test/data/jobsData.js
test/unit/spec/common/jobCommChannel-spec.js
test/unit/spec/common/jobs-Spec.js

- Added a method to validate RUN_STATUS messages
- Added a method to validate an incoming kernel job message and remove any invalid data from it

DATAUP-497: kernel job validation

---

RELEASE_NOTES.md
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

Bump the version number in the usual places, including release notes.
Note that this will need a final configuration change before deployment - this should be done on the master branch to avoid continual conflicts on develop.

bump version numbers for 5.0.1 release

---

kbase-extension/static/kbase/js/widgets/narrative_core/upload/importSetup.js
test/unit/spec/narrative_core/upload/importSetup-spec.js

If file names are sufficiently long enough, or there's enough of them, then multiple calls to the staging service have to get made to get bulk specification data. Since these are separate calls, if multiple files have the same data type, that error won't get caught by the server, so we have to catch it by checking the response.
This does that, then wrangles a fake service error that the rest of the error parsing machinery can take from there.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-696
- [n/a] [Version has been bumped](https://semver.org/) for each …

DATAUP-696 II capture 'multiple types' error some more

---

package-lock.json
test/unit/spec/common/cellComponents/tabs/jobStatusTable-Spec.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/util/jobLogViewerSpec.js

Update tests that generate job messages to allow changes to message structure to be made more easily

DATAUP-497: update tests to facilitate message batching

---

test/unit/spec/appWidgets/input/structInputSpec.js

fix structInput tests to have correct config

---

kbase-extension/static/kbase/js/common/monoBus.js
nbextensions/appCell2/widgets/appCellWidget-fsm.js
nbextensions/appCell2/widgets/appCellWidget.js
test/data/jobsData.js
test/unit/spec/nbextensions/appCell2/widgets/appCellWidget-spec.js

Adding tests for the App Cell Widget

DATAUP-497: app cell widget tests

---

RELEASE_NOTES.md
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

No code changes, just increase version number in the usual places to 5.0.2

bump version to 5.0.2

---

docs/deploy_narrative.md

Some very minor tweaks to the Narrative release ritual in response to recent DevOps changes.
No code changes here.

Update release docs slightly

---

src/biokbase/narrative/jobs/appmanager.py
src/biokbase/narrative/tests/test_appmanager.py

Fix errors from the previous merge.
FE and BE tests are failing on GHA, but they passed when I ran them locally.

Fixing merge errors

---

kbase-extension/static/kbase/custom/custom.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/jobStatus/jobActionDropdown.js
kbase-extension/static/kbase/js/common/cellComponents/tabs/results/resultsTab.js
kbase-extension/static/kbase/js/common/jobManager.js
kbase-extension/static/kbase/js/common/jobStateViewer.js
nbextensions/appCell2/widgets/tabs/resultsViewer.js
nbextensions/bulkImportCell/bulkImportCell.js
package-lock.json
test/unit/spec/common/cellComponents/tabs/results/resultsTab-spec.js
test/unit/spec/nbextensions/bulkImportCell/bulkImportCell-spec.js

Some minor bits and pieces, mostly relating to the job manager:
- use existing functions to access the job index
- use the job manager in the results tab to standardise access to indexed jobs
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-719

DATAUP-719: minor fixes

---

.github/workflows/ReleaseCycleProposal.md
.github/workflows/build_and_push_image.yml
.github/workflows/build_prodrc_pr.yaml
.github/workflows/integration_test.yml
.github/workflows/tag_latest_image.yaml
.github/workflows/unit_test.yml
.gitignore
README.md
docs/deploy_narrative.md
docs/git-workflow.md
docs/install/deployment_eap.md
docs/install/dockerhub_builds.md
scripts/push2dockerhub.sh
src/config.json
src/config.json.templ

Search and replace and/or delete of mentions of a `master` branch; now using the term `main` instead.
Related Jira ticket: N/A

Renaming master branch to main

---

RELEASE_NOTES.md
src/requirements.txt

Just a couple extra python dependency updates.
- [n/a] My code follows the guidelines at https://sites.google.com/lbl.gov/trussresources/home?authuser=0
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] My changes generate no new warnings
- [n/a] I have added tests that prove my fix is effective or that my feature works

update python deps

---

kbase-extension/static/kbase/js/api/RestAPIClient.js
kbase-extension/static/kbase/js/api/StagingServiceClient.js
kbase-extension/static/kbase/js/common/ui.js
nbextensions/bulkImportCell/tabs/configure.js
nbextensions/bulkImportCell/tabs/xsvGenerator.js
test/unit/spec/api/RestAPIClient-spec.js
test/unit/spec/api/StagingServiceClient-spec.js
test/unit/spec/nbextensions/bulkImportCell/tabs/configure-spec.js
test/unit/spec/nbextensions/bulkImportCell/tabs/xsvGenerator-spec.js

Making a start on the bones of the XSV generator. Comments inline.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-744

DATAUP-744: the grand new XSV Generator

---

kbase-extension/static/kbase/js/common/dialogMessages.js
kbase-extension/static/kbase/js/common/semaphore.js
nbextensions/appCell2/appCell.js
nbextensions/appCell2/widgets/appCellWidget-fsm.js
nbextensions/appCell2/widgets/appCellWidget.js
test/unit/spec/nbextensions/appCell2/widgets/appCellWidget-spec.js

Reorganising the methods in the app cell and adding tests for cell reset and job cancellation
See inline docs for more details
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-729

DATAUP-729: app cell params clean up

---

nbextensions/bulkImportCell/tabs/xsvGenerator.js

DATAUP-747: Docs link

---

kbase-extension/static/kbase/js/common/jobManager.js
nbextensions/appCell2/widgets/appCellWidget-fsm.js
nbextensions/appCell2/widgets/appCellWidget.js
test/unit/spec/common/jobManager-Spec.js
test/unit/spec/nbextensions/appCell2/widgets/appCellWidget-spec.js

- removing unused variables
- compact down the FSM stuff
Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-729

DATAUP-729: a bit more clean up

---

nbextensions/bulkImportCell/tabs/xsvGenerator.js

Adding a bit of blurb to the XSV generator dialog box and some styling to the "errors present" message.

DATAUP-747: minor text edits

---

package-lock.json
test/unit/spec/function_output/kbaseDefaultObjectView-spec.js
test/unit/spec/nbextensions/appCell2/widgets/appCellWidget-spec.js
test/unit/spec/nbextensions/bulkImportCell/tabs/configure-spec.js

I found that tests were failing oddly during some local work. I think it was mostly because I was configured against production, which exposed some old test code with hard-coded workspace URLs. Ugh.
This fixes that, and a missing bit of config for the xsvGenerator.

fix some tests

---

RELEASE_NOTES.md
kbase-extension/static/kbase/js/widgets/appWidgets2/input/selectInput.js
package-lock.json
test/unit/spec/appWidgets/input/selectInputSpec.js

Make a more generic bit of error text for missing select values.

DATAUP-753 change error text for select

---

kbase-extension/static/kbase/js/widgets/function_output/modeling/KBModeling.js

Removing service version from use of BiochemistryAPI

---

nbextensions/bulkImportCell/tabs/xsvGenerator.js

Updating bulk import link
Related Jira ticket: N/A

Updating bulk import link per Ellen

---

kbase-extension/static/kbase/js/widgets/function_output/modeling/KBModeling.js

Updating service version to be null

---

kbase-extension/static/kbase/config/staging_upload.json

This was specifically removed from the `main` branch. Tweaking the config file here should put a new commit at the end of the chain and allow merging without much drama. I think.

Activate xSV in the staging browser

---

RELEASE_NOTES.md
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

Just updating the version string in the usual places. No code changes.

update version to 5.1.2

---

RELEASE_NOTES.md
package-lock.json
package.json
src/requirements.txt

Will nothing make dependabot happy? I guess we were a few updates behind...
Related Jira ticket: https://kbase-jira.atlassian.net/browse/UIP-16
Rest of checklist was not relevant, other than release notes, which have been updated.

UIP-16 more dependabot upgrades

---

.github/workflows/integration_test.yml
.github/workflows/unit_test.yml
RELEASE_NOTES.md
src/requirements.txt

Update python dependencies for Feb 2023

---

RELEASE_NOTES.md
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

No other code changes, just the usual version stamps and a package-json rebuild.

bump version to 5.1.4

---

RELEASE_NOTES.md
package-lock.json
package.json
src/requirements.txt

No sooner do you update a load of dependencies than a load more turn up!
One python and one JS dep updated.
closes #3316 
closes #3315 
closes #3299 
closes #3298 
closes #3297 
closes #3287 
closes #3286 
closes #3284 
closes #3257 
closes #3254

Updating dependencies for July 2023

---

RELEASE_NOTES.md
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

Change various text fields to reflect version update. No code changes.

Bump version to 5.2.0

---

RELEASE_NOTES.md
src/requirements.txt

Combine dependabot updates for the Python side into one PR. These are all pretty minor this month.
Updates release notes as well. No actual code changes.

Python updates September 2023

---

RELEASE_NOTES.md
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

Getting ready to release a bugfix. No code changes.

bump version to 5.2.1

---

RELEASE_NOTES.md
package.json
src/biokbase/narrative/jobs/appmanager.py
src/requirements.txt

- updating python deps for Nov 2023
- reformatting one file that had gone astray
- updating the command for the browserslist thing
N/A

PyDeps Nov 2023

---

src/biokbase/narrative/jobs/specmanager.py

I was on autopilot and added typing and function documentation to this class before I knew what I was doing.

Adding typing and some documentation to the specmanager class

---

RELEASE_NOTES.md
src/requirements.txt

Python dependency updates.
It was very satisfying to be able to C&P the dependabot list from GitHub and then use a regex to generate the summary for the release notes.

Updating python deps for Feb 2024

---

Dockerfile

remove nodejs install from dockerfile

---

Dockerfile
package-lock.json

Use the latest version of the narrative base image for building the narrative.

Use latest narr base image

---

.github/workflows/build_prodrc_pr.yaml
.github/workflows/build_test_pr.yaml
.github/workflows/unit_test.yml

Updating codecov call and passing in secret in the vain hope that it will fix the test coverage upload that keeps failing.
ETA: it worked... but that might just be a coincidence.

Attempt to fix finicky codecov

---

RELEASE_NOTES.md
docker_image_dependencies/python-requirements.txt
src/biokbase/narrative/jobs/jobcomm.py
src/biokbase/narrative/tests/narrative_mock/mockcomm.py
src/requirements-dev.txt
src/requirements.txt

June python updates
Related Jira ticket: https://kbase-jira.atlassian.net/browse/UIP-47

UIP-47: June Python updates

---

.github/workflows/build_and_push_image.yml
.github/workflows/build_test_pr.yaml
.github/workflows/integration_test.yml
.github/workflows/tag_latest_image.yaml
.github/workflows/unit_test.yml

Updating GitHub actions to the most recent versions.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/UIP-47

UIP-47: Updating versions of github actions

---

test/unit/spec/function_output/kbaseReportView-spec.js

This is the first step on migrating download links from the Data Import Export (DIE) service to the Blobstore. Just adding a simple regression test to make sure the file download gets plopped in the download iframe correctly.
(also a chance to exercise the pile of infrastructure changes that have happened recently)
Related Jira ticket: https://kbase-jira.atlassian.net/browse/UIP-45
- [n/a] (Python) I have run Ruff `format` and `check` on changed Python code manually or with a git precommit hook

UIP-45 - add regression test for download path from report

---

RELEASE_NOTES.md
deployment/services/kbase-ui/narrative_version
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

As the title says. No other code changes. A release PR will be made once this is merged.

bump version to 5.3.0

---

kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDataList.js
kbase-extension/static/kbase/js/widgets/narrative_core/kbaseNarrativeDownloadPanel.js
package-lock.json
test/unit/spec/narrative_core/kbaseNarrativeDownloadPanel-spec.js

Error tests, as mentioned in the previous PR, as well as other download status watching.
Related Jira ticket: https://kbase-jira.atlassian.net/browse/UIP-43
- [n/a] (Python) I have run Ruff `format` and `check` on changed Python code manually or with a git precommit hook

UIP-43 include tests for errors, downloader logs

---

RELEASE_NOTES.md
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

Prepping 5.4.0 release that removes data import export things. No code changes here.

bump version to 5.4.0

---

package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

Mainly to release a bug in the staging uploader apps (it doesn't automatically fill out the object input field like it should), but also a bundle of minor dependency updates.

Bump version to 5.4.1

---

RELEASE_NOTES.md
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

Bumps version to 5.4.2, adds brief release notes. no code changes.

PTV-1913 bump version, add release notes

---

RELEASE_NOTES.md
package-lock.json
package.json
src/biokbase/narrative/__init__.py
src/config.json
src/config.json.templ

As the title says. No code changes.

bump version to 5.4.3, add release notes
